export const AGENT_PANEL_MIN_WIDTH = 280;
export const AGENT_PANEL_MAX_WIDTH = 500;
export const AGENT_PANEL_DEFAULT_WIDTH = 380;
export const AGENT_PANEL_ICON_STRIP_WIDTH = 48;
export const AGENT_SIDEBAR_TRANSITION_DURATION_MS = 260;
export const AGENT_SIDEBAR_TRANSITION_EASING = 'cubic-bezier(0.32, 0.72, 0, 1)';
export const AGENT_SIDEBAR_SLIDE_OFFSET_PX = 8;
