#!/usr/bin/env bash
# Creates a GitHub issue for integrating a new AI model.
# Called by the model watcher cron when new models are discovered,
# or manually by developers when adding a new model.
#
# Uses scripts/sh/gh-issue-create.sh for dedup enforcement if available,
# otherwise falls back to direct gh CLI.
#
# Usage:
#   gh-issue-create-model.sh --model "google/nano-banana-2" --category "image" --cost 50 \
#     --fields "prompt, aspect_ratio, output_format" --ratios "1:1, 16:9, 9:16" --refs 14
#
# Options:
#   --model    Required. Model key in owner/name format (e.g. "google/imagen-5")
#   --category Required. Model category (image, video, text, music, voice, etc.)
#   --cost     Required. Estimated cost in credits
#   --fields   Optional. Comma-separated list of model input fields
#   --ratios   Optional. Comma-separated list of supported aspect ratios
#   --refs     Optional. Related issue number(s) for cross-referencing

set -euo pipefail

# --- Parse arguments ---
MODEL=""
CATEGORY=""
COST=""
FIELDS=""
RATIOS=""
REFS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)
      MODEL="$2"
      shift 2
      ;;
    --category)
      CATEGORY="$2"
      shift 2
      ;;
    --cost)
      COST="$2"
      shift 2
      ;;
    --fields)
      FIELDS="$2"
      shift 2
      ;;
    --ratios)
      RATIOS="$2"
      shift 2
      ;;
    --refs)
      REFS="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# --- Validate required args ---
if [[ -z "$MODEL" ]]; then
  echo "Error: --model is required" >&2
  exit 1
fi

if [[ -z "$CATEGORY" ]]; then
  echo "Error: --category is required" >&2
  exit 1
fi

if [[ -z "$COST" ]]; then
  echo "Error: --cost is required" >&2
  exit 1
fi

# --- Build issue title ---
TITLE="feat(models): integrate ${MODEL} (${CATEGORY})"

# --- Build issue body ---
BODY=$(cat <<EOF
## New Model Integration

| Field | Value |
|-------|-------|
| **Model** | \`${MODEL}\` |
| **Category** | ${CATEGORY} |
| **Estimated Cost** | ${COST} credits |
| **Provider** | replicate |
| **Status** | Draft (isActive: false) |

## Auto-Discovery Details

This model was discovered by the model watcher cron (Phase 3 - Dynamic Model System).
A draft entry has been created in the \`models\` collection with \`isActive: false\`.

## Integration Checklist

- [ ] Review model on Replicate: https://replicate.com/${MODEL}
- [ ] Verify pricing estimate (${COST} credits) against actual API costs
- [ ] Configure aspect ratios${RATIOS:+: ${RATIOS}}
- [ ] Configure input fields${FIELDS:+: ${FIELDS}}
- [ ] Add model key to \`ModelKey\` enum in \`../packages/enums/src/model.enum.ts\`
- [ ] Set output capabilities (batch support, durations, end-frame, etc.)
- [ ] Set router metadata (capabilities, costTier, speedTier, qualityTier)
- [ ] Test generation end-to-end
- [ ] Activate model (\`isActive: true\`)
- [ ] Update model documentation

${FIELDS:+## Input Fields
\`\`\`
${FIELDS}
\`\`\`
}
${RATIOS:+## Supported Ratios
${RATIOS}
}
${REFS:+## References
Related: #${REFS}
}

---
_Auto-generated by model watcher cron_
EOF
)

# --- Check for dedup script ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEDUP_SCRIPT="${SCRIPT_DIR}/gh-issue-create.sh"

# Search for existing issues before creating
EXISTING=$(gh issue list --state all --search "integrate ${MODEL}" --repo genfeedai/cloud --json number,title --jq '.[].number' 2>/dev/null || true)

if [[ -n "$EXISTING" ]]; then
  echo "Existing issue(s) found for ${MODEL}: #${EXISTING}"
  echo "Skipping creation to avoid duplicates."
  exit 0
fi

# --- Create the issue ---
if [[ -x "$DEDUP_SCRIPT" ]]; then
  "$DEDUP_SCRIPT" --title "$TITLE" --body "$BODY" --label "models,auto-discovery"
else
  gh issue create \
    --repo genfeedai/cloud \
    --title "$TITLE" \
    --body "$BODY" \
    --label "models" 2>/dev/null || {
      echo "Warning: Failed to create GitHub issue (gh CLI not available or auth issue)" >&2
      echo "Issue title: $TITLE" >&2
      exit 0
    }
fi

echo "Issue created: ${TITLE}"
