import { createEntityAttributes } from '@genfeedai/helpers';

export const presetAttributes = createEntityAttributes([
  'organization',
  'brand',
  'organizationId',
  'brandId',
  'label',
  'description',
  'prompt',
  'key',
  'category',
  'model',
  'provider',
  'platform',
  'camera',
  'aspectRatio',
  'duration',
  'promptTemplate',
  'lighting',
  'lens',
  'cameraMovement',
  'mood',
  'scene',
  'style',
  'blacklists',
  'ingredientId',
  'isActive',
  'isFavorite',
]);
