import { createEntityAttributes } from '@genfeedai/helpers';

export const listingAttributes = createEntityAttributes([
  'seller',
  'organization',
  'type',
  'title',
  'slug',
  'shortDescription',
  'description',
  'price',
  'currency',
  'tags',
  'thumbnail',
  'previewImages',
  'previewVideo',
  'previewData',
  'views',
  'downloads',
  'purchases',
  'rating',
  'reviewCount',
  'likeCount',
  'revenue',
  'version',
  'changelog',
  'status',
  'rejectionReason',
  'publishedAt',
  'canBeSoldSeparately',
  'pricingTier',
  'isOfficial',
  'packageSource',
  'packageSlug',
  'installCount',
  'createdAt',
  'updatedAt',
]);
