import {
  DEFAULT_BEAT_ANALYSIS_DATA,
  DEFAULT_BEAT_SYNC_EDITOR_DATA,
  DEFAULT_BRAND_ASSET_DATA,
  DEFAULT_BRAND_CONTEXT_DATA,
  DEFAULT_BRAND_DATA,
  DEFAULT_ENGAGEMENT_TRIGGER_DATA,
  DEFAULT_HOOK_GENERATOR_DATA,
  DEFAULT_IMAGE_TEXT_OVERLAY_DATA,
  DEFAULT_KEYWORD_TRIGGER_DATA,
  DEFAULT_MUSIC_SOURCE_DATA,
  DEFAULT_PERSONA_CONTENT_PLAN_DATA,
  DEFAULT_PERSONA_PHOTO_SESSION_DATA,
  DEFAULT_PERSONA_VIDEO_CONTENT_DATA,
  DEFAULT_PUBLISH_DATA,
  DEFAULT_SLIDESHOW_IMAGE_BATCH_DATA,
  DEFAULT_SOUND_OVERLAY_DATA,
  DEFAULT_TREND_HASHTAG_INSPIRATION_DATA,
  DEFAULT_TREND_SOUND_INSPIRATION_DATA,
  DEFAULT_TREND_TRIGGER_DATA,
  DEFAULT_TREND_VIDEO_INSPIRATION_DATA,
  DEFAULT_VIDEO_INPUT_DATA,
} from '@workflow-saas/nodes';
import { describe, expect, it } from 'vitest';

const allDefaults: Record<string, unknown> = {
  beatAnalysis: DEFAULT_BEAT_ANALYSIS_DATA,
  beatSyncEditor: DEFAULT_BEAT_SYNC_EDITOR_DATA,
  brand: DEFAULT_BRAND_DATA,
  brandAsset: DEFAULT_BRAND_ASSET_DATA,
  brandContext: DEFAULT_BRAND_CONTEXT_DATA,
  engagementTrigger: DEFAULT_ENGAGEMENT_TRIGGER_DATA,
  hookGenerator: DEFAULT_HOOK_GENERATOR_DATA,
  imageTextOverlay: DEFAULT_IMAGE_TEXT_OVERLAY_DATA,
  keywordTrigger: DEFAULT_KEYWORD_TRIGGER_DATA,
  musicSource: DEFAULT_MUSIC_SOURCE_DATA,
  personaContentPlan: DEFAULT_PERSONA_CONTENT_PLAN_DATA,
  personaPhotoSession: DEFAULT_PERSONA_PHOTO_SESSION_DATA,
  personaVideoContent: DEFAULT_PERSONA_VIDEO_CONTENT_DATA,
  publish: DEFAULT_PUBLISH_DATA,
  slideshowImageBatch: DEFAULT_SLIDESHOW_IMAGE_BATCH_DATA,
  soundOverlay: DEFAULT_SOUND_OVERLAY_DATA,
  trendHashtagInspiration: DEFAULT_TREND_HASHTAG_INSPIRATION_DATA,
  trendSoundInspiration: DEFAULT_TREND_SOUND_INSPIRATION_DATA,
  trendTrigger: DEFAULT_TREND_TRIGGER_DATA,
  trendVideoInspiration: DEFAULT_TREND_VIDEO_INSPIRATION_DATA,
  videoInput: DEFAULT_VIDEO_INPUT_DATA,
};

describe('node default data', () => {
  for (const [name, data] of Object.entries(allDefaults)) {
    describe(name, () => {
      it('is defined and has label', () => {
        expect(data).toBeDefined();
        expect((data as any).label).toBeTruthy();
      });
    });
  }
});
