/**
 * Persona Content Plan Node
 *
 * SAAS category node that generates an N-day content plan for an AI persona.
 * Uses the persona's content strategy (topics, tone, formats, frequency)
 * to create a scheduled content calendar.
 */

import type { BaseNodeData } from '@workflow-saas/types';

/**
 * Content plan entry generated by this node
 */
export interface ContentPlanEntry {
  scheduledDate: string;
  format: string;
  topic: string;
  description: string;
  category: string;
}

/**
 * Persona Content Plan Node Data
 *
 * Inputs:
 * - brand (brand): Brand context
 *
 * Outputs:
 * - plan (object): Generated content plan entries
 */
export interface PersonaContentPlanNodeData extends BaseNodeData {
  type: 'personaContentPlan';

  // Configuration
  personaId: string | null;
  days: number;
  credentialId: string | null;
  createDrafts: boolean;

  // Resolved at execution time
  resolvedPersonaId: string | null;
  resolvedPersonaLabel: string | null;
  resolvedPlanEntries: ContentPlanEntry[];
  resolvedDraftsCreated: number;
}

/**
 * Default data for a new Persona Content Plan node
 */
export const DEFAULT_PERSONA_CONTENT_PLAN_DATA: Partial<PersonaContentPlanNodeData> =
  {
    createDrafts: false,
    credentialId: null,
    days: 7,
    label: 'Content Plan',
    personaId: null,
    resolvedDraftsCreated: 0,
    resolvedPersonaId: null,
    resolvedPersonaLabel: null,
    resolvedPlanEntries: [],
    status: 'idle',
    type: 'personaContentPlan',
  };

/**
 * Persona Content Plan node definition for registry
 */
export const personaContentPlanNodeDefinition = {
  category: 'saas' as const,
  defaultData: DEFAULT_PERSONA_CONTENT_PLAN_DATA,
  description:
    'Generate an N-day content plan based on persona content strategy',
  icon: 'Calendar',
  inputs: [{ id: 'brand', label: 'Brand', required: true, type: 'brand' }],
  label: 'Content Plan',
  outputs: [{ id: 'plan', label: 'Content Plan', type: 'object' }],
  type: 'personaContentPlan',
};
