import { createEntityAttributes } from '@genfeedai/helpers';

export const organizationSettingsAttributes = createEntityAttributes([
  'isWhitelabelEnabled',
  'isVoiceControlEnabled',
  'isWatermarkEnabled',
  'isVerifyScriptEnabled',
  'isVerifyIngredientEnabled',
  'isVerifyVideoEnabled',
  'isGenerateVideosEnabled',
  'isGenerateArticlesEnabled',
  'isGenerateImagesEnabled',
  'isGenerateMusicEnabled',
  'isAutoEvaluateEnabled',
  'isNotificationsDiscordEnabled',
  'isNotificationsEmailEnabled',
  'isWebhookEnabled',
  'webhookEndpoint',
  'webhookSecret',
  'seatsLimit',
  'brandsLimit',
  'timezone',
  'enabledModels',
  'isAdvancedMode',
  'agentReplyStyle',
  'isByokEnabled',
  'defaultAvatarPhotoUrl',
  'defaultVoiceId',
  'defaultVoiceRef',
  'defaultVoiceProvider',
  'defaultModel',
  'defaultModelReview',
  'defaultModelUpdate',
  'onboardingJourneyMissions',
  'onboardingJourneyCompletedAt',
]);
