import { createEntityAttributes } from '@genfeedai/helpers';

export const socialMessageAttributes = createEntityAttributes([
  'conversation',
  'conversationId',
  'organization',
  'organizationId',
  'user',
  'userId',
  'brand',
  'brandId',
  'credential',
  'credentialId',
  'post',
  'postId',
  'platform',
  'direction',
  'messageType',
  'body',
  'externalMessageId',
  'externalParentMessageId',
  'senderExternalId',
  'senderHandle',
  'senderName',
  'senderAvatarUrl',
  'authorRole',
  'status',
  'sourceUrl',
  'idempotencyKey',
  'workflowRunId',
  'agentRunId',
  'actionProvenance',
  'failureReason',
  'metadata',
]);
