import { createEntityAttributes } from '@genfeedai/helpers';

export const socialMessageAttributes = createEntityAttributes([
  'conversationId',
  'organizationId',
  'userId',
  'brandId',
  'credentialId',
  'postId',
  'platform',
  'direction',
  'messageType',
  'body',
  'externalMessageId',
  'externalParentMessageId',
  'senderExternalId',
  'senderHandle',
  'senderName',
  'senderAvatarUrl',
  'authorRole',
  'status',
  'sourceUrl',
  'idempotencyKey',
  'workflowRunId',
  'agentRunId',
  'workflowTriggerStatus',
  'workflowTriggerJobId',
  'workflowTriggerError',
  'workflowTriggerAttemptedAt',
  'workflowTriggerQueuedAt',
  'actionProvenance',
  'failureReason',
  'metadata',
]);
