import { createEntityAttributes } from '@genfeedai/helpers';

export const socialReplyCampaignAttributes = createEntityAttributes([
  'organization',
  'organizationId',
  'brand',
  'brandId',
  'user',
  'userId',
  'name',
  'description',
  'platform',
  'messageType',
  'status',
  'bodyTemplate',
  'maxPerHour',
  'maxPerDay',
  'minDelaySeconds',
  'totalRecipients',
  'sentCount',
  'failedCount',
  'skippedCount',
  'dispatchCursor',
  'startedAt',
  'pausedAt',
  'completedAt',
  'nextRunAt',
  'lastDispatchedAt',
  'lastError',
  'workflowId',
  'workflowExecutionId',
  'metadata',
]);
