import { createEntityAttributes } from '@genfeedai/helpers';

export const sourcePostAttributes = createEntityAttributes([
  'organization',
  'organizationId',
  'brand',
  'brandId',
  'user',
  'userId',
  'source',
  'sourceId',
  'platform',
  'externalId',
  'contentType',
  'text',
  'authorId',
  'authorHandle',
  'authorDisplayName',
  'authorAvatarUrl',
  'authorFollowersCount',
  'sourceUrl',
  'mediaUrls',
  'thumbnailUrl',
  'metrics',
  'hashtags',
  'publishedAt',
  'collectedAt',
  'raw',
]);
