import { createEntityAttributes } from '@genfeedai/helpers';

export const agentRunAttributes = createEntityAttributes([
  'brand',
  'completedAt',
  'creditBudget',
  'creditsUsed',
  'durationMs',
  'error',
  'label',
  'metadata',
  'objective',
  'organization',
  'parentRun',
  'progress',
  'retryCount',
  'startedAt',
  'status',
  'steps',
  'strategy',
  'summary',
  'thread',
  'toolCalls',
  'trigger',
  'user',
]);
