import { createEntityAttributes } from '@genfeedai/helpers';

export const agentTransferAttributes = createEntityAttributes([
  'artifactReferences',
  'artifactVersionPinIds',
  'completedAt',
  'completionSummary',
  'content',
  'correlationId',
  'deliveredAt',
  'deliveryMode',
  'depth',
  'destinationBrandId',
  'destinationMessageId',
  'destinationRunId',
  'destinationThreadId',
  'destinationThreadTitle',
  'failureReason',
  'idempotencyKey',
  'lastAttemptAt',
  'organization',
  'outputArtifactReferences',
  'outputArtifactVersionPinIds',
  'parentCorrelationId',
  'progress',
  'queuedAt',
  'retryCount',
  'selectedContext',
  'sourceBrandId',
  'sourceMessageId',
  'sourceThreadId',
  'sourceThreadTitle',
  'startedAt',
  'status',
  'user',
]);
