import { createEntityAttributes } from '@genfeedai/helpers';

export const outreachCampaignAttributes = createEntityAttributes([
  'aiConfig',
  'brandId',
  'campaignType',
  'completedAt',
  'credentialId',
  'description',
  'discoveryConfig',
  'dmConfig',
  'isActive',
  'label',
  'lastActivityAt',
  'organizationId',
  'platform',
  'rateLimits',
  'schedule',
  'startedAt',
  'status',
  'totalDmsSent',
  'totalFailed',
  'totalReplies',
  'totalSkipped',
  'totalSuccessful',
  'totalTargets',
  'userId',
]);
