import { createEntityAttributes } from '@genfeedai/helpers';

export const replyBotConfigAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'userId',
  'credentialId',
  'name',
  'description',
  'type',
  'platform',
  'actionType',
  'isActive',
  'replyTone',
  'replyLength',
  'replyInstructions',
  'templateId',
  'dmConfig',
  'rateLimits',
  'schedule',
  'filters',
  'monitoredAccountIds',
  'totalRepliesSent',
  'totalDmsSent',
  'totalSkipped',
  'totalFailed',
  'lastActivityAt',
]);
