import { createEntityAttributes } from '@genfeedai/helpers';

export const workflowAttributes = createEntityAttributes([
  'organizationId',
  'userId',
  'brandId',
  'tasks',
  'label',
  'description',
  'key',
  'trigger',
  'status',
  'metadata',
  'schedule',
  'timezone',
  'isScheduleEnabled',
  'nextRunAt',
  'nodes',
  'edges',
  'inputVariables',
  'thumbnail',
  'thumbnailNodeId',
  'lifecycle',
  'lockedNodeIds',
  'cloudSync',
]);
