export * from '@serializers/server/admin/announcement.serializer';
export * from '@serializers/server/admin/business-analytics.serializer';
export * from '@serializers/server/admin/darkroom-cloudfront-invalidation.serializer';
export { DarkroomCloudFrontInvalidationSerializer as FleetCloudFrontInvalidationSerializer } from '@serializers/server/admin/darkroom-cloudfront-invalidation.serializer';
export * from '@serializers/server/admin/darkroom-ec2-action-result.serializer';
export { DarkroomEc2ActionResultSerializer as FleetEc2ActionResultSerializer } from '@serializers/server/admin/darkroom-ec2-action-result.serializer';
export * from '@serializers/server/admin/darkroom-ec2-bulk-action-result.serializer';
export { DarkroomEc2BulkActionResultSerializer as FleetEc2BulkActionResultSerializer } from '@serializers/server/admin/darkroom-ec2-bulk-action-result.serializer';
export * from '@serializers/server/admin/darkroom-ec2-instance.serializer';
export { DarkroomEc2InstanceSerializer as FleetEc2InstanceSerializer } from '@serializers/server/admin/darkroom-ec2-instance.serializer';
export * from '@serializers/server/admin/darkroom-fleet-health.serializer';
export { DarkroomFleetHealthSerializer as FleetHealthSerializer } from '@serializers/server/admin/darkroom-fleet-health.serializer';
export * from '@serializers/server/admin/darkroom-generate-voice-result.serializer';
export { DarkroomGenerateVoiceResultSerializer as FleetGenerateVoiceResultSerializer } from '@serializers/server/admin/darkroom-generate-voice-result.serializer';
export * from '@serializers/server/admin/darkroom-generation-job.serializer';
export { DarkroomGenerationJobSerializer as FleetGenerationJobSerializer } from '@serializers/server/admin/darkroom-generation-job.serializer';
export * from '@serializers/server/admin/darkroom-lip-sync-job.serializer';
export { DarkroomLipSyncJobSerializer as FleetLipSyncJobSerializer } from '@serializers/server/admin/darkroom-lip-sync-job.serializer';
export * from '@serializers/server/admin/darkroom-lip-sync-status.serializer';
export { DarkroomLipSyncStatusSerializer as FleetLipSyncStatusSerializer } from '@serializers/server/admin/darkroom-lip-sync-status.serializer';
export * from '@serializers/server/admin/darkroom-pipeline-campaign.serializer';
export { DarkroomPipelineCampaignSerializer as FleetPipelineCampaignSerializer } from '@serializers/server/admin/darkroom-pipeline-campaign.serializer';
export * from '@serializers/server/admin/darkroom-pipeline-stats.serializer';
export { DarkroomPipelineStatsSerializer as FleetPipelineStatsSerializer } from '@serializers/server/admin/darkroom-pipeline-stats.serializer';
export * from '@serializers/server/admin/darkroom-service-status.serializer';
export { DarkroomServiceStatusSerializer as FleetServiceStatusSerializer } from '@serializers/server/admin/darkroom-service-status.serializer';
export * from '@serializers/server/admin/darkroom-upload-dataset-result.serializer';
export { DarkroomUploadDatasetResultSerializer as FleetUploadDatasetResultSerializer } from '@serializers/server/admin/darkroom-upload-dataset-result.serializer';
export * from '@serializers/server/admin/darkroom-voice.serializer';
export { DarkroomVoiceSerializer as FleetVoiceSerializer } from '@serializers/server/admin/darkroom-voice.serializer';
