import { ApiKeyScope } from '@genfeedai/enums';

export const API_KEY_SCOPE_PRESETS = {
  content: [
    ApiKeyScope.VIDEOS_READ,
    ApiKeyScope.VIDEOS_CREATE,
    ApiKeyScope.IMAGES_READ,
    ApiKeyScope.IMAGES_CREATE,
    ApiKeyScope.PROMPTS_READ,
    ApiKeyScope.PROMPTS_CREATE,
    ApiKeyScope.ARTICLES_READ,
    ApiKeyScope.ARTICLES_CREATE,
    ApiKeyScope.POSTS_CREATE,
  ],
  full: [
    ApiKeyScope.VIDEOS_READ,
    ApiKeyScope.VIDEOS_CREATE,
    ApiKeyScope.VIDEOS_UPDATE,
    ApiKeyScope.VIDEOS_DELETE,
    ApiKeyScope.IMAGES_READ,
    ApiKeyScope.IMAGES_CREATE,
    ApiKeyScope.IMAGES_UPDATE,
    ApiKeyScope.IMAGES_DELETE,
    ApiKeyScope.PROMPTS_READ,
    ApiKeyScope.PROMPTS_CREATE,
    ApiKeyScope.PROMPTS_UPDATE,
    ApiKeyScope.PROMPTS_DELETE,
    ApiKeyScope.ARTICLES_READ,
    ApiKeyScope.ARTICLES_CREATE,
    ApiKeyScope.BRANDS_READ,
    ApiKeyScope.CREDITS_READ,
    ApiKeyScope.POSTS_CREATE,
    ApiKeyScope.ANALYTICS_READ,
  ],
  mcp: [
    ApiKeyScope.VIDEOS_READ,
    ApiKeyScope.VIDEOS_CREATE,
    ApiKeyScope.IMAGES_READ,
    ApiKeyScope.IMAGES_CREATE,
    ApiKeyScope.PROMPTS_READ,
    ApiKeyScope.PROMPTS_CREATE,
    ApiKeyScope.ARTICLES_READ,
    ApiKeyScope.ARTICLES_CREATE,
    ApiKeyScope.BRANDS_READ,
    ApiKeyScope.CREDITS_READ,
    ApiKeyScope.POSTS_CREATE,
    ApiKeyScope.ANALYTICS_READ,
  ],
  read: [
    ApiKeyScope.VIDEOS_READ,
    ApiKeyScope.IMAGES_READ,
    ApiKeyScope.PROMPTS_READ,
    ApiKeyScope.ARTICLES_READ,
    ApiKeyScope.BRANDS_READ,
    ApiKeyScope.CREDITS_READ,
    ApiKeyScope.ANALYTICS_READ,
  ],
} as const satisfies Record<string, readonly ApiKeyScope[]>;

export type ApiKeyScopePreset = keyof typeof API_KEY_SCOPE_PRESETS;
