CREATE TYPE "AgentFailureReason" AS ENUM (
  'PROVIDER_CONFIGURATION', 'INSUFFICIENT_CREDITS', 'RATE_LIMITED', 'TIMEOUT',
  'DATA_SAVE_FAILED', 'SESSION_EXPIRED', 'CONNECTION_INTERRUPTED', 'CANCELLED',
  'PROVIDER_AUTHENTICATION', 'WORKSPACE_MISSING', 'ACTION_NOT_ALLOWED',
  'MODEL_UNAVAILABLE', 'PROVIDER_ACCESS_DENIED', 'PROVIDER_UNAVAILABLE', 'UNKNOWN'
);

ALTER TABLE "workflow_executions"
  ADD COLUMN "failureReason" "AgentFailureReason",
  ADD COLUMN "failure" JSONB;
