/**
 * GENERATED — do not edit by hand.
 * Source: packages/prisma/prisma/schema.prisma
 * Regenerate: `cd packages/prisma && bun run db:generate`
 *
 * Static model/field metadata for BaseService enum normalisation.
 * Replaces runtime `_runtimeDataModel` lookup which is not populated
 * by the PrismaPg driver adapter under Prisma 7.
 */

/** Per-field enum metadata (used by BaseService). */
export interface EnumFieldMeta {
  /** Prisma enum type name, e.g. "IngredientCategory". */
  enumType: string;
  /** True when the column is NOT NULL in the schema. */
  isRequired: boolean;
}

/** Per-model field metadata. */
export interface ModelFieldMeta {
  /**
   * All scalar + enum field names present on the model.
   * Used by modelHasField().
   */
  allFields: ReadonlyArray<string>;
  /**
   * List field names present on the model, including scalar lists.
   * Used by modelHasField() for list-valued Prisma columns.
   */
  listFields: ReadonlyArray<string>;
  /**
   * Enum fields: fieldName -> EnumFieldMeta.
   * Only fields whose type is a Prisma enum appear here.
   */
  enumFields: Readonly<Record<string, EnumFieldMeta>>;
}

/**
 * Complete model metadata map.
 * Key = PascalCase model name matching Prisma.ModelName.
 */
export const PRISMA_MODEL_METADATA: Readonly<Record<string, ModelFieldMeta>> = {
  Account: {
    allFields: [
      'accessToken',
      'accessTokenExpiresAt',
      'accountId',
      'createdAt',
      'id',
      'idToken',
      'password',
      'providerId',
      'refreshToken',
      'refreshTokenExpiresAt',
      'scope',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Activity: {
    allFields: [
      'action',
      'brand',
      'brandId',
      'createdAt',
      'data',
      'entityId',
      'entityModel',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  AdBulkUploadJob: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'credential',
      'credentialId',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AdCreativeMapping: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AdOptimizationAuditLog: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AdOptimizationConfig: {
    allFields: [
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AdOptimizationRecommendation: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AdPerformance: {
    allFields: [
      'adPlatform',
      'brand',
      'brandId',
      'conversionRate',
      'cpa',
      'cpc',
      'createdAt',
      'credential',
      'credentialId',
      'ctaText',
      'ctr',
      'data',
      'dataConfidence',
      'headlineText',
      'id',
      'industry',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'performanceScore',
      'roas',
      'scope',
      'spend',
      'spendBucket',
      'updatedAt',
    ],
    listFields: ['ctaPatternCategories', 'headlinePatternCategories'],
    enumFields: {},
  },
  AgentCampaign: {
    allFields: [
      'brand',
      'brandId',
      'campaignLeadStrategy',
      'campaignLeadStrategyId',
      'config',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['agents', 'memories'],
    enumFields: {},
  },
  AgentGoal: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['strategies'],
    enumFields: {},
  },
  AgentMemory: {
    allFields: [
      'brand',
      'brandId',
      'campaign',
      'campaignId',
      'confidence',
      'content',
      'contentType',
      'createdAt',
      'id',
      'importance',
      'kind',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'performanceSnapshot',
      'platform',
      'scope',
      'sourceContentId',
      'sourceMessageId',
      'sourceType',
      'sourceUrl',
      'summary',
      'type',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['tags'],
    enumFields: {},
  },
  AgentMessage: {
    allFields: [
      'artifactReferenceEligibleReadCount',
      'artifactReferences',
      'brand',
      'brandId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'isLegacyArtifactReferenceEligible',
      'legacyArtifactReferenceLastSource',
      'legacyArtifactReferenceLastUsedAt',
      'legacyArtifactReferenceReadCount',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'role',
      'thread',
      'threadId',
      'toolCalls',
      'toolResults',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['artifactVersionPinIds'],
    enumFields: {},
  },
  AgentRun: {
    allFields: [
      'artifactReferences',
      'brand',
      'brandId',
      'completedAt',
      'config',
      'createdAt',
      'creditBudget',
      'creditsUsed',
      'durationMs',
      'error',
      'id',
      'isDeleted',
      'label',
      'metadata',
      'mongoId',
      'objective',
      'organization',
      'organizationId',
      'parentRun',
      'parentRunId',
      'progress',
      'result',
      'retryCount',
      'startedAt',
      'status',
      'steps',
      'strategy',
      'strategyId',
      'summary',
      'thread',
      'threadId',
      'toolCalls',
      'trigger',
      'type',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'artifactVersionPinIds',
      'captions',
      'childRuns',
      'ingredients',
      'newsletters',
      'posts',
      'tasks',
    ],
    enumFields: {
      status: { enumType: 'AgentRunStatus', isRequired: true },
    },
  },
  AgentStrategy: {
    allFields: [
      'agentType',
      'brand',
      'brandId',
      'config',
      'createdAt',
      'description',
      'goal',
      'goalId',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'policies',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'batches',
      'campaignLeads',
      'campaigns',
      'ingredients',
      'opportunities',
      'platforms',
      'posts',
      'reports',
      'runs',
    ],
    enumFields: {},
  },
  AgentStrategyOpportunity: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'strategy',
      'strategyId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AgentStrategyReport: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'strategy',
      'strategyId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AgentThread: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'contextVersion',
      'createdAt',
      'id',
      'isDeleted',
      'isLegacyBrandFallbackEligible',
      'isPinned',
      'legacyBrandFallbackCount',
      'legacyBrandFallbackLastBrandId',
      'legacyBrandFallbackLastSource',
      'legacyBrandFallbackLastUsedAt',
      'mongoId',
      'organization',
      'organizationId',
      'parentThreadId',
      'planModeEnabled',
      'requestedModel',
      'runtimeKey',
      'scopeChangeProvenance',
      'source',
      'status',
      'systemPrompt',
      'title',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'contextStates',
      'events',
      'memoryEntryIds',
      'messages',
      'posts',
      'runs',
      'snapshots',
      'tasks',
    ],
    enumFields: {},
  },
  AgentThreadEvent: {
    allFields: [
      'commandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'runId',
      'sequence',
      'thread',
      'threadId',
      'type',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AgentThreadSnapshot: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'thread',
      'threadId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  AgentWorkflow: {
    allFields: [
      'config',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Analytic: {
    allFields: ['createdAt', 'data', 'id', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  Announcement: {
    allFields: [
      'config',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'title',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ApiKey: {
    allFields: [
      'category',
      'createdAt',
      'description',
      'expiresAt',
      'id',
      'isRevoked',
      'key',
      'keyFingerprint',
      'label',
      'lastUsedAt',
      'lastUsedIp',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'rateLimit',
      'revokedAt',
      'updatedAt',
      'usageCount',
      'user',
      'userId',
    ],
    listFields: ['allowedIps', 'scopes'],
    enumFields: {
      category: { enumType: 'ApiKeyCategory', isRequired: true },
    },
  },
  Article: {
    allFields: [
      'brand',
      'brandId',
      'category',
      'content',
      'coverImageUrl',
      'createdAt',
      'excerpt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'publishedAt',
      'scope',
      'seoBreakdown',
      'seoScore',
      'slug',
      'status',
      'title',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'articleAnalytics',
      'newsletters',
      'postEntities',
      'prompts',
      'tags',
      'transcripts',
    ],
    enumFields: {
      status: { enumType: 'ArticleStatus', isRequired: true },
    },
  },
  ArticleAnalytics: {
    allFields: [
      'article',
      'articleId',
      'brand',
      'brandId',
      'createdAt',
      'date',
      'engagementRate',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'totalComments',
      'totalLikes',
      'totalShares',
      'totalViews',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Asset: {
    allFields: [
      'category',
      'cloudObjectKey',
      'createdAt',
      'displayName',
      'externalId',
      'id',
      'isDeleted',
      'kind',
      'localAssetId',
      'mimeType',
      'mongoId',
      'origin',
      'originalFileName',
      'parentArticleId',
      'parentBrandId',
      'parentIngredientId',
      'parentOrgId',
      'parentType',
      'residency',
      'sha256',
      'sizeBytes',
      'updatedAt',
      'uploadPolicy',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      category: { enumType: 'AssetCategory', isRequired: true },
      parentType: { enumType: 'AssetParent', isRequired: true },
    },
  },
  Batch: {
    allFields: [
      'agentStrategy',
      'agentStrategyId',
      'brand',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'items',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'BatchStatus', isRequired: true },
    },
  },
  BatchWorkflowJob: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'items',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'userId',
      'workflow',
      'workflowId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'BatchStatus', isRequired: true },
    },
  },
  Bookmark: {
    allFields: [
      'author',
      'authorHandle',
      'brand',
      'brandId',
      'category',
      'content',
      'createdAt',
      'description',
      'folder',
      'folderId',
      'id',
      'intent',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'platformData',
      'processedAt',
      'savedAt',
      'thumbnailUrl',
      'title',
      'updatedAt',
      'url',
      'user',
      'userId',
    ],
    listFields: [
      'extractedIngredients',
      'generatedIngredients',
      'ingredients',
      'mediaUrls',
      'tags',
    ],
    enumFields: {
      category: { enumType: 'BookmarkCategory', isRequired: true },
      intent: { enumType: 'BookmarkIntent', isRequired: true },
      platform: { enumType: 'BookmarkPlatform', isRequired: true },
    },
  },
  Bot: {
    allFields: [
      'brandId',
      'category',
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'settings',
      'status',
      'targets',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['platforms'],
    enumFields: {
      status: { enumType: 'BotStatus', isRequired: true },
    },
  },
  BotActivity: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'monitoredAccount',
      'monitoredAccountId',
      'organization',
      'organizationId',
      'replyBotConfig',
      'replyBotConfigId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Brand: {
    allFields: [
      'agentConfig',
      'backgroundColor',
      'createdAt',
      'defaultImageModel',
      'defaultImageToVideoModel',
      'defaultMusicModel',
      'defaultVideoModel',
      'description',
      'fontFamily',
      'id',
      'isActive',
      'isDefault',
      'isDeleted',
      'isFleetEnabled',
      'isHighlighted',
      'isSelected',
      'label',
      'mongoId',
      'moodBoard',
      'musicIngredient',
      'musicIngredientId',
      'organization',
      'organizationId',
      'primaryColor',
      'referenceImages',
      'scope',
      'secondaryColor',
      'slug',
      'text',
      'updatedAt',
      'user',
      'userId',
      'voiceIngredient',
      'voiceIngredientId',
    ],
    listFields: [
      'activities',
      'adBulkUploadJobs',
      'adCreativeMappings',
      'adPerformances',
      'agentCampaigns',
      'agentGoals',
      'agentMemories',
      'agentMessages',
      'agentRuns',
      'agentStrategies',
      'agentStrategyOpportunities',
      'agentStrategyReports',
      'agentThreads',
      'articleAnalytics',
      'articles',
      'batches',
      'bookmarks',
      'botActivities',
      'brandInterviews',
      'brandMemories',
      'clipProjects',
      'contentDrafts',
      'contentPerformances',
      'contentPlanItems',
      'contentPlans',
      'contentRuns',
      'contentSchedules',
      'contentVersionPins',
      'contextBases',
      'creativePatterns',
      'credentials',
      'dashboardLayouts',
      'distributions',
      'editorProjects',
      'folders',
      'ingredients',
      'lastUsedByMembers',
      'links',
      'listeningEvidence',
      'listeningTopicSources',
      'listeningTopics',
      'members',
      'monitoredAccounts',
      'newsletters',
      'personas',
      'postAnalytics',
      'postGroups',
      'posts',
      'presets',
      'proactiveLeads',
      'prompts',
      'publishApprovals',
      'schedules',
      'socialConversations',
      'socialMessages',
      'socialSources',
      'sourcePosts',
      'tags',
      'trackedLinks',
      'trainings',
      'trendPreferences',
      'trendRemixLineages',
      'trends',
      'warmupAccounts',
      'watchlists',
      'workflows',
    ],
    enumFields: {
      fontFamily: { enumType: 'FontFamily', isRequired: true },
      scope: { enumType: 'AssetScope', isRequired: true },
    },
  },
  BrandInterview: {
    allFields: [
      'answeredFields',
      'brand',
      'brandId',
      'completenessAfter',
      'completenessBefore',
      'createdAt',
      'creditsCharged',
      'currentFieldKey',
      'id',
      'isDeleted',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['askedFieldKeys'],
    enumFields: {
      status: { enumType: 'BrandInterviewStatus', isRequired: true },
    },
  },
  BrandMemory: {
    allFields: [
      'brand',
      'brandId',
      'content',
      'createdAt',
      'date',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'type',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  CampaignTarget: {
    allFields: [
      'campaign',
      'campaignId',
      'createdAt',
      'data',
      'errorMessage',
      'externalId',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'processedAt',
      'replyExternalId',
      'replyText',
      'replyUrl',
      'retryCount',
      'scheduledAt',
      'skipReason',
      'status',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Caption: {
    allFields: [
      'agentRun',
      'agentRunId',
      'content',
      'createdAt',
      'id',
      'ingredient',
      'ingredientId',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  ClipProject: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'error',
      'failedClipCount',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'pendingClipCount',
      'progress',
      'readiness',
      'readyClipCount',
      'status',
      'terminalAt',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ClipResult: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'isSelected',
      'mode',
      'mongoId',
      'organization',
      'organizationId',
      'projectId',
      'providerJobId',
      'readiness',
      'status',
      'terminalAt',
      'updatedAt',
      'viralityScore',
    ],
    listFields: [],
    enumFields: {},
  },
  ContentDraft: {
    allFields: [
      'approvedBy',
      'approvedById',
      'approvedVersionPin',
      'approvedVersionPinId',
      'brand',
      'brandId',
      'confidence',
      'content',
      'contentRun',
      'contentRunId',
      'createdAt',
      'data',
      'generatedBy',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'skillSlug',
      'status',
      'type',
      'updatedAt',
    ],
    listFields: ['mediaUrls', 'platforms', 'trendRemixLineages'],
    enumFields: {},
  },
  ContentPattern: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'sourceCreator',
      'sourceCreatorId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ContentPerformance: {
    allFields: [
      'brand',
      'brandId',
      'comments',
      'contentRun',
      'contentRunId',
      'contentType',
      'createdAt',
      'cycleNumber',
      'data',
      'engagementRate',
      'externalPostId',
      'generationId',
      'id',
      'isDeleted',
      'likes',
      'measuredAt',
      'mongoId',
      'organization',
      'organizationId',
      'performanceScore',
      'platform',
      'post',
      'postId',
      'revenue',
      'saves',
      'shares',
      'source',
      'updatedAt',
      'userId',
      'variantId',
      'views',
      'workflowExecutionId',
    ],
    listFields: [],
    enumFields: {},
  },
  ContentPlan: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'createdBy',
      'createdById',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: ['items'],
    enumFields: {},
  },
  ContentPlanItem: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'plan',
      'planId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ContentRun: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
    ],
    listFields: ['contentDrafts', 'contentPerformances', 'posts'],
    enumFields: {},
  },
  ContentSchedule: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'cronExpression',
      'id',
      'isActive',
      'isDeleted',
      'isEnabled',
      'lastRunAt',
      'mongoId',
      'name',
      'nextRunAt',
      'organization',
      'organizationId',
      'skillParams',
      'timezone',
      'updatedAt',
    ],
    listFields: ['skillSlugs'],
    enumFields: {},
  },
  ContentScore: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: ['optimizations'],
    enumFields: {},
  },
  ContentVersionPin: {
    allFields: [
      'brand',
      'brandId',
      'contentDigest',
      'createdAt',
      'createdByUser',
      'createdByUserId',
      'id',
      'idempotencyKey',
      'organization',
      'organizationId',
      'provenance',
      'recordId',
      'recordKind',
      'recordVersion',
    ],
    listFields: [
      'publishApprovals',
      'reviewedContentDrafts',
      'reviewedNewsletters',
      'reviewedPosts',
    ],
    enumFields: {},
  },
  ContextBase: {
    allFields: [
      'createdAt',
      'createdBy',
      'createdById',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'sourceBrand',
      'sourceBrandId',
      'updatedAt',
    ],
    listFields: ['entries'],
    enumFields: {},
  },
  ContextEntry: {
    allFields: [
      'contextBase',
      'contextBaseId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  CreativePattern: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  CreatorAnalysis: {
    allFields: [
      'createdAt',
      'createdBy',
      'createdById',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: ['contentPatterns', 'patternPlaybooks'],
    enumFields: {},
  },
  Credential: {
    allFields: [
      'accessToken',
      'accessTokenExpiry',
      'accessTokenSecret',
      'brand',
      'brandId',
      'createdAt',
      'description',
      'externalAvatar',
      'externalHandle',
      'externalId',
      'externalName',
      'id',
      'isConnected',
      'isDeleted',
      'label',
      'mongoId',
      'oauthState',
      'oauthToken',
      'oauthTokenHash',
      'oauthTokenSecret',
      'organization',
      'organizationId',
      'platform',
      'refreshToken',
      'refreshTokenExpiry',
      'updatedAt',
      'user',
      'userId',
      'username',
      'warmupAssessedAt',
      'warmupHoldReason',
      'warmupManualOverride',
      'warmupOverrideConfirmedAt',
      'warmupOverrideConfirmedByUserId',
      'warmupOverrideReason',
      'warmupOverrideUntil',
      'warmupRiskLevel',
      'warmupScore',
      'warmupSignals',
      'warmupState',
      'warmupThresholds',
    ],
    listFields: [
      'adBulkUploadJobs',
      'adPerformances',
      'monitoredAccounts',
      'personas',
      'posts',
      'socialConversations',
      'socialMessages',
      'socialSources',
      'tags',
    ],
    enumFields: {
      platform: { enumType: 'CredentialPlatform', isRequired: true },
    },
  },
  CreditBalance: {
    allFields: [
      'balance',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  CreditTransaction: {
    allFields: [
      'amount',
      'balanceAfter',
      'category',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'referenceId',
      'referenceType',
      'source',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  CronJob: {
    allFields: [
      'config',
      'createdAt',
      'expression',
      'id',
      'isDeleted',
      'label',
      'lastRunAt',
      'mongoId',
      'nextRunAt',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['runs'],
    enumFields: {
      status: { enumType: 'CronJobStatus', isRequired: true },
    },
  },
  CronRun: {
    allFields: [
      'completedAt',
      'createdAt',
      'cronJob',
      'cronJobId',
      'error',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'result',
      'startedAt',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'CronRunStatus', isRequired: true },
    },
  },
  Customer: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'stripeCustomerId',
      'updatedAt',
    ],
    listFields: ['subscriptions'],
    enumFields: {},
  },
  CustomerInstance: {
    allFields: [
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organizationId',
      'status',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  DashboardLayout: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'document',
      'id',
      'isDeleted',
      'organization',
      'organizationId',
      'pageKey',
      'updatedAt',
      'version',
    ],
    listFields: [],
    enumFields: {},
  },
  DesktopAuthCode: {
    allFields: [
      'codeChallenge',
      'codeHash',
      'createdAt',
      'expiresAt',
      'id',
      'organizationId',
      'stateHash',
      'updatedAt',
      'usedAt',
      'userEmail',
      'userId',
      'userName',
    ],
    listFields: ['scopes'],
    enumFields: {},
  },
  DesktopMessage: {
    allFields: [
      'content',
      'createdAt',
      'draftId',
      'generatedContent',
      'id',
      'role',
      'thread',
      'threadId',
    ],
    listFields: [],
    enumFields: {},
  },
  DesktopThread: {
    allFields: [
      'createdAt',
      'id',
      'localUserId',
      'organizationId',
      'status',
      'title',
      'updatedAt',
      'userId',
      'workspaceId',
    ],
    listFields: ['messages'],
    enumFields: {},
  },
  Distribution: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  EditorProject: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'renderedVideo',
      'renderedVideoId',
      'tracks',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementBlacklist: {
    allFields: [
      'category',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementCamera: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementCameraMovement: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementLens: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementLighting: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementMood: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementScene: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'isFavorite',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementSound: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'isFavorite',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ElementStyle: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Evaluation: {
    allFields: [
      'contentId',
      'contentType',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  ExternalVoice: {
    allFields: [
      'createdAt',
      'externalId',
      'externalProvider',
      'id',
      'isActive',
      'isDefaultSelectable',
      'isFeatured',
      'language',
      'name',
      'providerData',
      'sampleAudioUrl',
      'updatedAt',
    ],
    listFields: ['ingredients'],
    enumFields: {
      externalProvider: { enumType: 'VoiceProvider', isRequired: true },
    },
  },
  FanvueContent: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organizationId',
      'publishedAt',
      'status',
      'updatedAt',
      'userId',
    ],
    listFields: ['schedules'],
    enumFields: {},
  },
  FanvueEarnings: {
    allFields: [
      'createdAt',
      'data',
      'earnedAt',
      'id',
      'isDeleted',
      'mongoId',
      'organizationId',
      'type',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  FanvueSchedule: {
    allFields: [
      'content',
      'contentId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organizationId',
      'scheduledAt',
      'status',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  FanvueSubscriber: {
    allFields: [
      'createdAt',
      'data',
      'externalId',
      'id',
      'isDeleted',
      'mongoId',
      'organizationId',
      'status',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Folder: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'description',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['bookmarks', 'ingredients', 'tags'],
    enumFields: {},
  },
  FontFamilyRecord: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Forecast: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Goal: {
    allFields: [
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'label',
      'level',
      'mongoId',
      'organization',
      'organizationId',
      'parent',
      'parentId',
      'status',
      'updatedAt',
    ],
    listFields: ['children'],
    enumFields: {},
  },
  Ingredient: {
    allFields: [
      'agentRun',
      'agentRunId',
      'agentStrategy',
      'agentStrategyId',
      'assetLabel',
      'bookmark',
      'bookmarkId',
      'brand',
      'brandId',
      'campaign',
      'campaignWeek',
      'category',
      'cdnUrl',
      'cfgScale',
      'cloneStatus',
      'contentRating',
      'createdAt',
      'externalVoiceCatalog',
      'externalVoiceCatalogId',
      'externalVoiceId',
      'fileSize',
      'folder',
      'folderId',
      'generationCompletedAt',
      'generationError',
      'generationProgress',
      'generationPrompt',
      'generationSeed',
      'generationSource',
      'generationStage',
      'generationStartedAt',
      'generationSteps',
      'groupId',
      'groupIndex',
      'id',
      'isCloned',
      'isDefault',
      'isDefaultSelectable',
      'isDeleted',
      'isFavorite',
      'isFeatured',
      'isHighlighted',
      'isMergeEnabled',
      'isPublic',
      'isVoiceActive',
      'language',
      'loraUsed',
      'metadata',
      'metadataId',
      'mimeType',
      'modelUsed',
      'mongoId',
      'negativePrompt',
      'order',
      'organization',
      'organizationId',
      'parent',
      'parentId',
      'persona',
      'personaId',
      'personaSlug',
      'prompt',
      'promptId',
      'promptTemplate',
      'providerData',
      'qualityScore',
      'qualityStatus',
      'reviewStatus',
      's3Key',
      'sampleAudioUrl',
      'scope',
      'status',
      'templateVersion',
      'training',
      'trainingId',
      'updatedAt',
      'user',
      'userId',
      'version',
      'voiceProvider',
      'voiceSource',
      'workflowUsed',
    ],
    listFields: [
      'bookmarkExtracted',
      'bookmarkGenerated',
      'brandMusics',
      'brandVoices',
      'captions',
      'children',
      'editorProjectVideos',
      'personaAvatars',
      'personaVoices',
      'postAnalyticsIngredients',
      'postEntities',
      'postIngredients',
      'postedTo',
      'qualityFeedback',
      'sourceOf',
      'sources',
      'tags',
      'taskApprovedOutputs',
      'taskLinkedOutputs',
      'trackedLinkContent',
      'trainingSources',
      'transformations',
    ],
    enumFields: {
      assetLabel: { enumType: 'FleetAssetLabel', isRequired: false },
      category: { enumType: 'IngredientCategory', isRequired: true },
      cloneStatus: { enumType: 'VoiceCloneStatus', isRequired: false },
      contentRating: { enumType: 'ContentRating', isRequired: false },
      qualityStatus: { enumType: 'QualityStatus', isRequired: true },
      reviewStatus: { enumType: 'FleetReviewStatus', isRequired: false },
      scope: { enumType: 'AssetScope', isRequired: true },
      status: { enumType: 'IngredientStatus', isRequired: true },
      voiceProvider: { enumType: 'VoiceProvider', isRequired: false },
    },
  },
  Insight: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Invitation: {
    allFields: [
      'acceptedAt',
      'acceptedByUser',
      'acceptedByUserId',
      'createdAt',
      'email',
      'expiresAt',
      'firstName',
      'id',
      'invitedByUser',
      'invitedByUserId',
      'isDeleted',
      'lastName',
      'mongoId',
      'organization',
      'organizationId',
      'redirectUrl',
      'revokedAt',
      'role',
      'roleId',
      'roleKey',
      'status',
      'tokenHash',
      'updatedAt',
    ],
    listFields: ['warmupAccounts'],
    enumFields: {},
  },
  Jwks: {
    allFields: ['createdAt', 'expiresAt', 'id', 'privateKey', 'publicKey'],
    listFields: [],
    enumFields: {},
  },
  Lead: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'proactiveBrand',
      'proactiveBrandId',
      'proactiveOrganization',
      'proactiveOrganizationId',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'LeadStatus', isRequired: true },
    },
  },
  LifecycleEmailDelivery: {
    allFields: [
      'canceledAt',
      'createdAt',
      'email',
      'failureReason',
      'id',
      'metadata',
      'scheduledFor',
      'sentAt',
      'sequence',
      'skippedAt',
      'status',
      'step',
      'triggerKey',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  LifecycleEmailPreference: {
    allFields: [
      'createdAt',
      'id',
      'marketingUnsubscribedAt',
      'unsubscribeToken',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Link: {
    allFields: [
      'brand',
      'brandId',
      'category',
      'createdAt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'updatedAt',
      'url',
    ],
    listFields: [],
    enumFields: {
      category: { enumType: 'LinkCategory', isRequired: true },
    },
  },
  LinkClick: {
    allFields: [
      'country',
      'createdAt',
      'device',
      'gaClientId',
      'id',
      'isUnique',
      'link',
      'linkId',
      'mongoId',
      'referrer',
      'sessionId',
      'timestamp',
      'updatedAt',
      'userAgent',
    ],
    listFields: [],
    enumFields: {},
  },
  ListeningEvidence: {
    allFields: [
      'authorExternalId',
      'authorHandle',
      'brand',
      'brandId',
      'collectedAt',
      'contentExcerpt',
      'contractVersion',
      'createdAt',
      'eventType',
      'externalId',
      'freshnessExpiresAt',
      'id',
      'isDeleted',
      'metadata',
      'metrics',
      'occurredAt',
      'organization',
      'organizationId',
      'platform',
      'sourcePost',
      'sourcePostId',
      'sourceUrl',
      'topic',
      'topicId',
      'topicSource',
      'topicSourceId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ListeningTopic: {
    allFields: [
      'auditedAt',
      'brand',
      'brandId',
      'contractVersion',
      'createdAt',
      'description',
      'fingerprint',
      'freshnessHours',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'lastCollectedAt',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'evidence',
      'excludedKeywords',
      'keywords',
      'languages',
      'sources',
    ],
    enumFields: {},
  },
  ListeningTopicSource: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'id',
      'isDeleted',
      'organization',
      'organizationId',
      'platform',
      'source',
      'sourceId',
      'topic',
      'topicId',
      'updatedAt',
    ],
    listFields: ['evidence'],
    enumFields: {},
  },
  LivestreamBotSession: {
    allFields: ['createdAt', 'data', 'id', 'isDeleted', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  McpApproval: {
    allFields: [
      'arguments',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'resolvedAt',
      'result',
      'status',
      'toolName',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'McpApprovalStatus', isRequired: true },
    },
  },
  McpOAuthAuthCode: {
    allFields: [
      'client',
      'clientId',
      'codeChallenge',
      'codeChallengeMethod',
      'codeHash',
      'createdAt',
      'expiresAt',
      'id',
      'organizationId',
      'redirectUri',
      'resource',
      'stateHash',
      'updatedAt',
      'usedAt',
      'userEmail',
      'userId',
      'userName',
    ],
    listFields: ['scopes'],
    enumFields: {},
  },
  Member: {
    allFields: [
      'authProviderMembershipId',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'lastUsedBrand',
      'lastUsedBrandId',
      'mongoId',
      'organization',
      'organizationId',
      'role',
      'roleId',
      'roleKey',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['brands'],
    enumFields: {},
  },
  Metadata: {
    allFields: [
      'assistant',
      'createdAt',
      'description',
      'duration',
      'error',
      'extension',
      'externalId',
      'externalProvider',
      'fps',
      'hasAudio',
      'height',
      'id',
      'isDeleted',
      'label',
      'model',
      'mongoId',
      'prompt',
      'promptId',
      'promptTemplate',
      'resolution',
      'result',
      'seed',
      'size',
      'style',
      'templateVersion',
      'updatedAt',
      'width',
    ],
    listFields: ['ingredients', 'tags'],
    enumFields: {
      extension: { enumType: 'MetadataExtension', isRequired: true },
    },
  },
  Model: {
    allFields: [
      'category',
      'config',
      'cost',
      'costPerUnit',
      'costTier',
      'createdAt',
      'defaultAspectRatio',
      'defaultDuration',
      'deprecatedAt',
      'description',
      'discoveredAt',
      'externalId',
      'hasAudioToggle',
      'hasDurationEditing',
      'hasEndFrame',
      'hasInterpolation',
      'hasResolutionOptions',
      'hasSpeech',
      'id',
      'inputCostPerMillionTokens',
      'isActive',
      'isBatchSupported',
      'isDefault',
      'isDeleted',
      'isDeprecated',
      'isDiscovered',
      'isHighlighted',
      'isImagenModel',
      'isLegacy',
      'isPublic',
      'isReferencesMandatory',
      'key',
      'label',
      'lastSyncedAt',
      'margin',
      'maxDimensions',
      'maxOutputs',
      'maxReferences',
      'minCost',
      'minDimensions',
      'mongoId',
      'organization',
      'organizationId',
      'outputCostPerMillionTokens',
      'parentModel',
      'parentModelId',
      'predecessorOf',
      'pricingType',
      'provider',
      'providerCostUsd',
      'qualityTier',
      'rejectionReason',
      'reviewStatus',
      'reviewedAt',
      'reviewedBy',
      'speedTier',
      'succeededBy',
      'training',
      'trainingId',
      'trigger',
      'triggerWord',
      'updatedAt',
      'usesOrientation',
    ],
    listFields: [
      'aspectRatios',
      'capabilities',
      'childModels',
      'durations',
      'recommendedFor',
      'supportsFeatures',
    ],
    enumFields: {},
  },
  MonitoredAccount: {
    allFields: [
      'botConfig',
      'botConfigId',
      'brand',
      'brandId',
      'config',
      'createdAt',
      'credential',
      'credentialId',
      'id',
      'isActive',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['botActivities', 'processedTweets'],
    enumFields: {},
  },
  MoodBoard: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'id',
      'isDeleted',
      'layout',
      'metadata',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Newsletter: {
    allFields: [
      'agentRun',
      'agentRunId',
      'angle',
      'approvedAt',
      'approvedByUser',
      'approvedByUserId',
      'approvedVersionPin',
      'approvedVersionPinId',
      'brand',
      'brandId',
      'content',
      'createdAt',
      'generationPrompt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'publishedAt',
      'publishedByUser',
      'publishedByUserId',
      'scheduledFor',
      'sourceRefs',
      'status',
      'summary',
      'topic',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'articles',
      'contextNewsletterIds',
      'contextNewsletters',
      'contextOf',
    ],
    enumFields: {},
  },
  OAuthClient: {
    allFields: [
      'clientId',
      'clientName',
      'createdAt',
      'id',
      'tokenEndpointAuthMethod',
      'updatedAt',
    ],
    listFields: ['authCodes', 'grantTypes', 'redirectUris', 'responseTypes'],
    enumFields: {},
  },
  Optimization: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'score',
      'scoreId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  OrgIntegration: {
    allFields: [
      'config',
      'createdAt',
      'encryptedToken',
      'id',
      'isDeleted',
      'lastError',
      'lastErrorMessage',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'status',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {
      platform: { enumType: 'IntegrationPlatform', isRequired: true },
      status: { enumType: 'IntegrationStatus', isRequired: true },
    },
  },
  Organization: {
    allFields: [
      'accountType',
      'authProviderLogoUrl',
      'authProviderOrganizationId',
      'category',
      'createdAt',
      'id',
      'isDefault',
      'isDeleted',
      'isProactiveOnboarding',
      'isSelected',
      'label',
      'mongoId',
      'onboardingCompleted',
      'prefix',
      'proactiveWelcomeDismissed',
      'settings',
      'slug',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'activities',
      'adBulkUploadJobs',
      'adCreativeMappings',
      'adOptimizationAuditLogs',
      'adOptimizationConfigs',
      'adOptimizationRecommendations',
      'adPerformances',
      'agentCampaigns',
      'agentGoals',
      'agentMemories',
      'agentMessages',
      'agentRuns',
      'agentStrategies',
      'agentStrategyOpportunities',
      'agentStrategyReports',
      'agentThreadEvents',
      'agentThreadSnapshots',
      'agentThreads',
      'agentWorkflows',
      'announcements',
      'apiKeys',
      'articleAnalytics',
      'articles',
      'batchWorkflowJobs',
      'batches',
      'bookmarks',
      'botActivities',
      'bots',
      'brandInterviews',
      'brandMemories',
      'brands',
      'campaignTargets',
      'captions',
      'clipProjects',
      'clipResults',
      'contentDrafts',
      'contentPatterns',
      'contentPerformances',
      'contentPlanItems',
      'contentPlans',
      'contentRuns',
      'contentSchedules',
      'contentScores',
      'contentVersionPins',
      'contextBases',
      'contextEntries',
      'creativePatterns',
      'creatorAnalyses',
      'credentials',
      'creditBalances',
      'creditTransactions',
      'cronJobs',
      'cronRuns',
      'customers',
      'dashboardLayouts',
      'distributions',
      'editorProjects',
      'evaluations',
      'folders',
      'forecasts',
      'goals',
      'ingredients',
      'insights',
      'invitations',
      'leads',
      'listeningEvidence',
      'listeningTopicSources',
      'listeningTopics',
      'mcpApprovals',
      'members',
      'models',
      'monitoredAccounts',
      'moodBoards',
      'newsletters',
      'optimizations',
      'orgIntegrations',
      'outreachCampaigns',
      'patternPlaybooks',
      'personas',
      'postAnalytics',
      'postGroups',
      'posts',
      'presets',
      'proactiveLeads',
      'processedTweets',
      'profiles',
      'projects',
      'prompts',
      'publishApprovals',
      'replyBotConfigs',
      'repurposingJobs',
      'schedules',
      'skills',
      'socialConversations',
      'socialMessages',
      'socialSources',
      'sourcePosts',
      'streaks',
      'subscriptionAttributions',
      'subscriptions',
      'tags',
      'taskComments',
      'taskCounters',
      'tasks',
      'templateUsages',
      'templates',
      'threadContextStates',
      'trackedLinks',
      'trainings',
      'transcripts',
      'trendPreferences',
      'trendRemixLineages',
      'trends',
      'votes',
      'warmupAccounts',
      'watchlists',
      'workflowExecutions',
      'workflows',
    ],
    enumFields: {
      accountType: { enumType: 'OrganizationCategory', isRequired: false },
      category: { enumType: 'OrganizationCategory', isRequired: true },
    },
  },
  OrganizationSetting: {
    allFields: [
      'agentPolicy',
      'agentReplyStyle',
      'brandsLimit',
      'byokBillingRollover',
      'byokBillingStatus',
      'byokFreeThresholdOverride',
      'byokKeys',
      'byokOpenrouterApiKey',
      'createdAt',
      'defaultAvatarIngredientId',
      'defaultAvatarPhotoUrl',
      'defaultImageModel',
      'defaultImageToVideoModel',
      'defaultModel',
      'defaultModelReview',
      'defaultModelUpdate',
      'defaultMusicModel',
      'defaultVideoModel',
      'defaultVoiceId',
      'defaultVoiceProvider',
      'defaultVoiceRef',
      'hasEverHadCredits',
      'hasGeneratedFirstAsset',
      'id',
      'isAdvancedMode',
      'isAutoEvaluateEnabled',
      'isByokEnabled',
      'isFastlaneEnabled',
      'isFirstLogin',
      'isFleetNsfwVisible',
      'isGenerateArticlesEnabled',
      'isGenerateImagesEnabled',
      'isGenerateMusicEnabled',
      'isGenerateVideosEnabled',
      'isNotificationsDiscordEnabled',
      'isNotificationsEmailEnabled',
      'isVerifyIngredientEnabled',
      'isVerifyScriptEnabled',
      'isVerifyVideoEnabled',
      'isVoiceControlEnabled',
      'isWatermarkEnabled',
      'isWebhookEnabled',
      'isWhitelabelEnabled',
      'mongoId',
      'onboardingJourneyCompletedAt',
      'onboardingJourneyMissions',
      'organization',
      'organizationId',
      'quotaInstagram',
      'quotaTiktok',
      'quotaTwitter',
      'quotaYoutube',
      'seatsLimit',
      'subscriptionTier',
      'timezone',
      'updatedAt',
      'webhookDeliveryStatus',
      'webhookEndpoint',
      'webhookSecret',
    ],
    listFields: ['enabledModelIds', 'webhookEventTypes'],
    enumFields: {
      agentReplyStyle: { enumType: 'AgentReplyStyle', isRequired: true },
      byokBillingStatus: { enumType: 'ByokBillingStatus', isRequired: true },
    },
  },
  OutreachCampaign: {
    allFields: [
      'brandId',
      'campaignType',
      'config',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['targets'],
    enumFields: {},
  },
  PatternPlaybook: {
    allFields: [
      'createdAt',
      'createdById',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: ['sourceCreators'],
    enumFields: {},
  },
  Persona: {
    allFields: [
      'avatarExternalId',
      'avatarIngredient',
      'avatarIngredientId',
      'avatarProvider',
      'brand',
      'brandId',
      'config',
      'createdAt',
      'description',
      'handle',
      'id',
      'isAutopilotEnabled',
      'isDeleted',
      'label',
      'mongoId',
      'nextAutopilotRunAt',
      'organization',
      'organizationId',
      'profileImageUrl',
      'slug',
      'status',
      'updatedAt',
      'user',
      'userId',
      'voiceExternalId',
      'voiceIngredient',
      'voiceIngredientId',
      'voiceProvider',
    ],
    listFields: [
      'assignedMembers',
      'credentials',
      'ingredients',
      'posts',
      'tags',
      'trainings',
    ],
    enumFields: {
      status: { enumType: 'PersonaStatus', isRequired: true },
    },
  },
  PlatformSetting: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'key',
      'marginMultiplier',
      'mongoId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Post: {
    allFields: [
      'agentContextSource',
      'agentContextVersion',
      'agentRun',
      'agentRunId',
      'agentStrategy',
      'agentStrategyId',
      'agentThread',
      'agentThreadId',
      'analyticsCollectedAt',
      'analyticsCollectionAttemptKey',
      'analyticsCollectionError',
      'analyticsCollectionRequestedAt',
      'analyticsCollectionState',
      'brand',
      'brandId',
      'category',
      'contentRun',
      'contentRunId',
      'createdAt',
      'creativeVersion',
      'credential',
      'credentialId',
      'description',
      'entityArticle',
      'entityArticleId',
      'entityIngredient',
      'entityIngredientId',
      'entityModel',
      'externalId',
      'externalShortcode',
      'generationId',
      'groupId',
      'hookVersion',
      'id',
      'isAnalyticsEnabled',
      'isDeleted',
      'isRepeat',
      'isShareToFeedSelected',
      'label',
      'lastAttemptAt',
      'maxRepeats',
      'mongoId',
      'nextScheduledDate',
      'order',
      'organization',
      'organizationId',
      'originalPost',
      'originalPostId',
      'parent',
      'parentId',
      'persona',
      'personaId',
      'platform',
      'promptUsed',
      'publicationDate',
      'publishApproval',
      'publishApprovalId',
      'publishIntent',
      'publishedAt',
      'quoteTweetId',
      'repeatCount',
      'repeatEndDate',
      'repeatFrequency',
      'repeatInterval',
      'retryCount',
      'reviewBatchId',
      'reviewDecision',
      'reviewEvents',
      'reviewFeedback',
      'reviewItemId',
      'reviewVersionPin',
      'reviewVersionPinId',
      'reviewedAt',
      'scheduleSlot',
      'scheduledDate',
      'seoBreakdown',
      'seoScore',
      'source',
      'sourceActionId',
      'sourceWorkflowId',
      'sourceWorkflowName',
      'status',
      'targetAttachments',
      'targetError',
      'targetExecutionState',
      'targetIdempotencyKey',
      'targetReadiness',
      'targetSettings',
      'targetValidationState',
      'timezone',
      'updatedAt',
      'uploadedAt',
      'url',
      'user',
      'userId',
      'variantId',
      'workflowExecution',
      'workflowExecutionId',
    ],
    listFields: [
      'children',
      'contentPerformances',
      'ingredients',
      'postAnalytics',
      'publishApprovals',
      'repeatDaysOfWeek',
      'socialConversations',
      'socialMessages',
      'subscriptionAttributions',
      'tags',
      'targetValidationIssues',
      'trendRemixLineages',
      'variants',
    ],
    enumFields: {
      category: { enumType: 'PostCategory', isRequired: true },
      entityModel: { enumType: 'PostEntityModel', isRequired: false },
      reviewDecision: { enumType: 'ReviewDecision', isRequired: false },
    },
  },
  PostAnalytics: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'date',
      'engagementRate',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'post',
      'postId',
      'totalComments',
      'totalCommentsIncrement',
      'totalLikes',
      'totalLikesIncrement',
      'totalSaves',
      'totalSavesIncrement',
      'totalShares',
      'totalSharesIncrement',
      'totalViews',
      'totalViewsIncrement',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['ingredients'],
    enumFields: {
      platform: { enumType: 'CredentialPlatform', isRequired: true },
    },
  },
  PostGroup: {
    allFields: [
      'attachments',
      'baseContent',
      'brand',
      'brandId',
      'createdAt',
      'id',
      'idempotencyKey',
      'isDeleted',
      'media',
      'organization',
      'organizationId',
      'owner',
      'ownerId',
      'publishedAt',
      'recurrence',
      'scheduledAt',
      'status',
      'statusTransitions',
      'timezone',
      'title',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Preset: {
    allFields: [
      'brand',
      'brandId',
      'category',
      'config',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'isFavorite',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ProcessedTweet: {
    allFields: [
      'botActivityId',
      'createdAt',
      'id',
      'mongoId',
      'monitoredAccount',
      'monitoredAccountId',
      'organization',
      'organizationId',
      'processedAt',
      'processedBy',
      'replyBotConfig',
      'replyBotConfigId',
      'tweetId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Profile: {
    allFields: [
      'createdAt',
      'createdBy',
      'createdById',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Project: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Prompt: {
    allFields: [
      'article',
      'articleId',
      'brand',
      'brandId',
      'camera',
      'category',
      'createdAt',
      'duration',
      'enhanced',
      'fontFamily',
      'id',
      'ingredientId',
      'isDeleted',
      'isFavorite',
      'isSkipEnhancement',
      'model',
      'mongoId',
      'mood',
      'organization',
      'organizationId',
      'original',
      'ratio',
      'reference',
      'resolution',
      'scene',
      'scope',
      'seed',
      'speech',
      'status',
      'style',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['blacklists', 'ingredients', 'metadata', 'sounds', 'tags'],
    enumFields: {
      category: { enumType: 'PromptCategory', isRequired: false },
      scope: { enumType: 'AssetScope', isRequired: true },
      status: { enumType: 'PromptStatus', isRequired: true },
    },
  },
  PublishApproval: {
    allFields: [
      'activePost',
      'actorUser',
      'actorUserId',
      'artifactVersionPin',
      'artifactVersionPinId',
      'brand',
      'brandId',
      'contextVersion',
      'createdAt',
      'destinations',
      'executedAt',
      'id',
      'invalidatedAt',
      'invalidationReason',
      'lastError',
      'operationId',
      'organization',
      'organizationId',
      'policy',
      'post',
      'postId',
      'provenance',
      'scheduleIntent',
      'scopeDigest',
      'status',
      'statusTransitions',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  ReplyBotConfig: {
    allFields: [
      'actionType',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'type',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['botActivities', 'monitoredAccounts', 'processedTweets'],
    enumFields: {},
  },
  RepurposingJob: {
    allFields: [
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'results',
      'settings',
      'sourceContentId',
      'sourceContentType',
      'status',
      'targetFormats',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Role: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'primaryColor',
      'updatedAt',
    ],
    listFields: ['invitations', 'members'],
    enumFields: {},
  },
  Run: {
    allFields: [
      'actionType',
      'authType',
      'brandId',
      'completedAt',
      'correlationId',
      'createdAt',
      'data',
      'durationMs',
      'error',
      'events',
      'id',
      'idempotencyKey',
      'input',
      'isDeleted',
      'metadata',
      'mongoId',
      'organizationId',
      'output',
      'progress',
      'startedAt',
      'status',
      'surface',
      'traceId',
      'trigger',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Schedule: {
    allFields: [
      'brand',
      'brandId',
      'contentId',
      'contentType',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'scheduledAt',
      'schedulingMethod',
      'slots',
      'timezone',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Session: {
    allFields: [
      'activeOrganizationId',
      'createdAt',
      'expiresAt',
      'id',
      'ipAddress',
      'token',
      'updatedAt',
      'user',
      'userAgent',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Setting: {
    allFields: [
      'createdAt',
      'dashboardPreferences',
      'defaultAgentModel',
      'generationPriority',
      'id',
      'isAdvancedMode',
      'isAgentAssetsPanelOpen',
      'isDeleted',
      'isFirstLogin',
      'isMenuCollapsed',
      'isSidebarProgressCollapsed',
      'isSidebarProgressVisible',
      'isTrendNotificationsEmail',
      'isTrendNotificationsInApp',
      'isTrendNotificationsTelegram',
      'isVerified',
      'isVideoNotificationsEmail',
      'isWorkflowNotificationsEmail',
      'mongoId',
      'theme',
      'trendNotificationsEmailAddress',
      'trendNotificationsFrequency',
      'trendNotificationsMinViralScore',
      'trendNotificationsTelegramChatId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['contentPreferences', 'favoriteModelKeys'],
    enumFields: {
      generationPriority: { enumType: 'GenerationPriority', isRequired: true },
      trendNotificationsFrequency: {
        enumType: 'TrendNotificationFrequency',
        isRequired: true,
      },
    },
  },
  Skill: {
    allFields: [
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  SkillReceipt: {
    allFields: ['createdAt', 'data', 'id', 'isDeleted', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  SocialConversation: {
    allFields: [
      'accountExternalId',
      'accountHandle',
      'accountName',
      'assignedOwnerId',
      'automationState',
      'availability',
      'brand',
      'brandId',
      'conversationType',
      'createdAt',
      'credential',
      'credentialId',
      'externalConversationId',
      'externalParentId',
      'externalThreadId',
      'id',
      'isDeleted',
      'lastInboundAt',
      'lastOutboundAt',
      'latestMessageAt',
      'latestMessageText',
      'metadata',
      'mongoId',
      'needsReview',
      'organization',
      'organizationId',
      'participantAvatarUrl',
      'participantExternalId',
      'participantHandle',
      'participantName',
      'platform',
      'post',
      'postId',
      'priority',
      'sourceContentId',
      'sourceContentTitle',
      'sourceContentType',
      'sourceContentUrl',
      'status',
      'unreadCount',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['messages', 'tags'],
    enumFields: {},
  },
  SocialMessage: {
    allFields: [
      'actionProvenance',
      'agentRunId',
      'authorRole',
      'body',
      'brand',
      'brandId',
      'conversation',
      'conversationId',
      'createdAt',
      'credential',
      'credentialId',
      'direction',
      'externalMessageId',
      'externalParentMessageId',
      'failureReason',
      'id',
      'idempotencyKey',
      'isDeleted',
      'messageType',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'post',
      'postId',
      'senderAvatarUrl',
      'senderExternalId',
      'senderHandle',
      'senderName',
      'sourceUrl',
      'status',
      'updatedAt',
      'user',
      'userId',
      'workflowRunId',
      'workflowTriggerAttemptedAt',
      'workflowTriggerError',
      'workflowTriggerJobId',
      'workflowTriggerQueuedAt',
      'workflowTriggerStatus',
    ],
    listFields: [],
    enumFields: {},
  },
  SocialReplyCampaign: {
    allFields: [
      'bodyTemplate',
      'brandId',
      'completedAt',
      'createdAt',
      'description',
      'dispatchCursor',
      'failedCount',
      'id',
      'isDeleted',
      'lastDispatchedAt',
      'lastError',
      'maxPerDay',
      'maxPerHour',
      'messageType',
      'metadata',
      'minDelaySeconds',
      'name',
      'nextRunAt',
      'organizationId',
      'pausedAt',
      'platform',
      'sentCount',
      'skippedCount',
      'startedAt',
      'status',
      'totalRecipients',
      'updatedAt',
      'userId',
      'workflowExecutionId',
      'workflowId',
    ],
    listFields: ['recipients'],
    enumFields: {},
  },
  SocialReplyCampaignRecipient: {
    allFields: [
      'attemptCount',
      'body',
      'campaign',
      'campaignId',
      'conversationId',
      'createdAt',
      'dispatchedAt',
      'failureReason',
      'id',
      'idempotencyKey',
      'isDeleted',
      'messageId',
      'metadata',
      'organizationId',
      'position',
      'scheduledAt',
      'sentAt',
      'status',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  SocialSource: {
    allFields: [
      'avatarUrl',
      'bio',
      'brand',
      'brandId',
      'createdAt',
      'credential',
      'credentialId',
      'displayName',
      'externalId',
      'followersCount',
      'handle',
      'id',
      'isActive',
      'isDeleted',
      'lastPostExternalId',
      'lastSyncError',
      'lastSyncStatus',
      'lastSyncedAt',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'profileUrl',
      'sourceType',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['listeningTopicSources', 'posts'],
    enumFields: {},
  },
  SourcePost: {
    allFields: [
      'authorAvatarUrl',
      'authorDisplayName',
      'authorFollowersCount',
      'authorHandle',
      'authorId',
      'brand',
      'brandId',
      'collectedAt',
      'contentType',
      'createdAt',
      'externalId',
      'id',
      'isDeleted',
      'metrics',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'publishedAt',
      'raw',
      'source',
      'sourceId',
      'sourceUrl',
      'text',
      'thumbnailUrl',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['hashtags', 'listeningEvidence', 'mediaUrls'],
    enumFields: {},
  },
  Streak: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Subscription: {
    allFields: [
      'cancelAtPeriodEnd',
      'createdAt',
      'currentPeriodEnd',
      'currentPeriodStart',
      'customer',
      'customerId',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'plan',
      'status',
      'stripePriceId',
      'stripeSubscriptionId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'SubscriptionStatus', isRequired: true },
    },
  },
  SubscriptionAttribution: {
    allFields: [
      'channel',
      'createdAt',
      'id',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'referrer',
      'sourceContent',
      'sourceContentId',
      'sourceLink',
      'sourceLinkId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Tag: {
    allFields: [
      'backgroundColor',
      'brand',
      'brandId',
      'category',
      'createdAt',
      'description',
      'id',
      'isActive',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'textColor',
      'updatedAt',
      'userId',
    ],
    listFields: [
      'articles',
      'bookmarks',
      'credentials',
      'folders',
      'ingredients',
      'metadata',
      'personas',
      'posts',
      'prompts',
      'workflows',
    ],
    enumFields: {
      category: { enumType: 'TagCategory', isRequired: false },
    },
  },
  Task: {
    allFields: [
      'assigneeAgentId',
      'assigneeUserId',
      'brandId',
      'checkedOutAt',
      'checkoutAgentId',
      'checkoutRunId',
      'completedAt',
      'config',
      'createdAt',
      'decomposition',
      'description',
      'dismissedAt',
      'eventStream',
      'failureReason',
      'goalId',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'parent',
      'parentId',
      'planningThread',
      'planningThreadId',
      'priority',
      'progress',
      'projectId',
      'requestedChangesReason',
      'reviewState',
      'status',
      'title',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [
      'approvedOutputIds',
      'approvedOutputs',
      'children',
      'comments',
      'linkedOutputs',
      'linkedRuns',
    ],
    enumFields: {
      priority: { enumType: 'TaskPriority', isRequired: true },
    },
  },
  TaskComment: {
    allFields: [
      'authorId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'task',
      'taskId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  TaskCounter: {
    allFields: [
      'counter',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  Template: {
    allFields: [
      'category',
      'config',
      'createdAt',
      'createdById',
      'id',
      'isActive',
      'isDeleted',
      'isFeatured',
      'key',
      'label',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'purpose',
      'scope',
      'updatedAt',
      'usageCount',
      'variables',
      'version',
    ],
    listFields: ['categories', 'industries', 'platforms', 'usages'],
    enumFields: {},
  },
  TemplateMetadata: {
    allFields: [
      'author',
      'averageQuality',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'lastUsed',
      'license',
      'mongoId',
      'successRate',
      'template',
      'templateId',
      'updatedAt',
      'usageCount',
      'version',
    ],
    listFields: ['compatiblePlatforms'],
    enumFields: {},
  },
  TemplateUsage: {
    allFields: [
      'createdAt',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'template',
      'templateId',
      'updatedAt',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  ThreadContextState: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'thread',
      'threadId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  TrackedLink: {
    allFields: [
      'brand',
      'brandId',
      'campaignName',
      'content',
      'contentId',
      'contentType',
      'createdAt',
      'customSlug',
      'expiresAt',
      'id',
      'isActive',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'originalUrl',
      'platform',
      'shortCode',
      'shortUrl',
      'stats',
      'title',
      'updatedAt',
      'utm',
    ],
    listFields: ['linkClicks', 'subscriptionAttributions'],
    enumFields: {},
  },
  Training: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'description',
      'externalId',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'persona',
      'personaId',
      'stage',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['ingredients', 'models', 'sources'],
    enumFields: {
      stage: { enumType: 'TrainingStage', isRequired: true },
    },
  },
  Transcript: {
    allFields: [
      'article',
      'articleId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'language',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Trend: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'data',
      'expiresAt',
      'id',
      'isCurrent',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'requiresAuth',
      'topic',
      'updatedAt',
      'viralityScore',
    ],
    listFields: ['remixLineages', 'sourceReferenceLinks'],
    enumFields: {},
  },
  TrendPreferences: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  TrendRemixLineage: {
    allFields: [
      'brand',
      'brandId',
      'contentDraft',
      'contentDraftId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'post',
      'postId',
      'updatedAt',
    ],
    listFields: ['sourceReferences', 'trends'],
    enumFields: {},
  },
  TrendSourceReference: {
    allFields: [
      'authorHandle',
      'canonicalUrl',
      'createdAt',
      'currentEngagementTotal',
      'data',
      'id',
      'isDeleted',
      'lastSeenAt',
      'latestTrendViralityScore',
      'mongoId',
      'platform',
      'updatedAt',
    ],
    listFields: ['links', 'remixLineages', 'snapshots'],
    enumFields: {},
  },
  TrendSourceReferenceLink: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'sourceReference',
      'sourceReferenceId',
      'trend',
      'trendId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  TrendSourceReferenceSnapshot: {
    allFields: [
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'snapshotDate',
      'sourceReference',
      'sourceReferenceId',
      'updatedAt',
    ],
    listFields: [],
    enumFields: {},
  },
  TrendingHashtag: {
    allFields: ['createdAt', 'data', 'id', 'isDeleted', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  TrendingSound: {
    allFields: ['createdAt', 'data', 'id', 'isDeleted', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  TrendingVideo: {
    allFields: ['createdAt', 'data', 'id', 'isDeleted', 'mongoId', 'updatedAt'],
    listFields: [],
    enumFields: {},
  },
  User: {
    allFields: [
      'appSource',
      'avatar',
      'createdAt',
      'email',
      'emailVerified',
      'firstName',
      'handle',
      'hasDismissedAssetGate',
      'id',
      'isDefault',
      'isDeleted',
      'isInvited',
      'isOnboardingCompleted',
      'lastName',
      'lastUsedOrganizationId',
      'lifecycleEmailPreference',
      'mongoId',
      'name',
      'onboardingCompletedAt',
      'onboardingStartedAt',
      'onboardingType',
      'platformRole',
      'settings',
      'stripeCustomerId',
      'updatedAt',
      'userSubscription',
    ],
    listFields: [
      'accounts',
      'agentCampaigns',
      'agentGoals',
      'agentMemories',
      'agentMessages',
      'agentRuns',
      'agentStrategies',
      'agentThreads',
      'agentWorkflows',
      'apiKeys',
      'articleAnalytics',
      'articles',
      'assets',
      'batches',
      'bookmarks',
      'botActivities',
      'bots',
      'brandInterviews',
      'brands',
      'captions',
      'contentDrafts',
      'contentPlans',
      'contentVersionPins',
      'contextBases',
      'creatorAnalyses',
      'credentials',
      'cronJobs',
      'cronRuns',
      'distributions',
      'editorProjects',
      'evaluations',
      'folders',
      'forecasts',
      'ingredients',
      'invitationsAccepted',
      'invitationsSent',
      'leads',
      'lifecycleEmailDeliveries',
      'listeningTopics',
      'mcpApprovals',
      'members',
      'monitoredAccounts',
      'newsletterApprovals',
      'newsletterPublishes',
      'newsletters',
      'onboardingStepsCompleted',
      'optimizations',
      'organizations',
      'outreachCampaigns',
      'personaAssignments',
      'personas',
      'postAnalytics',
      'postGroups',
      'posts',
      'profiles',
      'prompts',
      'publishApprovals',
      'replyBotConfigs',
      'repurposingJobs',
      'sessions',
      'socialConversations',
      'socialMessages',
      'socialSources',
      'sourcePosts',
      'streaks',
      'subscriptionAttributions',
      'subscriptions',
      'tasks',
      'trainings',
      'transcripts',
      'votes',
      'warmupAccountsCustomer',
      'warmupAccountsOperated',
      'watchlists',
      'workflowExecutions',
      'workflows',
    ],
    enumFields: {
      appSource: { enumType: 'AppSource', isRequired: true },
      onboardingType: { enumType: 'OnboardingType', isRequired: false },
      platformRole: { enumType: 'PlatformRole', isRequired: true },
    },
  },
  UserSubscription: {
    allFields: [
      'cancelAtPeriodEnd',
      'createdAt',
      'currentPeriodEnd',
      'currentPeriodStart',
      'id',
      'isDeleted',
      'mongoId',
      'plan',
      'status',
      'stripePriceId',
      'stripeSubscriptionId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'SubscriptionStatus', isRequired: true },
    },
  },
  Verification: {
    allFields: [
      'createdAt',
      'expiresAt',
      'id',
      'identifier',
      'updatedAt',
      'value',
    ],
    listFields: [],
    enumFields: {},
  },
  Vote: {
    allFields: [
      'createdAt',
      'entityId',
      'entityModel',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  WarmupAccount: {
    allFields: [
      'auditEvents',
      'brand',
      'brandId',
      'brandName',
      'createdAt',
      'customerUser',
      'customerUserId',
      'diagnostics',
      'guidance',
      'id',
      'invitation',
      'invitationId',
      'isDeleted',
      'leadEmail',
      'leadFirstName',
      'leadLastName',
      'operatorUser',
      'operatorUserId',
      'organization',
      'organizationId',
      'organizationName',
      'status',
      'updatedAt',
      'websiteUrl',
    ],
    listFields: [],
    enumFields: {
      status: { enumType: 'WarmupAccountStatus', isRequired: true },
    },
  },
  Watchlist: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdAt',
      'handle',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: [],
    enumFields: {},
  },
  Workflow: {
    allFields: [
      'brand',
      'brandId',
      'completedAt',
      'config',
      'createdAt',
      'defaultRecurringBrandId',
      'description',
      'edges',
      'executionCount',
      'id',
      'inputVariables',
      'isDeleted',
      'isScheduleEnabled',
      'label',
      'lastExecutedAt',
      'lifecycle',
      'lockedNodeIds',
      'metadata',
      'mongoId',
      'nodes',
      'organization',
      'organizationId',
      'progress',
      'recurrence',
      'schedule',
      'startedAt',
      'status',
      'steps',
      'thumbnail',
      'thumbnailNodeId',
      'timezone',
      'updatedAt',
      'user',
      'userId',
    ],
    listFields: ['batchJobs', 'executions', 'tags'],
    enumFields: {},
  },
  WorkflowExecution: {
    allFields: [
      'completedAt',
      'createdAt',
      'error',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'result',
      'startedAt',
      'status',
      'trigger',
      'updatedAt',
      'user',
      'userId',
      'workflow',
      'workflowId',
    ],
    listFields: ['posts'],
    enumFields: {
      status: { enumType: 'WorkflowExecutionStatus', isRequired: true },
    },
  },
};

/**
 * Returns model metadata for a given model name (camelCase or PascalCase).
 * Returns undefined when the model is not in the schema.
 */
export function getModelMeta(modelName: string): ModelFieldMeta | undefined {
  const pascal = modelName.charAt(0).toUpperCase() + modelName.slice(1);
  return PRISMA_MODEL_METADATA[pascal];
}
