/**
 * GENERATED — do not edit by hand.
 * Source: packages/prisma/prisma/schema.prisma
 * Regenerate: `cd packages/prisma && bun run db:generate`
 *
 * Static model/field metadata for BaseService enum normalisation.
 * Replaces runtime `_runtimeDataModel` lookup which is not populated
 * by the PrismaPg driver adapter under Prisma 7.
 */

/** Per-field enum metadata (used by BaseService). */
export interface EnumFieldMeta {
  /** Prisma enum type name, e.g. "IngredientCategory". */
  enumType: string;
  /** True when the column is NOT NULL in the schema. */
  isRequired: boolean;
}

/** Per-model field metadata. */
export interface ModelFieldMeta {
  /**
   * All scalar + enum field names present on the model.
   * Does NOT include list relation fields.
   * Used by modelHasField().
   */
  allFields: ReadonlyArray<string>;
  /**
   * Enum fields: fieldName -> EnumFieldMeta.
   * Only fields whose type is a Prisma enum appear here.
   */
  enumFields: Readonly<Record<string, EnumFieldMeta>>;
}

/**
 * Complete model metadata map.
 * Key = PascalCase model name matching Prisma.ModelName.
 */
export const PRISMA_MODEL_METADATA: Readonly<Record<string, ModelFieldMeta>> = {
  Account: {
    allFields: [
      'accessToken',
      'accessTokenExpiresAt',
      'accountId',
      'createdAt',
      'id',
      'idToken',
      'password',
      'providerId',
      'refreshToken',
      'refreshTokenExpiresAt',
      'scope',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Activity: {
    allFields: [
      'action',
      'brand',
      'brandId',
      'createdAt',
      'data',
      'entityId',
      'entityModel',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'userId',
    ],
    enumFields: {},
  },
  AdBulkUploadJob: {
    allFields: [
      'brand',
      'brandId',
      'credential',
      'credentialId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  AdCreativeMapping: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  AdInsights: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  AdOptimizationAuditLog: {
    allFields: ['data', 'id', 'mongoId', 'organization', 'organizationId'],
    enumFields: {},
  },
  AdOptimizationConfig: {
    allFields: ['config', 'id', 'mongoId', 'organization', 'organizationId'],
    enumFields: {},
  },
  AdOptimizationRecommendation: {
    allFields: ['data', 'id', 'mongoId', 'organization', 'organizationId'],
    enumFields: {},
  },
  AdPerformance: {
    allFields: [
      'brand',
      'brandId',
      'credential',
      'credentialId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  AgentCampaign: {
    allFields: [
      'brand',
      'brandId',
      'campaignLeadStrategy',
      'campaignLeadStrategyId',
      'config',
      'description',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentGoal: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'description',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentMemory: {
    allFields: [
      'brand',
      'brandId',
      'campaign',
      'campaignId',
      'confidence',
      'content',
      'contentType',
      'createdAt',
      'id',
      'importance',
      'kind',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'performanceSnapshot',
      'platform',
      'scope',
      'sourceContentId',
      'sourceMessageId',
      'sourceType',
      'sourceUrl',
      'summary',
      'type',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentMessage: {
    allFields: [
      'brand',
      'brandId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'role',
      'thread',
      'threadId',
      'toolCalls',
      'toolResults',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentRun: {
    allFields: [
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'parentRun',
      'parentRunId',
      'status',
      'strategy',
      'strategyId',
      'thread',
      'threadId',
      'type',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'AgentRunStatus', isRequired: true },
    },
  },
  AgentStrategy: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'description',
      'goal',
      'goalId',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentStrategyOpportunity: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'strategy',
      'strategyId',
    ],
    enumFields: {},
  },
  AgentStrategyReport: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'strategy',
      'strategyId',
    ],
    enumFields: {},
  },
  AgentThread: {
    allFields: [
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'title',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  AgentThreadEvent: {
    allFields: [
      'commandId',
      'createdAt',
      'data',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'runId',
      'sequence',
      'thread',
      'threadId',
      'type',
      'updatedAt',
    ],
    enumFields: {},
  },
  AgentThreadSnapshot: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'thread',
      'threadId',
    ],
    enumFields: {},
  },
  AgentWorkflow: {
    allFields: [
      'config',
      'description',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Analytic: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  Announcement: {
    allFields: [
      'config',
      'content',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'title',
    ],
    enumFields: {},
  },
  ApiKey: {
    allFields: [
      'category',
      'createdAt',
      'description',
      'expiresAt',
      'id',
      'isRevoked',
      'key',
      'keyFingerprint',
      'label',
      'lastUsedAt',
      'lastUsedIp',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'rateLimit',
      'revokedAt',
      'updatedAt',
      'usageCount',
      'user',
      'userId',
    ],
    enumFields: {
      category: { enumType: 'ApiKeyCategory', isRequired: true },
    },
  },
  Article: {
    allFields: [
      'brand',
      'brandId',
      'category',
      'content',
      'coverImageUrl',
      'createdAt',
      'excerpt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'publishedAt',
      'scope',
      'seoBreakdown',
      'seoScore',
      'slug',
      'status',
      'title',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'ArticleStatus', isRequired: true },
    },
  },
  ArticleAnalytics: {
    allFields: [
      'article',
      'articleId',
      'brand',
      'brandId',
      'createdAt',
      'date',
      'engagementRate',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'totalComments',
      'totalLikes',
      'totalShares',
      'totalViews',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Asset: {
    allFields: [
      'category',
      'cloudObjectKey',
      'createdAt',
      'deletedAt',
      'displayName',
      'externalId',
      'id',
      'isDeleted',
      'kind',
      'localAssetId',
      'mimeType',
      'mongoId',
      'origin',
      'originalFileName',
      'parentArticleId',
      'parentBrandId',
      'parentIngredientId',
      'parentOrgId',
      'parentType',
      'residency',
      'sha256',
      'sizeBytes',
      'updatedAt',
      'uploadPolicy',
      'user',
      'userId',
    ],
    enumFields: {
      category: { enumType: 'AssetCategory', isRequired: true },
      parentType: { enumType: 'AssetParent', isRequired: true },
    },
  },
  Batch: {
    allFields: [
      'agentStrategy',
      'agentStrategyId',
      'brand',
      'brandId',
      'config',
      'id',
      'items',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'BatchStatus', isRequired: true },
    },
  },
  BatchWorkflowJob: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'items',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
      'userId',
      'workflow',
      'workflowId',
    ],
    enumFields: {
      status: { enumType: 'BatchStatus', isRequired: true },
    },
  },
  Bookmark: {
    allFields: [
      'author',
      'authorHandle',
      'brand',
      'brandId',
      'category',
      'content',
      'description',
      'folder',
      'folderId',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'platformData',
      'thumbnailUrl',
      'title',
      'url',
      'user',
      'userId',
    ],
    enumFields: {
      category: { enumType: 'BookmarkCategory', isRequired: true },
      platform: { enumType: 'BookmarkPlatform', isRequired: true },
    },
  },
  Bot: {
    allFields: [
      'brandId',
      'config',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  BotActivity: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'monitoredAccount',
      'monitoredAccountId',
      'organization',
      'organizationId',
      'replyBotConfig',
      'replyBotConfigId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Brand: {
    allFields: [
      'agentConfig',
      'backgroundColor',
      'defaultImageModel',
      'defaultImageToVideoModel',
      'defaultMusicModel',
      'defaultVideoModel',
      'description',
      'fontFamily',
      'id',
      'isActive',
      'isDarkroomEnabled',
      'isDefault',
      'isDeleted',
      'isHighlighted',
      'isSelected',
      'label',
      'mongoId',
      'musicIngredient',
      'musicIngredientId',
      'organization',
      'organizationId',
      'primaryColor',
      'referenceImages',
      'scope',
      'secondaryColor',
      'slug',
      'text',
      'user',
      'userId',
      'voiceIngredient',
      'voiceIngredientId',
    ],
    enumFields: {
      fontFamily: { enumType: 'FontFamily', isRequired: true },
      scope: { enumType: 'AssetScope', isRequired: true },
    },
  },
  BrandInterview: {
    allFields: [
      'answeredFields',
      'brand',
      'brandId',
      'id',
      'organization',
      'organizationId',
      'status',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'BrandInterviewStatus', isRequired: true },
    },
  },
  BrandMemory: {
    allFields: [
      'brand',
      'brandId',
      'content',
      'createdAt',
      'date',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'type',
      'updatedAt',
    ],
    enumFields: {},
  },
  CampaignTarget: {
    allFields: [
      'campaign',
      'campaignId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'status',
    ],
    enumFields: {},
  },
  Caption: {
    allFields: [
      'agentRun',
      'agentRunId',
      'content',
      'createdAt',
      'id',
      'ingredient',
      'ingredientId',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  ClipProject: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  ClipResult: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'projectId',
      'providerJobId',
      'viralityScore',
    ],
    enumFields: {},
  },
  ContentDraft: {
    allFields: [
      'approvedBy',
      'approvedById',
      'brand',
      'brandId',
      'contentRun',
      'contentRunId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'status',
    ],
    enumFields: {},
  },
  ContentPattern: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'sourceCreator',
      'sourceCreatorId',
    ],
    enumFields: {},
  },
  ContentPerformance: {
    allFields: [
      'brand',
      'brandId',
      'comments',
      'contentRun',
      'contentRunId',
      'contentType',
      'cycleNumber',
      'data',
      'engagementRate',
      'externalPostId',
      'generationId',
      'id',
      'likes',
      'measuredAt',
      'mongoId',
      'organization',
      'organizationId',
      'performanceScore',
      'platform',
      'post',
      'postId',
      'revenue',
      'saves',
      'shares',
      'source',
      'userId',
      'variantId',
      'views',
      'workflowExecutionId',
    ],
    enumFields: {},
  },
  ContentPlan: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'createdBy',
      'createdById',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  ContentPlanItem: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'plan',
      'planId',
    ],
    enumFields: {},
  },
  ContentRun: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  ContentSchedule: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  ContentScore: {
    allFields: ['data', 'id', 'mongoId', 'organization', 'organizationId'],
    enumFields: {},
  },
  ContextBase: {
    allFields: [
      'createdBy',
      'createdById',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'sourceBrand',
      'sourceBrandId',
    ],
    enumFields: {},
  },
  ContextEntry: {
    allFields: [
      'contextBase',
      'contextBaseId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  CreativePattern: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  CreatorAnalysis: {
    allFields: [
      'createdBy',
      'createdById',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  Credential: {
    allFields: [
      'accessToken',
      'accessTokenExpiry',
      'accessTokenSecret',
      'brand',
      'brandId',
      'createdAt',
      'description',
      'externalAvatar',
      'externalHandle',
      'externalId',
      'externalName',
      'id',
      'isConnected',
      'isDeleted',
      'label',
      'mongoId',
      'oauthState',
      'oauthToken',
      'oauthTokenHash',
      'oauthTokenSecret',
      'organization',
      'organizationId',
      'platform',
      'refreshToken',
      'refreshTokenExpiry',
      'updatedAt',
      'user',
      'userId',
      'username',
    ],
    enumFields: {
      platform: { enumType: 'CredentialPlatform', isRequired: true },
    },
  },
  CreditBalance: {
    allFields: [
      'balance',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  CreditTransaction: {
    allFields: [
      'amount',
      'balanceAfter',
      'category',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'referenceId',
      'referenceType',
      'source',
      'updatedAt',
    ],
    enumFields: {},
  },
  CronJob: {
    allFields: [
      'config',
      'expression',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  CronRun: {
    allFields: [
      'completedAt',
      'createdAt',
      'cronJob',
      'cronJobId',
      'error',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'result',
      'startedAt',
      'status',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'CronRunStatus', isRequired: true },
    },
  },
  Customer: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'stripeCustomerId',
      'updatedAt',
    ],
    enumFields: {},
  },
  CustomerInstance: {
    allFields: ['config', 'id', 'mongoId', 'organizationId'],
    enumFields: {},
  },
  DesktopAuthCode: {
    allFields: [
      'codeChallenge',
      'codeHash',
      'createdAt',
      'expiresAt',
      'id',
      'organizationId',
      'stateHash',
      'updatedAt',
      'usedAt',
      'userEmail',
      'userId',
      'userName',
    ],
    enumFields: {},
  },
  DesktopMessage: {
    allFields: [
      'content',
      'createdAt',
      'draftId',
      'generatedContent',
      'id',
      'role',
      'thread',
      'threadId',
    ],
    enumFields: {},
  },
  DesktopThread: {
    allFields: [
      'createdAt',
      'id',
      'localUserId',
      'organizationId',
      'status',
      'title',
      'updatedAt',
      'userId',
      'workspaceId',
    ],
    enumFields: {},
  },
  Distribution: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  EditorProject: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'renderedVideo',
      'renderedVideoId',
      'tracks',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  ElementBlacklist: {
    allFields: [
      'category',
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementCamera: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementCameraMovement: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementLens: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementLighting: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementMood: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementScene: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'isFavorite',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementSound: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'isFavorite',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  ElementStyle: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  Evaluation: {
    allFields: [
      'contentId',
      'contentType',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  ExternalVoice: {
    allFields: [
      'createdAt',
      'externalId',
      'externalProvider',
      'id',
      'isActive',
      'isDefaultSelectable',
      'isFeatured',
      'language',
      'name',
      'providerData',
      'sampleAudioUrl',
      'updatedAt',
    ],
    enumFields: {
      externalProvider: { enumType: 'VoiceProvider', isRequired: true },
    },
  },
  FanvueContent: {
    allFields: ['data', 'id', 'mongoId', 'organizationId', 'status', 'userId'],
    enumFields: {},
  },
  FanvueEarnings: {
    allFields: ['data', 'id', 'mongoId', 'organizationId', 'type', 'userId'],
    enumFields: {},
  },
  FanvueSchedule: {
    allFields: [
      'content',
      'contentId',
      'data',
      'id',
      'mongoId',
      'organizationId',
      'scheduledAt',
      'status',
      'userId',
    ],
    enumFields: {},
  },
  FanvueSubscriber: {
    allFields: [
      'data',
      'externalId',
      'id',
      'mongoId',
      'organizationId',
      'status',
      'userId',
    ],
    enumFields: {},
  },
  Folder: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'description',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  FontFamilyRecord: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  Forecast: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Goal: {
    allFields: [
      'config',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'parent',
      'parentId',
    ],
    enumFields: {},
  },
  Ingredient: {
    allFields: [
      'agentRun',
      'agentRunId',
      'agentStrategy',
      'agentStrategyId',
      'assetLabel',
      'bookmark',
      'bookmarkId',
      'brand',
      'brandId',
      'campaign',
      'campaignWeek',
      'category',
      'cdnUrl',
      'cfgScale',
      'cloneStatus',
      'contentRating',
      'createdAt',
      'externalVoiceCatalog',
      'externalVoiceCatalogId',
      'externalVoiceId',
      'fileSize',
      'folder',
      'folderId',
      'generationCompletedAt',
      'generationError',
      'generationProgress',
      'generationPrompt',
      'generationSeed',
      'generationSource',
      'generationStage',
      'generationStartedAt',
      'generationSteps',
      'groupId',
      'groupIndex',
      'id',
      'isCloned',
      'isDefault',
      'isDefaultSelectable',
      'isDeleted',
      'isFavorite',
      'isFeatured',
      'isHighlighted',
      'isMergeEnabled',
      'isPublic',
      'isVoiceActive',
      'language',
      'loraUsed',
      'metadata',
      'metadataId',
      'mimeType',
      'modelUsed',
      'mongoId',
      'negativePrompt',
      'order',
      'organization',
      'organizationId',
      'parent',
      'parentId',
      'persona',
      'personaId',
      'personaSlug',
      'prompt',
      'promptId',
      'promptTemplate',
      'providerData',
      'qualityScore',
      'qualityStatus',
      'reviewStatus',
      's3Key',
      'sampleAudioUrl',
      'scope',
      'status',
      'templateVersion',
      'training',
      'trainingId',
      'updatedAt',
      'user',
      'userId',
      'version',
      'voiceProvider',
      'voiceSource',
      'workflowUsed',
    ],
    enumFields: {
      assetLabel: { enumType: 'DarkroomAssetLabel', isRequired: false },
      category: { enumType: 'IngredientCategory', isRequired: true },
      cloneStatus: { enumType: 'VoiceCloneStatus', isRequired: false },
      contentRating: { enumType: 'ContentRating', isRequired: false },
      qualityStatus: { enumType: 'QualityStatus', isRequired: true },
      reviewStatus: { enumType: 'DarkroomReviewStatus', isRequired: false },
      scope: { enumType: 'AssetScope', isRequired: true },
      status: { enumType: 'IngredientStatus', isRequired: true },
      voiceProvider: { enumType: 'VoiceProvider', isRequired: false },
    },
  },
  Insight: {
    allFields: ['data', 'id', 'mongoId', 'organization', 'organizationId'],
    enumFields: {},
  },
  Invitation: {
    allFields: [
      'acceptedAt',
      'acceptedByUser',
      'acceptedByUserId',
      'createdAt',
      'email',
      'expiresAt',
      'firstName',
      'id',
      'invitedByUser',
      'invitedByUserId',
      'isDeleted',
      'lastName',
      'mongoId',
      'organization',
      'organizationId',
      'redirectUrl',
      'revokedAt',
      'role',
      'roleId',
      'roleKey',
      'status',
      'tokenHash',
      'updatedAt',
    ],
    enumFields: {},
  },
  Jwks: {
    allFields: ['createdAt', 'expiresAt', 'id', 'privateKey', 'publicKey'],
    enumFields: {},
  },
  Lead: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'proactiveBrand',
      'proactiveBrandId',
      'proactiveOrganization',
      'proactiveOrganizationId',
      'status',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'LeadStatus', isRequired: true },
    },
  },
  Link: {
    allFields: [
      'brand',
      'brandId',
      'category',
      'createdAt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'updatedAt',
      'url',
    ],
    enumFields: {
      category: { enumType: 'LinkCategory', isRequired: true },
    },
  },
  LinkClick: {
    allFields: [
      'country',
      'createdAt',
      'device',
      'gaClientId',
      'id',
      'isUnique',
      'link',
      'linkId',
      'mongoId',
      'referrer',
      'sessionId',
      'timestamp',
      'updatedAt',
      'userAgent',
    ],
    enumFields: {},
  },
  LivestreamBotSession: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  McpApproval: {
    allFields: [
      'arguments',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'toolName',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Member: {
    allFields: [
      'authProviderMembershipId',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'lastUsedBrand',
      'lastUsedBrandId',
      'mongoId',
      'organization',
      'organizationId',
      'role',
      'roleId',
      'roleKey',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Metadata: {
    allFields: [
      'assistant',
      'createdAt',
      'description',
      'duration',
      'error',
      'extension',
      'externalId',
      'externalProvider',
      'fps',
      'hasAudio',
      'height',
      'id',
      'isDeleted',
      'label',
      'model',
      'mongoId',
      'prompt',
      'promptId',
      'promptTemplate',
      'resolution',
      'result',
      'seed',
      'size',
      'style',
      'templateVersion',
      'updatedAt',
      'width',
    ],
    enumFields: {
      extension: { enumType: 'MetadataExtension', isRequired: true },
    },
  },
  Model: {
    allFields: [
      'config',
      'externalId',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'parentModel',
      'parentModelId',
      'training',
      'trainingId',
    ],
    enumFields: {},
  },
  MonitoredAccount: {
    allFields: [
      'botConfig',
      'botConfigId',
      'brand',
      'brandId',
      'config',
      'credential',
      'credentialId',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  MoodBoard: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'id',
      'isDeleted',
      'layout',
      'metadata',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  Newsletter: {
    allFields: [
      'agentRun',
      'agentRunId',
      'angle',
      'approvedAt',
      'approvedByUser',
      'approvedByUserId',
      'brand',
      'brandId',
      'content',
      'createdAt',
      'generationPrompt',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'publishedAt',
      'publishedByUser',
      'publishedByUserId',
      'scheduledFor',
      'sourceRefs',
      'status',
      'summary',
      'topic',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Optimization: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'score',
      'scoreId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  OrgIntegration: {
    allFields: [
      'config',
      'encryptedToken',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
    ],
    enumFields: {
      platform: { enumType: 'IntegrationPlatform', isRequired: true },
    },
  },
  Organization: {
    allFields: [
      'accountType',
      'authProviderLogoUrl',
      'authProviderOrganizationId',
      'category',
      'createdAt',
      'id',
      'isDefault',
      'isDeleted',
      'isProactiveOnboarding',
      'isSelected',
      'label',
      'mongoId',
      'onboardingCompleted',
      'prefix',
      'proactiveWelcomeDismissed',
      'settings',
      'slug',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      accountType: { enumType: 'OrganizationCategory', isRequired: false },
      category: { enumType: 'OrganizationCategory', isRequired: true },
    },
  },
  OrganizationSetting: {
    allFields: [
      'agentPolicy',
      'agentReplyStyle',
      'brandsLimit',
      'byokBillingRollover',
      'byokBillingStatus',
      'byokFreeThresholdOverride',
      'byokOpenrouterApiKey',
      'defaultAvatarIngredientId',
      'defaultAvatarPhotoUrl',
      'defaultImageModel',
      'defaultImageToVideoModel',
      'defaultModel',
      'defaultModelReview',
      'defaultModelUpdate',
      'defaultMusicModel',
      'defaultVideoModel',
      'defaultVoiceId',
      'defaultVoiceProvider',
      'defaultVoiceRef',
      'hasEverHadCredits',
      'id',
      'isAdvancedMode',
      'isAutoEvaluateEnabled',
      'isByokEnabled',
      'isDarkroomNsfwVisible',
      'isFastlaneEnabled',
      'isFirstLogin',
      'isGenerateArticlesEnabled',
      'isGenerateImagesEnabled',
      'isGenerateMusicEnabled',
      'isGenerateVideosEnabled',
      'isNotificationsDiscordEnabled',
      'isNotificationsEmailEnabled',
      'isVerifyIngredientEnabled',
      'isVerifyScriptEnabled',
      'isVerifyVideoEnabled',
      'isVoiceControlEnabled',
      'isWatermarkEnabled',
      'isWebhookEnabled',
      'isWhitelabelEnabled',
      'mongoId',
      'onboardingJourneyCompletedAt',
      'onboardingJourneyMissions',
      'organization',
      'organizationId',
      'quotaInstagram',
      'quotaTiktok',
      'quotaTwitter',
      'quotaYoutube',
      'seatsLimit',
      'subscriptionTier',
      'timezone',
      'webhookEndpoint',
      'webhookSecret',
    ],
    enumFields: {
      agentReplyStyle: { enumType: 'AgentReplyStyle', isRequired: true },
      byokBillingStatus: { enumType: 'ByokBillingStatus', isRequired: true },
    },
  },
  OutreachCampaign: {
    allFields: [
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  PatternPlaybook: {
    allFields: [
      'createdById',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  Persona: {
    allFields: [
      'avatarExternalId',
      'avatarIngredient',
      'avatarIngredientId',
      'avatarProvider',
      'brand',
      'brandId',
      'config',
      'description',
      'handle',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'profileImageUrl',
      'slug',
      'status',
      'user',
      'userId',
      'voiceExternalId',
      'voiceIngredient',
      'voiceIngredientId',
      'voiceProvider',
    ],
    enumFields: {
      status: { enumType: 'PersonaStatus', isRequired: true },
    },
  },
  Post: {
    allFields: [
      'agentRun',
      'agentRunId',
      'agentStrategy',
      'agentStrategyId',
      'brand',
      'brandId',
      'category',
      'contentRun',
      'contentRunId',
      'createdAt',
      'creativeVersion',
      'credential',
      'credentialId',
      'description',
      'entityArticle',
      'entityArticleId',
      'entityIngredient',
      'entityIngredientId',
      'entityModel',
      'externalId',
      'externalShortcode',
      'generationId',
      'groupId',
      'hookVersion',
      'id',
      'isAnalyticsEnabled',
      'isDeleted',
      'isRepeat',
      'isShareToFeedSelected',
      'label',
      'lastAttemptAt',
      'maxRepeats',
      'mongoId',
      'nextScheduledDate',
      'order',
      'organization',
      'organizationId',
      'originalPost',
      'originalPostId',
      'parent',
      'parentId',
      'persona',
      'personaId',
      'platform',
      'promptUsed',
      'publicationDate',
      'publishIntent',
      'publishedAt',
      'quoteTweetId',
      'repeatCount',
      'repeatEndDate',
      'repeatFrequency',
      'repeatInterval',
      'retryCount',
      'reviewBatchId',
      'reviewDecision',
      'reviewEvents',
      'reviewFeedback',
      'reviewItemId',
      'reviewedAt',
      'scheduleSlot',
      'scheduledDate',
      'seoBreakdown',
      'seoScore',
      'source',
      'sourceActionId',
      'sourceWorkflowId',
      'sourceWorkflowName',
      'status',
      'timezone',
      'updatedAt',
      'uploadedAt',
      'url',
      'user',
      'userId',
      'variantId',
      'workflowExecution',
      'workflowExecutionId',
    ],
    enumFields: {
      category: { enumType: 'PostCategory', isRequired: true },
      entityModel: { enumType: 'PostEntityModel', isRequired: false },
      reviewDecision: { enumType: 'ReviewDecision', isRequired: false },
    },
  },
  PostAnalytics: {
    allFields: [
      'brand',
      'brandId',
      'createdAt',
      'date',
      'engagementRate',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'post',
      'postId',
      'totalComments',
      'totalCommentsIncrement',
      'totalLikes',
      'totalLikesIncrement',
      'totalSaves',
      'totalSavesIncrement',
      'totalShares',
      'totalSharesIncrement',
      'totalViews',
      'totalViewsIncrement',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      platform: { enumType: 'CredentialPlatform', isRequired: true },
    },
  },
  Preset: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  ProcessedTweet: {
    allFields: [
      'botActivityId',
      'createdAt',
      'id',
      'mongoId',
      'monitoredAccount',
      'monitoredAccountId',
      'organization',
      'organizationId',
      'processedAt',
      'processedBy',
      'replyBotConfig',
      'replyBotConfigId',
      'tweetId',
      'updatedAt',
    ],
    enumFields: {},
  },
  Profile: {
    allFields: [
      'createdBy',
      'createdById',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  Project: {
    allFields: [
      'createdAt',
      'description',
      'id',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'status',
      'updatedAt',
    ],
    enumFields: {},
  },
  Prompt: {
    allFields: [
      'article',
      'articleId',
      'brand',
      'brandId',
      'camera',
      'category',
      'createdAt',
      'duration',
      'enhanced',
      'fontFamily',
      'id',
      'ingredientId',
      'isDeleted',
      'isFavorite',
      'isSkipEnhancement',
      'model',
      'mongoId',
      'mood',
      'organization',
      'organizationId',
      'original',
      'ratio',
      'reference',
      'resolution',
      'scene',
      'scope',
      'seed',
      'speech',
      'status',
      'style',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      category: { enumType: 'PromptCategory', isRequired: false },
      scope: { enumType: 'AssetScope', isRequired: true },
      status: { enumType: 'PromptStatus', isRequired: true },
    },
  },
  ReplyBotConfig: {
    allFields: [
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  RepurposingJob: {
    allFields: [
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Role: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'primaryColor',
      'updatedAt',
    ],
    enumFields: {},
  },
  Run: {
    allFields: [
      'actionType',
      'authType',
      'brandId',
      'completedAt',
      'correlationId',
      'data',
      'durationMs',
      'error',
      'events',
      'id',
      'idempotencyKey',
      'input',
      'metadata',
      'mongoId',
      'organizationId',
      'output',
      'progress',
      'startedAt',
      'status',
      'surface',
      'traceId',
      'trigger',
      'userId',
    ],
    enumFields: {},
  },
  Schedule: {
    allFields: [
      'brand',
      'brandId',
      'contentId',
      'contentType',
      'createdAt',
      'id',
      'isActive',
      'isDeleted',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'platform',
      'scheduledAt',
      'schedulingMethod',
      'slots',
      'timezone',
      'updatedAt',
      'userId',
    ],
    enumFields: {},
  },
  Session: {
    allFields: [
      'activeOrganizationId',
      'createdAt',
      'expiresAt',
      'id',
      'ipAddress',
      'token',
      'updatedAt',
      'user',
      'userAgent',
      'userId',
    ],
    enumFields: {},
  },
  Setting: {
    allFields: [
      'dashboardPreferences',
      'defaultAgentModel',
      'generationPriority',
      'id',
      'isAdvancedMode',
      'isAgentAssetsPanelOpen',
      'isFirstLogin',
      'isMenuCollapsed',
      'isSidebarProgressCollapsed',
      'isSidebarProgressVisible',
      'isTrendNotificationsEmail',
      'isTrendNotificationsInApp',
      'isTrendNotificationsTelegram',
      'isVerified',
      'isVideoNotificationsEmail',
      'isWorkflowNotificationsEmail',
      'mongoId',
      'theme',
      'trendNotificationsEmailAddress',
      'trendNotificationsFrequency',
      'trendNotificationsMinViralScore',
      'trendNotificationsTelegramChatId',
      'user',
      'userId',
    ],
    enumFields: {
      generationPriority: { enumType: 'GenerationPriority', isRequired: true },
      trendNotificationsFrequency: {
        enumType: 'TrendNotificationFrequency',
        isRequired: true,
      },
    },
  },
  Skill: {
    allFields: [
      'config',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  SkillReceipt: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  Streak: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Subscription: {
    allFields: [
      'cancelAtPeriodEnd',
      'createdAt',
      'currentPeriodEnd',
      'currentPeriodStart',
      'customer',
      'customerId',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'plan',
      'status',
      'stripePriceId',
      'stripeSubscriptionId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'SubscriptionStatus', isRequired: true },
    },
  },
  SubscriptionAttribution: {
    allFields: [
      'channel',
      'createdAt',
      'id',
      'metadata',
      'mongoId',
      'organization',
      'organizationId',
      'referrer',
      'sourceContent',
      'sourceContentId',
      'sourceLink',
      'sourceLinkId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Tag: {
    allFields: [
      'backgroundColor',
      'brand',
      'brandId',
      'category',
      'createdAt',
      'description',
      'id',
      'isActive',
      'isDeleted',
      'key',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'textColor',
      'updatedAt',
      'userId',
    ],
    enumFields: {
      category: { enumType: 'TagCategory', isRequired: false },
    },
  },
  Task: {
    allFields: [
      'brandId',
      'config',
      'description',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'parent',
      'parentId',
      'planningThread',
      'planningThreadId',
      'priority',
      'status',
      'title',
      'user',
      'userId',
    ],
    enumFields: {
      priority: { enumType: 'TaskPriority', isRequired: true },
    },
  },
  TaskComment: {
    allFields: [
      'authorId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'task',
      'taskId',
      'updatedAt',
    ],
    enumFields: {},
  },
  TaskCounter: {
    allFields: [
      'counter',
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
    ],
    enumFields: {},
  },
  Template: {
    allFields: [
      'config',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  TemplateMetadata: {
    allFields: ['data', 'id', 'mongoId', 'template', 'templateId'],
    enumFields: {},
  },
  TemplateUsage: {
    allFields: [
      'createdAt',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'template',
      'templateId',
      'updatedAt',
      'userId',
    ],
    enumFields: {},
  },
  ThreadContextState: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'thread',
      'threadId',
    ],
    enumFields: {},
  },
  TrackedLink: {
    allFields: [
      'brand',
      'brandId',
      'campaignName',
      'content',
      'contentId',
      'contentType',
      'customSlug',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'originalUrl',
      'platform',
      'shortCode',
      'shortUrl',
      'stats',
      'title',
      'utm',
    ],
    enumFields: {},
  },
  Training: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'description',
      'externalId',
      'id',
      'label',
      'mongoId',
      'organization',
      'organizationId',
      'persona',
      'personaId',
      'stage',
      'user',
      'userId',
    ],
    enumFields: {
      stage: { enumType: 'TrainingStage', isRequired: true },
    },
  },
  Transcript: {
    allFields: [
      'article',
      'articleId',
      'content',
      'createdAt',
      'id',
      'isDeleted',
      'language',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Trend: {
    allFields: [
      'brand',
      'brandId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  TrendPreferences: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
    ],
    enumFields: {},
  },
  TrendRemixLineage: {
    allFields: [
      'brand',
      'brandId',
      'contentDraft',
      'contentDraftId',
      'data',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'post',
      'postId',
    ],
    enumFields: {},
  },
  TrendSourceReference: {
    allFields: [
      'authorHandle',
      'canonicalUrl',
      'currentEngagementTotal',
      'data',
      'id',
      'lastSeenAt',
      'latestTrendViralityScore',
      'mongoId',
      'platform',
    ],
    enumFields: {},
  },
  TrendSourceReferenceLink: {
    allFields: [
      'createdAt',
      'id',
      'isDeleted',
      'mongoId',
      'sourceReference',
      'sourceReferenceId',
      'trend',
      'trendId',
      'updatedAt',
    ],
    enumFields: {},
  },
  TrendSourceReferenceSnapshot: {
    allFields: [
      'data',
      'id',
      'mongoId',
      'snapshotDate',
      'sourceReference',
      'sourceReferenceId',
    ],
    enumFields: {},
  },
  TrendingHashtag: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  TrendingSound: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  TrendingVideo: {
    allFields: ['data', 'id', 'mongoId'],
    enumFields: {},
  },
  User: {
    allFields: [
      'appSource',
      'authProviderId',
      'avatar',
      'createdAt',
      'email',
      'emailVerified',
      'firstName',
      'handle',
      'id',
      'isDefault',
      'isDeleted',
      'isInvited',
      'isOnboardingCompleted',
      'lastName',
      'lastUsedOrganizationId',
      'mongoId',
      'name',
      'onboardingCompletedAt',
      'onboardingStartedAt',
      'onboardingType',
      'platformRole',
      'settings',
      'stripeCustomerId',
      'updatedAt',
      'userSubscription',
    ],
    enumFields: {
      appSource: { enumType: 'AppSource', isRequired: true },
      onboardingType: { enumType: 'OnboardingType', isRequired: false },
      platformRole: { enumType: 'PlatformRole', isRequired: true },
    },
  },
  UserSubscription: {
    allFields: [
      'cancelAtPeriodEnd',
      'createdAt',
      'currentPeriodEnd',
      'currentPeriodStart',
      'id',
      'isDeleted',
      'mongoId',
      'plan',
      'status',
      'stripePriceId',
      'stripeSubscriptionId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {
      status: { enumType: 'SubscriptionStatus', isRequired: true },
    },
  },
  Verification: {
    allFields: [
      'createdAt',
      'expiresAt',
      'id',
      'identifier',
      'updatedAt',
      'value',
    ],
    enumFields: {},
  },
  Vote: {
    allFields: [
      'createdAt',
      'entityId',
      'entityModel',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'updatedAt',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Watchlist: {
    allFields: [
      'brand',
      'brandId',
      'config',
      'id',
      'mongoId',
      'organization',
      'organizationId',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  Workflow: {
    allFields: [
      'config',
      'description',
      'edges',
      'id',
      'inputVariables',
      'label',
      'mongoId',
      'nodes',
      'organization',
      'organizationId',
      'steps',
      'user',
      'userId',
    ],
    enumFields: {},
  },
  WorkflowExecution: {
    allFields: [
      'completedAt',
      'createdAt',
      'error',
      'id',
      'isDeleted',
      'mongoId',
      'organization',
      'organizationId',
      'result',
      'startedAt',
      'status',
      'trigger',
      'updatedAt',
      'user',
      'userId',
      'workflow',
      'workflowId',
    ],
    enumFields: {
      status: { enumType: 'WorkflowExecutionStatus', isRequired: true },
    },
  },
};

/**
 * Returns model metadata for a given model name (camelCase or PascalCase).
 * Returns undefined when the model is not in the schema.
 */
export function getModelMeta(modelName: string): ModelFieldMeta | undefined {
  const pascal = modelName.charAt(0).toUpperCase() + modelName.slice(1);
  return PRISMA_MODEL_METADATA[pascal];
}
