/**
 * Light-weight testing subpath for @genfeedai/prisma.
 *
 * Re-exports everything a unit test needs to build a faithful
 * `vi.mock('@genfeedai/prisma', ...)` factory WITHOUT pulling in the heavy
 * `PrismaClient` / `@prisma/client/runtime` dependency graph:
 *
 * - All enums (from the generated, dependency-free `enums.ts` leaf module —
 *   confirmed zero imports; regenerated by `prisma generate` on postinstall,
 *   so it never goes stale relative to the schema).
 * - `getModelMeta` + `PRISMA_MODEL_METADATA` (from `enum-field-map.ts`, also
 *   dependency-free — static metadata used by BaseService for enum
 *   normalisation, generated from the same schema).
 *
 * Do NOT import `PrismaClient`, `Prisma`, or anything from `./client` here —
 * that pulls in `@prisma/client/runtime` and reintroduces the exact weight
 * this subpath exists to avoid.
 */
export * from '../generated/prisma/client/enums';
export type { EnumFieldMeta, ModelFieldMeta } from './enum-field-map';
export { getModelMeta, PRISMA_MODEL_METADATA } from './enum-field-map';
