import { motionTokens } from '@ui/core/motion';
import { radiusTokens } from '@ui/core/radius';
import { typographyTokens } from '@ui/core/typography';

export const nativeTokenMap = {
  borderRadius: {
    full: 999,
    lg: 10,
    md: 8,
    sm: 6,
    xl: 12,
    xxl: 14,
    xxxl: 16,
  },
  colors: {
    accent: '#FFFFFF',
    accentDark: '#0A0A0A',
    bgBorder: '#262626',
    bgPrimary: '#0A0A0A',
    bgSecondary: '#0F0F0F',
    bgTertiary: '#1A1A1A',
    black: '#000000',
    error: '#CF3F3F',
    indigo: '#2563EB',
    info: '#0EA5E9',
    primary: '#FFFFFF',
    primaryForeground: '#000000',
    success: '#22C55E',
    textMuted: '#737373',
    textPrimary: '#FAFAFA',
    textSecondary: '#A3A3A3',
    textSubtle: '#525252',
    transparent: 'transparent',
    warning: '#F59E0B',
    warningDark: '#000000',
    white: '#FFFFFF',
  },
  motion: {
    durationFast: motionTokens.durationFast,
    durationNormal: motionTokens.durationNormal,
    durationSlow: motionTokens.durationSlow,
  },
  radius: radiusTokens,
  spacing: {
    lg: 16,
    md: 12,
    sm: 8,
    xl: 20,
    xs: 4,
    xxl: 24,
    xxxl: 32,
    xxxxl: 48,
  },
  typography: {
    fontSans: typographyTokens.fontSans,
    fontSerif: typographyTokens.fontSerif,
    h1: 26,
    h2: 24,
    h3: 20,
    hero: 28,
    lg: 14,
    md: 13,
    sm: 12,
    xl: 15,
    xs: 11,
    xxl: 16,
    xxxl: 18,
  },
} as const;
