import { motionTokens } from '@ui/core/motion';
import { radiusTokens } from '@ui/core/radius';
import { typographyTokens } from '@ui/core/typography';

export const nativeTokenMap = {
  borderRadius: {
    full: 9999,
    lg: 8,
    md: 6,
    sm: 4,
    xl: 10,
    xxl: 12,
    xxxl: 16,
  },
  colors: {
    accent: '#FFFFFF',
    accentDark: '#000000',
    agent: '#38BDF8',
    bgBorder: '#262626',
    bgPrimary: '#030303',
    bgSecondary: '#0F0F0F',
    bgTertiary: '#1A1A1A',
    black: '#000000',
    error: '#DC2626',
    google: '#4285F4',
    indigo: '#2563EB',
    info: '#3B82F6',
    overlayScrim: 'rgba(0, 0, 0, 0.7)',
    primary: '#FFFFFF',
    primaryForeground: '#000000',
    success: '#10B981',
    textMuted: '#949494',
    textPrimary: '#FAFAFA',
    textSecondary: '#949494',
    textSubtle: '#707070',
    transparent: 'transparent',
    warning: '#F59E0B',
    warningDark: '#000000',
    white: '#FFFFFF',
  },
  motion: {
    durationFast: motionTokens.durationFast,
    durationNormal: motionTokens.durationNormal,
    durationSlow: motionTokens.durationSlow,
  },
  radius: radiusTokens,
  spacing: {
    lg: 16,
    md: 12,
    sm: 8,
    xl: 20,
    xs: 4,
    xxl: 24,
    xxxl: 32,
    xxxxl: 48,
  },
  typography: {
    fontSans: typographyTokens.fontSans,
    fontSerif: typographyTokens.fontSerif,
    h1: 26,
    h2: 24,
    h3: 20,
    hero: 28,
    lg: 14,
    md: 13,
    sm: 12,
    xl: 15,
    xs: 11,
    xxl: 16,
    xxxl: 18,
  },
} as const;
