export const webviewSemanticTokenMap = {
  accent: 'var(--vscode-list-hoverBackground)',
  accentForeground: 'var(--vscode-foreground)',
  background: 'var(--vscode-sideBar-background)',
  border: 'var(--vscode-widget-border)',
  card: 'var(--vscode-editor-background)',
  cardForeground: 'var(--vscode-foreground)',
  destructive: 'var(--vscode-errorForeground)',
  destructiveForeground: 'white',
  foreground: 'var(--vscode-foreground)',
  input: 'var(--vscode-input-border)',
  muted: 'var(--vscode-textBlockQuote-background)',
  mutedForeground: 'var(--vscode-descriptionForeground)',
  popover: 'var(--vscode-editor-background)',
  popoverForeground: 'var(--vscode-foreground)',
  primary: 'var(--vscode-button-background)',
  primaryForeground: 'var(--vscode-button-foreground)',
  ring: 'var(--vscode-focusBorder)',
  secondary: 'var(--vscode-button-secondaryBackground)',
  secondaryForeground: 'var(--vscode-button-secondaryForeground)',
} as const;
