/**
 * Guard: every domain enum that shares a name with a Prisma column enum must
 * use the Prisma label as its value (SCREAMING_SNAKE). This is the class of
 * bug that made `status: "pending"` fail at runtime while TypeScript stayed silent.
 *
 * When you add a Prisma enum member, add it here too.
 *
 * @see .claude/rules/enum_source_of_truth.md
 * @see packages/prisma/prisma/schema.prisma
 */
import { describe, expect, it } from 'vitest';
import {
  AgentAutonomyMode,
  AgentPublishDecision,
  AgentReplyStyle,
  ApiKeyCategory,
  AppSource,
  ArticleStatus,
  AssetCategory,
  AssetParent,
  AssetScope,
  BatchItemStatus,
  BatchStatus,
  BillingAccountMemberRole,
  BillingAccountOrganizationStatus,
  BillingAccountStatus,
  BookmarkCategory,
  BookmarkIntent,
  BookmarkPlatform,
  BotStatus,
  BrandInterviewStatus,
  ByokBillingStatus,
  ContentRating,
  CreditReservationStatus,
  EngagementMetric,
  EngagementRuleAction,
  EngagementRuleMode,
  EngagementRuleState,
  FleetAssetLabel,
  FleetReviewStatus,
  FontFamily,
  GenerationPriority,
  IngredientCategory,
  IngredientStatus,
  IntegrationPlatform,
  IntegrationStatus,
  KnowledgeProcessingState,
  KnowledgeRetentionPolicy,
  KnowledgeRetentionState,
  KnowledgeRetrievalState,
  KnowledgeSourceKind,
  KnowledgeSourcePurpose,
  LeadStatus,
  LinkCategory,
  McpApprovalStatus,
  MetadataExtension,
  OnboardingType,
  OrganizationCategory,
  PersistedReviewDecision,
  PersonaStatus,
  PlatformRole,
  PostCategory,
  PostEntityModel,
  PromptCategory,
  PromptStatus,
  QualityStatus,
  ReferenceImageCategory,
  RssApprovalMode,
  RssFeedItemStatus,
  RssImportPolicy,
  SocialWarmupEnrollmentState,
  SocialWarmupEventAction,
  SocialWarmupSignalSource,
  SocialWarmupSignalStatus,
  SubscriptionStatus,
  TagCategory,
  TrainingStage,
  TransformationCategory,
  TrendNotificationFrequency,
  VoiceCloneStatus,
  VoiceProvider,
  WarmupAccountStatus,
  WorkflowExecutionStatus,
} from '../../src';

/** Prisma labels that MUST appear as domain enum values (extras allowed). */
const PRISMA_REQUIRED: Record<string, readonly string[]> = {
  KnowledgeSourceKind: [
    'TEXT',
    'URL',
    'FILE',
    'DOCUMENT',
    'VIDEO',
    'AUDIO',
    'RSS',
  ],
  KnowledgeSourcePurpose: ['BRAND_TRUTH', 'INSPIRATION', 'RESEARCH'],
  KnowledgeProcessingState: ['QUEUED', 'PROCESSING', 'READY', 'FAILED'],
  KnowledgeRetrievalState: [
    'ACTIVE',
    'STALE',
    'CONTRADICTED',
    'SUPERSEDED',
    'QUARANTINED',
    'EXPIRED',
  ],
  KnowledgeRetentionState: [
    'RETAINED',
    'SCHEDULED_FOR_PURGE',
    'PAYLOAD_PURGED',
    'POLICY_ERASED',
  ],
  KnowledgeRetentionPolicy: ['KEEP', 'UNTIL_EXPIRY'],

  AgentAutonomyMode: ['SUPERVISED', 'AUTO_PUBLISH'],
  AgentPublishDecision: ['PERMITTED', 'DENIED'],
  AgentReplyStyle: ['CONCISE', 'DETAILED', 'FRIENDLY', 'PROFESSIONAL'],
  ApiKeyCategory: ['GENFEEDAI', 'ELEVENLABS', 'HEDRA', 'HEYGEN', 'OPUS_PRO'],
  AppSource: ['GENFEED', 'GETSHAREABLE'],
  ArticleStatus: ['DRAFT', 'PUBLISHED', 'ARCHIVED'],
  AssetCategory: ['LOGO', 'BANNER', 'REFERENCE'],
  AssetParent: ['ORGANIZATION', 'INGREDIENT', 'BRAND', 'ARTICLE'],
  AssetScope: ['USER', 'BRAND', 'ORGANIZATION', 'PUBLIC'],
  BatchItemStatus: ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED'],
  BatchStatus: [
    'PENDING',
    'PROCESSING',
    'COMPLETED',
    'PARTIAL',
    'FAILED',
    'CANCELLED',
  ],
  BillingAccountMemberRole: ['OWNER', 'ADMINISTRATOR', 'VIEWER'],
  BillingAccountOrganizationStatus: ['LINKED', 'DETACHED'],
  BillingAccountStatus: [
    'UNPROVISIONED',
    'ACTIVE',
    'PAST_DUE',
    'CANCELLED',
    'STALE',
  ],
  BookmarkCategory: ['INSTAGRAM', 'TIKTOK', 'TWEET', 'URL', 'YOUTUBE'],
  BookmarkIntent: ['VIDEO', 'IMAGE', 'REPLY', 'REFERENCE', 'INSPIRATION'],
  BookmarkPlatform: ['INSTAGRAM', 'TIKTOK', 'TWITTER', 'WEB', 'YOUTUBE'],
  BotStatus: ['ACTIVE', 'PAUSED', 'STOPPED'],
  BrandInterviewStatus: ['IN_PROGRESS', 'COMPLETED', 'ABANDONED'],
  ByokBillingStatus: ['ACTIVE', 'PAST_DUE', 'SUSPENDED'],
  ContentRating: ['SFW', 'SUGGESTIVE', 'NSFW'],
  CreditReservationStatus: ['RESERVED', 'SETTLED', 'RELEASED', 'EXPIRED'],
  EngagementMetric: ['LIKES', 'COMMENTS', 'SHARES', 'VIEWS', 'ENGAGEMENT_RATE'],
  EngagementRuleAction: ['REPOST', 'FOLLOW_UP_COMMENT'],
  EngagementRuleMode: ['APPROVAL', 'AUTO'],
  EngagementRuleState: [
    'ARMED',
    'TRIGGERED',
    'COMPLETED',
    'EXPIRED',
    'DISABLED',
  ],
  FleetAssetLabel: ['HERO', 'FILLER', 'BTS', 'PROMO', 'LIFESTYLE', 'EDITORIAL'],
  FleetReviewStatus: ['PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVISION'],
  FontFamily: ['MONTSERRAT_BLACK', 'MONTSERRAT_BOLD', 'MONTSERRAT_REGULAR'],
  GenerationPriority: ['QUALITY', 'SPEED', 'COST', 'BALANCED'],
  IngredientCategory: [
    'IMAGE',
    'VIDEO',
    'MUSIC',
    'GIF',
    'AVATAR',
    'AUDIO',
    'IMAGE_EDIT',
    'VIDEO_EDIT',
    'VOICE',
    'INGREDIENT',
    'TEXT',
    'SOURCE',
  ],
  IngredientStatus: [
    'DRAFT',
    'PROCESSING',
    'UPLOADED',
    'GENERATED',
    'VALIDATED',
    'FAILED',
    'ARCHIVED',
    'REJECTED',
  ],
  IntegrationPlatform: ['TELEGRAM', 'SLACK', 'DISCORD', 'UNIPILE'],
  IntegrationStatus: ['ACTIVE', 'PAUSED', 'ERROR'],
  LeadStatus: ['NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST'],
  McpApprovalStatus: ['PENDING', 'APPROVED', 'DECLINED'],
  LinkCategory: [
    'FACEBOOK',
    'INSTAGRAM',
    'LINKEDIN',
    'OTHER',
    'TIKTOK',
    'TWITTER',
    'WEBSITE',
    'YOUTUBE',
  ],
  MetadataExtension: [
    'JPEG',
    'JPG',
    'PNG',
    'GIF',
    'WEBP',
    'MP4',
    'WEBM',
    'MOV',
    'AVI',
    'MP3',
    'WAV',
  ],
  OnboardingType: ['CREATOR', 'ORGANIZATION'],
  OrganizationCategory: ['CREATOR', 'BUSINESS', 'AGENCY'],
  PersonaStatus: ['ACTIVE', 'INACTIVE', 'ARCHIVED'],
  PlatformRole: ['USER', 'SUPERADMIN'],
  PostCategory: ['ARTICLE', 'VIDEO', 'POST', 'REEL', 'STORY', 'IMAGE', 'TEXT'],
  PostEntityModel: ['INGREDIENT', 'ARTICLE'],
  RssApprovalMode: ['APPROVAL', 'AUTO'],
  RssFeedItemStatus: ['PENDING', 'IMPORTED', 'SKIPPED', 'FAILED'],
  RssImportPolicy: ['DRAFT', 'SCHEDULED', 'PUBLISH_NOW'],
  PromptCategory: [
    'BRAND_DESCRIPTION',
    'STORYBOARD_SCRIPT_DESCRIPTION',
    'PRESET_DESCRIPTION_TEXT',
    'PRESET_DESCRIPTION_IMAGE',
    'PRESET_DESCRIPTION_VIDEO',
    'PRESET_DESCRIPTION_MUSIC',
    'POST_CONTENT_TWITTER',
    'POST_CONTENT_YOUTUBE',
    'POST_CONTENT_TIKTOK',
    'POST_CONTENT_INSTAGRAM',
    'POST_TITLE_TWITTER',
    'POST_TITLE_YOUTUBE',
    'POST_TITLE_TIKTOK',
    'POST_TITLE_INSTAGRAM',
    'MODELS_PROMPT_IMAGE',
    'MODELS_PROMPT_VIDEO',
    'MODELS_PROMPT_MUSIC',
    'MODELS_PROMPT_TRAINING',
    'ARTICLE',
  ],
  PromptStatus: ['DRAFT', 'PROCESSING', 'GENERATED', 'FAILED'],
  QualityStatus: ['UNRATED', 'GOOD', 'NEEDS_REVIEW'],
  ReferenceImageCategory: ['FACE', 'PRODUCT', 'STYLE', 'LOGO'],
  ReviewDecision: ['APPROVED', 'REJECTED', 'REQUEST_CHANGES'],
  SubscriptionStatus: [
    'ACTIVE',
    'CANCELLED',
    'PAST_DUE',
    'TRIALING',
    'INCOMPLETE',
  ],
  TagCategory: [
    'ORGANIZATION',
    'CREDENTIAL',
    'INGREDIENT',
    'PROMPT',
    'ARTICLE',
  ],
  TrainingStage: [
    'PENDING',
    'UPLOADING',
    'TRAINING',
    'READY',
    'FAILED',
    'CANCELLED',
  ],
  TransformationCategory: [
    'UPSCALED',
    'RESIZED',
    'ENHANCED',
    'EXTENDED',
    'INTERPOLATED',
    'STABILIZED',
    'BACKGROUND_REMOVED',
    'STYLE_TRANSFERRED',
    'FACE_SWAPPED',
    'LIP_SYNCED',
    'ANIMATED',
    'IMAGE_TO_VIDEO',
    'CLIPPED',
    'MERGED',
    'EDITED',
    'REVERSED',
    'MIRRORED',
    'CAPTIONED',
    'VALIDATED',
    'REFRAMED',
  ],
  TrendNotificationFrequency: ['REALTIME', 'HOURLY', 'DAILY', 'WEEKLY'],
  VoiceCloneStatus: ['PENDING', 'CLONING', 'READY', 'FAILED'],
  VoiceProvider: ['HEYGEN', 'ELEVENLABS', 'HEDRA', 'GENFEED_AI'],
  WarmupAccountStatus: [
    'DRAFT',
    'PROVISIONING',
    'PROVISIONED',
    'INVITED',
    'FAILED',
    'CLAIMED',
    'ARCHIVED',
  ],
  SocialWarmupEnrollmentState: [
    'ENROLLED',
    'IN_PROGRESS',
    'PAUSED',
    'GRADUATED',
    'BLOCKED',
    'DISCONNECTED',
  ],
  SocialWarmupEventAction: ['COMPLETED', 'REOPENED'],
  SocialWarmupSignalSource: ['PLATFORM', 'GENFEED', 'USER'],
  SocialWarmupSignalStatus: [
    'AVAILABLE',
    'EMPTY',
    'STALE',
    'UNAVAILABLE',
    'PERMISSION_LIMITED',
    'FAILED',
    'MISSING',
    'REVOKED',
  ],
  WorkflowExecutionStatus: [
    'PENDING',
    'RUNNING',
    'COMPLETED',
    'FAILED',
    'CANCELLED',
  ],
};

const DOMAIN_ENUMS: Record<string, Record<string, string>> = {
  AgentAutonomyMode,
  AgentPublishDecision,
  AgentReplyStyle,
  ApiKeyCategory,
  AppSource,
  ArticleStatus,
  AssetCategory,
  AssetParent,
  AssetScope,
  BatchItemStatus,
  BatchStatus,
  BillingAccountMemberRole,
  BillingAccountOrganizationStatus,
  BillingAccountStatus,
  BookmarkCategory,
  BookmarkIntent,
  BookmarkPlatform,
  BotStatus,
  BrandInterviewStatus,
  ByokBillingStatus,
  ContentRating,
  CreditReservationStatus,
  EngagementMetric,
  EngagementRuleAction,
  EngagementRuleMode,
  EngagementRuleState,
  FleetAssetLabel,
  FleetReviewStatus,
  FontFamily,
  GenerationPriority,
  IngredientCategory,
  IngredientStatus,
  IntegrationPlatform,
  IntegrationStatus,
  KnowledgeSourceKind,
  KnowledgeSourcePurpose,
  KnowledgeProcessingState,
  KnowledgeRetrievalState,
  KnowledgeRetentionState,
  KnowledgeRetentionPolicy,

  LeadStatus,
  McpApprovalStatus,
  LinkCategory,
  MetadataExtension,
  OnboardingType,
  OrganizationCategory,
  PersonaStatus,
  PlatformRole,
  PostCategory,
  PostEntityModel,
  PromptCategory,
  PromptStatus,
  QualityStatus,
  ReferenceImageCategory,
  ReviewDecision: PersistedReviewDecision,
  RssApprovalMode,
  RssFeedItemStatus,
  RssImportPolicy,
  SubscriptionStatus,
  TagCategory,
  TrainingStage,
  TransformationCategory,
  TrendNotificationFrequency,
  VoiceCloneStatus,
  VoiceProvider,
  WarmupAccountStatus,
  SocialWarmupEnrollmentState,
  SocialWarmupEventAction,
  SocialWarmupSignalSource,
  SocialWarmupSignalStatus,
  WorkflowExecutionStatus,
};

describe('prisma-parity (domain enum values === Prisma labels)', () => {
  for (const [name, required] of Object.entries(PRISMA_REQUIRED)) {
    it(`${name} includes every Prisma label as a value`, () => {
      const domain = DOMAIN_ENUMS[name];
      expect(domain, `missing domain export ${name}`).toBeDefined();
      const values = new Set(Object.values(domain));
      for (const label of required) {
        expect(values.has(label), `${name} missing value ${label}`).toBe(true);
      }
    });
  }

  it('domain enum values for Prisma-backed enums are SCREAMING_SNAKE', () => {
    for (const [name, required] of Object.entries(PRISMA_REQUIRED)) {
      for (const label of required) {
        expect(label).toMatch(/^[A-Z][A-Z0-9_]*$/);
        expect(DOMAIN_ENUMS[name]).toBeDefined();
      }
    }
  });

  /**
   * The membership check above allows domain-only extras (Stripe-only
   * subscription states). It does NOT catch a *lowercase* value
   * sitting alongside the correct labels — which is exactly how `LinkCategory`
   * and `BookmarkCategory` aliased `Platform` ids into Prisma enum columns and
   * silently killed every read-side comparison.
   *
   * Extras are still fine; lowercase extras are not.
   */
  for (const name of Object.keys(PRISMA_REQUIRED)) {
    it(`${name} has no non-SCREAMING_SNAKE values`, () => {
      const domain = DOMAIN_ENUMS[name];
      expect(domain, `missing domain export ${name}`).toBeDefined();
      for (const value of Object.values(domain)) {
        expect(
          value,
          `${name} value "${value}" is not a Prisma-shaped label`,
        ).toMatch(/^[A-Z][A-Z0-9_]*$/);
      }
    });
  }
});
