import type { MenuItemConfig } from '@genfeedai/interfaces/ui/menu-config.interface';
import {
  HiChartBar,
  HiChatBubbleLeftRight,
  HiClipboardDocumentList,
  HiCog6Tooth,
  HiCpuChip,
  HiCreditCard,
  HiDocumentText,
  HiMegaphone,
  HiNewspaper,
  HiOutlineChartBar,
  HiOutlineChatBubbleLeftRight,
  HiOutlineClipboardDocumentList,
  HiOutlineCog6Tooth,
  HiOutlineCpuChip,
  HiOutlineCreditCard,
  HiOutlineDocumentText,
  HiOutlineMegaphone,
  HiOutlineNewspaper,
  HiOutlinePhoto,
  HiOutlineShieldCheck,
  HiOutlineSpeakerWave,
  HiOutlineTag,
  HiOutlineUserGroup,
  HiOutlineVideoCamera,
  HiPhoto,
  HiShieldCheck,
  HiSpeakerWave,
  HiTag,
  HiUserGroup,
  HiVideoCamera,
} from 'react-icons/hi2';

export const ADMIN_MENU_ITEMS: MenuItemConfig[] = [
  // AGENT
  {
    group: '',
    href: '/agent',
    label: 'Agent',
    matchPaths: ['/agent'],
    outline: HiOutlineChatBubbleLeftRight,
    solid: HiChatBubbleLeftRight,
  },
  // OVERVIEW
  {
    drillDown: true,
    group: 'Overview',
    href: '/overview/dashboard',
    label: 'Dashboard',
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Overview',
    href: '/overview/analytics',
    label: 'Analytics',
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Overview',
    href: '/overview/activities',
    label: 'Activities',
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  // CONTENT
  {
    drillDown: true,
    group: 'Content',
    href: '/content/posts',
    label: 'Posts',
    outline: HiOutlineNewspaper,
    solid: HiNewspaper,
  },
  {
    group: 'Content',
    href: '/content/templates',
    label: 'Templates',
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Content',
    href: '/content/prompts',
    label: 'Prompts',
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Content',
    href: '/content/ingredients',
    label: 'Ingredients',
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  // AI & AUTOMATION
  {
    drillDown: true,
    group: 'AI & Automation',
    href: '/automation/models',
    label: 'Models',
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: '/automation/trainings',
    label: 'Trainings',
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: '/automation/bots',
    label: 'Bots',
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: '/library/voices',
    label: 'Voice Library',
    outline: HiOutlineSpeakerWave,
    solid: HiSpeakerWave,
  },
  {
    group: 'AI & Automation',
    href: '/automation/workflows',
    label: 'Workflows',
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  // CONFIGURATION
  {
    drillDown: true,
    group: 'Configuration',
    href: '/configuration/elements',
    label: 'Elements',
    outline: HiOutlineTag,
    solid: HiTag,
  },
  {
    group: 'Configuration',
    href: '/configuration/presets',
    label: 'Presets',
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Configuration',
    href: '/configuration/font-families',
    label: 'Font Families',
    outline: HiOutlineCog6Tooth,
    solid: HiCog6Tooth,
  },
  {
    group: 'Configuration',
    href: '/configuration/tags',
    label: 'Tags',
    outline: HiOutlineTag,
    solid: HiTag,
  },
  // ADMINISTRATION
  {
    drillDown: true,
    group: 'Administration',
    href: '/administration/users',
    label: 'Users',
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Administration',
    href: '/administration/roles',
    label: 'Roles',
    outline: HiOutlineShieldCheck,
    solid: HiShieldCheck,
  },
  {
    group: 'Administration',
    href: '/administration/subscriptions',
    label: 'Subscriptions',
    outline: HiOutlineCreditCard,
    solid: HiCreditCard,
  },
  {
    group: 'Administration',
    href: '/administration/announcements',
    label: 'Announcements',
    outline: HiOutlineMegaphone,
    solid: HiMegaphone,
  },
  // DARKROOM
  {
    drillDown: true,
    group: 'Darkroom',
    hasDividerAbove: true,
    href: '/darkroom/characters',
    label: 'Characters',
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/gallery',
    label: 'Gallery',
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/training',
    label: 'Training',
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/pipeline',
    label: 'Pipeline',
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/generate',
    label: 'Generate',
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/lip-sync',
    label: 'Lip Sync',
    outline: HiOutlineVideoCamera,
    solid: HiVideoCamera,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/voices',
    label: 'Voices',
    outline: HiOutlineSpeakerWave,
    solid: HiSpeakerWave,
  },
  {
    group: 'Darkroom',
    href: '/darkroom/infrastructure',
    label: 'Infrastructure',
    outline: HiOutlineCog6Tooth,
    solid: HiCog6Tooth,
  },
  // CRM
  {
    drillDown: true,
    group: 'CRM',
    href: '/crm/leads',
    label: 'Leads',
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'CRM',
    href: '/crm/companies',
    label: 'Companies',
    outline: HiOutlineNewspaper,
    solid: HiNewspaper,
  },
  {
    group: 'CRM',
    href: '/crm/tasks',
    label: 'Tasks',
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    group: 'CRM',
    href: '/crm/margins',
    label: 'Margins',
    outline: HiOutlineCreditCard,
    solid: HiCreditCard,
  },
  {
    group: 'CRM',
    href: '/crm/analytics',
    label: 'Analytics',
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'CRM',
    href: '/crm/alignment',
    label: 'Alignment',
    outline: HiOutlineShieldCheck,
    solid: HiShieldCheck,
  },
  // MARKETPLACE
  {
    drillDown: true,
    group: 'Marketplace',
    href: '/marketplace',
    label: 'Management',
    outline: HiOutlineNewspaper,
    solid: HiNewspaper,
  },
];

export const ADMIN_LOGO_HREF = '/overview/dashboard';
