import { IngredientCategory } from '@genfeedai/enums';

/**
 * TrainingFilterUtil - Utility for building training-specific query filters and lookups
 *
 * Provides reusable filter builders for training-related query patterns.
 * Handles training-specific logic like source images and generated images lookups.
 *
 * @example
 * // Build source images lookup
 * const sourceLookup = TrainingFilterUtil.buildSourceImagesLookup({
 *   sourceIdsVar: '$sources',
 *   userIdVar: '$user',
 *   as: 'sourceImages'
 * });
 *
 * // Build generated images lookup
 * const generatedLookup = TrainingFilterUtil.buildGeneratedImagesLookup({
 *   metadataIdsVar: '$metadataWithModel._id',
 *   as: 'generatedImages'
 * });
 *
 * // Use in aggregation pipeline
 * const pipeline: Record<string, unknown>[] = [
 *   { $match: { ...baseMatch } },
 *   sourceLookup,
 *   generatedLookup,
 * ];
 */
export class TrainingFilterUtil {
  /**
   * Build source images lookup pipeline stage
   *
   * Creates a complete $lookup stage for finding ingredient source images for a training.
   * Includes all required filters: user match, category, ID match, and isDeleted.
   *
   * This lookup finds ingredients that are referenced in training.sources array.
   *
   * @param options - Configuration for the lookup
   * @param options.sourceIdsVar - Variable name for source IDs array (e.g., '$sources' or '$$sourceIds')
   * @param options.userIdVar - Variable name for user ID (e.g., '$user' or '$$userId')
   * @param options.as - Output field name (default: 'sourceImages')
   * @param options.category - Ingredient category (default: IngredientCategory.IMAGE)
   * @returns Complete $lookup pipeline stage
   *
   * @example
   * // In trainings controller
   * TrainingFilterUtil.buildSourceImagesLookup({
   *   sourceIdsVar: '$sources',
   *   userIdVar: '$user',
   *   as: 'sourceImages'
   * })
   * // Returns: Complete $lookup stage with user, category, ID, and isDeleted filters
   */
  static buildSourceImagesLookup(options: {
    sourceIdsVar: string;
    userIdVar: string;
    as?: string;
    category?: IngredientCategory;
  }): Record<string, unknown> {
    const {
      sourceIdsVar,
      userIdVar,
      as = 'sourceImages',
      category = IngredientCategory.IMAGE,
    } = options;

    // Normalize variable names - ensure single $ for let section
    const sourceIdsField = sourceIdsVar.startsWith('$')
      ? sourceIdsVar
      : `$${sourceIdsVar}`;
    const userIdField = userIdVar.startsWith('$') ? userIdVar : `$${userIdVar}`;

    return {
      $lookup: {
        as,
        from: 'ingredients',
        let: {
          sourceIds: sourceIdsField,
          userId: userIdField,
        },
        pipeline: [
          {
            $match: {
              $expr: {
                $and: [
                  { $eq: ['$user', '$$userId'] },
                  { $eq: ['$category', category] },
                  { $in: ['$_id', '$$sourceIds'] },
                  { $eq: ['$isDeleted', false] },
                ],
              },
            },
          },
        ],
      },
    };
  }

  /**
   * Build generated images lookup pipeline stage
   *
   * Creates a complete $lookup stage for finding ingredients generated by a training model.
   * Includes all required filters: category, metadata match, and isDeleted.
   *
   * This lookup finds ingredients that were generated using the training model
   * by matching metadata.model to the training.model.
   *
   * @param options - Configuration for the lookup
   * @param options.metadataIdsVar - Variable name for metadata IDs array (e.g., '$metadataWithModel._id' or '$$metadataIds')
   * @param options.as - Output field name (default: 'generatedImages')
   * @param options.category - Ingredient category (default: IngredientCategory.IMAGE)
   * @returns Complete $lookup pipeline stage
   *
   * @example
   * // In trainings controller
   * TrainingFilterUtil.buildGeneratedImagesLookup({
   *   metadataIdsVar: '$metadataWithModel._id',
   *   as: 'generatedImages'
   * })
   * // Returns: Complete $lookup stage with category, metadata, and isDeleted filters
   */
  static buildGeneratedImagesLookup(options: {
    metadataIdsVar: string;
    as?: string;
    category?: IngredientCategory;
  }): Record<string, unknown> {
    const {
      metadataIdsVar,
      as = 'generatedImages',
      category = IngredientCategory.IMAGE,
    } = options;

    // Normalize variable name - ensure single $ for let section
    const metadataIdsField = metadataIdsVar.startsWith('$')
      ? metadataIdsVar
      : `$${metadataIdsVar}`;

    return {
      $lookup: {
        as,
        from: 'ingredients',
        let: {
          metadataIds: metadataIdsField,
        },
        pipeline: [
          {
            $match: {
              $expr: {
                $and: [
                  { $eq: ['$category', category] },
                  { $in: ['$metadata', '$$metadataIds'] },
                  { $eq: ['$isDeleted', false] },
                ],
              },
            },
          },
        ],
      },
    };
  }
}
