import { createEntityAttributes } from '@genfeedai/helpers';

export const purchaseAttributes = createEntityAttributes([
  'buyer',
  'seller',
  'listing',
  'organization',
  'listingSnapshot',
  'subtotal',
  'discount',
  'total',
  'currency',
  'platformFee',
  'sellerEarnings',
  'stripeSessionId',
  'paymentMethod',
  'status',
  'failureReason',
  'downloadCount',
  'lastDownloadedAt',
  'hasReviewed',
  'review',
  'isGift',
  'giftRecipient',
  'giftMessage',
  'discountCode',
  'createdAt',
  'updatedAt',
]);
