-- First-party product skills from skills/*/SKILL.md.
-- Original five handler identities are unchanged; this migration only inserts
-- additional catalog-global rows. Full SKILL.md bodies are applied by
-- SkillCatalogSeedService on API boot and must not be duplicated here.
-- Re-running is idempotent (ON CONFLICT DO NOTHING).

UPDATE "skills"
SET
  "isDeleted" = true,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "organizationId" IS NOT NULL
  AND "isDeleted" = false
  AND COALESCE("config"->>'slug', '') = ANY (ARRAY[
    'ad-copy-creator',
    'ad-performance-analyzer',
    'blog-content-creator',
    'brand-os-architect',
    'cinematic-prompting',
    'competitor-analyzer',
    'content-atomizer',
    'content-reviewer',
    'content-seo-optimizer',
    'content-strategist',
    'genfeed-brand-os',
    'image-prompt-engineer',
    'instagram-content-creator',
    'instagram-warmup',
    'launch-copy-creator',
    'linkedin-content-creator',
    'linkedin-warmup',
    'model-selector',
    'newsletter-creator',
    'node-creator',
    'onboarding',
    'openclaw-integration',
    'prompt-generator',
    'scope-validator',
    'tiktok-warmup',
    'visual-brand-kit',
    'workflow-creator',
    'x-content-creator',
    'x-warmup',
    'youtube-content-creator',
    'youtube-warmup'
  ]::text[]);

INSERT INTO "skills" (
  "id",
  "organizationId",
  "label",
  "config",
  "isDeleted",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'cskillbuiltinadcopycreator',
    NULL,
    'Ad Copy Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create high-converting ad copy for Meta, Google, LinkedIn, TikTok, and X using proven direct response frameworks. Triggers on "write ad copy", "create an ad", "write a facebook ad", "google ad copy", "ad headline", "write ad creative", "ad variants".',
      'description', 'Create high-converting ad copy for Meta, Google, LinkedIn, TikTok, and X using proven direct response frameworks. Triggers on "write ad copy", "create an ad", "write a facebook ad", "google ad copy", "ad headline", "write ad creative", "ad variants".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Ad Copy Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'ad-copy-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinadperformanceanalyzer',
    NULL,
    'Ad Performance Analyzer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Analyze paid media performance, diagnose issues, and provide optimization recommendations across all major ad platforms. Triggers on "analyze ad performance", "ad metrics", "why is my ROAS low", "ad optimization", "campaign performance", "creative fatigue", "ad budget allocation".',
      'description', 'Analyze paid media performance, diagnose issues, and provide optimization recommendations across all major ad platforms. Triggers on "analyze ad performance", "ad metrics", "why is my ROAS low", "ad optimization", "campaign performance", "creative fatigue", "ad budget allocation".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Ad Performance Analyzer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'ad-performance-analyzer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinblogcontentcreator',
    NULL,
    'Blog Content Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create SEO-optimized blog posts in multiple formats with heading hierarchy, meta descriptions, and internal link strategy. Triggers on "write a blog post", "create a blog article", "draft a blog", "write an article", "blog about".',
      'description', 'Create SEO-optimized blog posts in multiple formats with heading hierarchy, meta descriptions, and internal link strategy. Triggers on "write a blog post", "create a blog article", "draft a blog", "write an article", "blog about".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Blog Content Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'blog-content-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinbrandosarchitect',
    NULL,
    'Brand OS Architect',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create source-backed Brand OS systems for AI-era brands, including positioning, voice, visual rules, content pillars, launch storytelling, CTA strategy, evidence, and generation checklists. Triggers on Brand OS, brand system, brand operating system, AI-readable brand book, brand kit generator, launch storytelling, Japanese color references, cute studies, and source-backed brand strategy.',
      'description', 'Create source-backed Brand OS systems for AI-era brands, including positioning, voice, visual rules, content pillars, launch storytelling, CTA strategy, evidence, and generation checklists. Triggers on Brand OS, brand system, brand operating system, AI-readable brand book, brand kit generator, launch storytelling, Japanese color references, cute studies, and source-backed brand strategy.',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Brand OS Architect',
      'requiredProviders', jsonb_build_array(),
      'slug', 'brand-os-architect',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincinematicprompting',
    NULL,
    'Cinematic Prompting',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Rewrite naive image and video prompts with precise cinematography vocabulary. Triggers on "cinematic prompt", "film language", "camera movement", "make it cinematic", "shot from above", "enhance this image prompt", "enhance this video prompt", "cinematography vocabulary", "rewrite with camera terms".',
      'description', 'Rewrite naive image and video prompts with precise cinematography vocabulary. Triggers on "cinematic prompt", "film language", "camera movement", "make it cinematic", "shot from above", "enhance this image prompt", "enhance this video prompt", "cinematography vocabulary", "rewrite with camera terms".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Cinematic Prompting',
      'requiredProviders', jsonb_build_array(),
      'slug', 'cinematic-prompting',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincompetitoranalyzer',
    NULL,
    'Competitor Analyzer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Analyze competitors'' content strategies, identify gaps and opportunities, and deliver actionable competitive intelligence reports. Triggers on "analyze competitor", "competitive analysis", "competitor content", "gap analysis", "what are competitors doing", "competitor research".',
      'description', 'Analyze competitors'' content strategies, identify gaps and opportunities, and deliver actionable competitive intelligence reports. Triggers on "analyze competitor", "competitive analysis", "competitor content", "gap analysis", "what are competitors doing", "competitor research".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Competitor Analyzer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'competitor-analyzer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincontentatomizer',
    NULL,
    'Content Atomizer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Repurpose one piece of content into dozens of platform-optimized derivatives with scheduling cadence and adaptation rules. Triggers on "atomize content", "repurpose content", "turn this into", "create derivatives", "cross-platform content".',
      'description', 'Repurpose one piece of content into dozens of platform-optimized derivatives with scheduling cadence and adaptation rules. Triggers on "atomize content", "repurpose content", "turn this into", "create derivatives", "cross-platform content".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Content Atomizer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'content-atomizer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincontentreviewer',
    NULL,
    'Content Reviewer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Review and score content quality across six dimensions with actionable feedback. Triggers on "review this content", "score this post", "check content quality", "review my copy", "is this post ready to publish", "critique this content".',
      'description', 'Review and score content quality across six dimensions with actionable feedback. Triggers on "review this content", "score this post", "check content quality", "review my copy", "is this post ready to publish", "critique this content".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Content Reviewer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'content-reviewer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincontentseooptimizer',
    NULL,
    'Content SEO Optimizer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Analyze and optimize content for SEO with a 0-100 scoring rubric, platform-specific rules, and actionable improvement priorities. Triggers on "optimize for SEO", "SEO score", "check SEO", "audit content", "improve search ranking".',
      'description', 'Analyze and optimize content for SEO with a 0-100 scoring rubric, platform-specific rules, and actionable improvement priorities. Triggers on "optimize for SEO", "SEO score", "check SEO", "audit content", "improve search ranking".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Content SEO Optimizer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'content-seo-optimizer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltincontentstrategist',
    NULL,
    'Content Strategist',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Build comprehensive content strategies including audience definition, content pillars, platform selection, posting cadence, editorial calendars, and KPI frameworks. Triggers on "content strategy", "editorial calendar", "content plan", "what should I post", "posting schedule", "content pillars".',
      'description', 'Build comprehensive content strategies including audience definition, content pillars, platform selection, posting cadence, editorial calendars, and KPI frameworks. Triggers on "content strategy", "editorial calendar", "content plan", "what should I post", "posting schedule", "content pillars".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Content Strategist',
      'requiredProviders', jsonb_build_array(),
      'slug', 'content-strategist',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltingenfeedbrandos',
    NULL,
    'Genfeed Brand OS',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Apply the Genfeed.ai Brand OS to product copy, website CTAs, launch content, skills, examples, prompts, and generation context. Triggers when creating Genfeed-branded content, Genfeed website copy, Genfeed launch narratives, Brand OS generator examples, product messaging, or AI-readable Genfeed brand guidance.',
      'description', 'Apply the Genfeed.ai Brand OS to product copy, website CTAs, launch content, skills, examples, prompts, and generation context. Triggers when creating Genfeed-branded content, Genfeed website copy, Genfeed launch narratives, Brand OS generator examples, product messaging, or AI-readable Genfeed brand guidance.',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Genfeed Brand OS',
      'requiredProviders', jsonb_build_array(),
      'slug', 'genfeed-brand-os',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinimagepromptengineer',
    NULL,
    'Image Prompt Engineer',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Craft optimized prompts for AI image generation across all major models. Triggers on "write an image prompt", "create a prompt for", "optimize this image prompt", "prompt for flux", "prompt for dall-e", "prompt for midjourney", "image prompt for".',
      'description', 'Craft optimized prompts for AI image generation across all major models. Triggers on "write an image prompt", "create a prompt for", "optimize this image prompt", "prompt for flux", "prompt for dall-e", "prompt for midjourney", "image prompt for".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Image Prompt Engineer',
      'requiredProviders', jsonb_build_array(),
      'slug', 'image-prompt-engineer',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltininstagramcontentcreator',
    NULL,
    'Instagram Content Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create Instagram content including captions, carousel outlines, Reels scripts, Story sequences, and hashtag strategies. Triggers on "write an instagram caption", "create instagram content", "carousel outline", "reel script", "hashtag strategy".',
      'description', 'Create Instagram content including captions, carousel outlines, Reels scripts, Story sequences, and hashtag strategies. Triggers on "write an instagram caption", "create instagram content", "carousel outline", "reel script", "hashtag strategy".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Instagram Content Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'instagram-content-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltininstagramwarmup',
    NULL,
    'Instagram Warmup',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Guide Instagram account warmup with engagement plans, Stories strategy, Reel and carousel warmup content, and post-warmup assessment frameworks. Triggers on "instagram warmup", "warm up instagram account", "new instagram account", "instagram account warmup plan", "instagram engagement plan", "warmup content instagram", "instagram trust score", "first post on instagram".',
      'description', 'Guide Instagram account warmup with engagement plans, Stories strategy, Reel and carousel warmup content, and post-warmup assessment frameworks. Triggers on "instagram warmup", "warm up instagram account", "new instagram account", "instagram account warmup plan", "instagram engagement plan", "warmup content instagram", "instagram trust score", "first post on instagram".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Instagram Warmup',
      'requiredProviders', jsonb_build_array(),
      'slug', 'instagram-warmup',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinlaunchcopycreator',
    NULL,
    'Launch Copy Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Generate channel-conform launch copy for Hacker News (Show HN) and Product Hunt. Triggers on "write a show hn", "show hn title", "hacker news launch", "product hunt tagline", "product hunt launch copy", "maker comment", "launch copy".',
      'description', 'Generate channel-conform launch copy for Hacker News (Show HN) and Product Hunt. Triggers on "write a show hn", "show hn title", "hacker news launch", "product hunt tagline", "product hunt launch copy", "maker comment", "launch copy".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Launch Copy Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'launch-copy-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinlinkedincontentcreator',
    NULL,
    'Linkedin Content Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create LinkedIn content including posts, articles, carousels, and newsletters for professional growth. Triggers on "write a linkedin post", "linkedin article", "linkedin carousel", "thought leadership", "professional post".',
      'description', 'Create LinkedIn content including posts, articles, carousels, and newsletters for professional growth. Triggers on "write a linkedin post", "linkedin article", "linkedin carousel", "thought leadership", "professional post".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Linkedin Content Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'linkedin-content-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinlinkedinwarmup',
    NULL,
    'Linkedin Warmup',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Guide LinkedIn account warmup with engagement plans, SSI-building strategy, comment-first content, and post-warmup assessment. Triggers on "linkedin warmup", "warm up linkedin", "new linkedin account", "linkedin account warmup plan", "linkedin engagement plan", "warmup content linkedin", "linkedin trust score", "first post on linkedin", "SSI score".',
      'description', 'Guide LinkedIn account warmup with engagement plans, SSI-building strategy, comment-first content, and post-warmup assessment. Triggers on "linkedin warmup", "warm up linkedin", "new linkedin account", "linkedin account warmup plan", "linkedin engagement plan", "warmup content linkedin", "linkedin trust score", "first post on linkedin", "SSI score".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Linkedin Warmup',
      'requiredProviders', jsonb_build_array(),
      'slug', 'linkedin-warmup',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinmodelselector',
    NULL,
    'Model Selector',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Recommend the best AI model for image, video, and audio generation tasks. Triggers on "which model should I use", "recommend a model", "best model for", "what model for", "compare models", "fastest model for", "cheapest model for".',
      'description', 'Recommend the best AI model for image, video, and audio generation tasks. Triggers on "which model should I use", "recommend a model", "best model for", "what model for", "compare models", "fastest model for", "cheapest model for".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Model Selector',
      'requiredProviders', jsonb_build_array(),
      'slug', 'model-selector',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinnewslettercreator',
    NULL,
    'Newsletter Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create high-performing email newsletters with subject lines, editorial structures, and subscriber growth tactics. Triggers on "write a newsletter", "create a newsletter", "draft newsletter", "email newsletter", "newsletter edition".',
      'description', 'Create high-performing email newsletters with subject lines, editorial structures, and subscriber growth tactics. Triggers on "write a newsletter", "create a newsletter", "draft newsletter", "email newsletter", "newsletter edition".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Newsletter Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'newsletter-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinnodecreator',
    NULL,
    'Node Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create custom Genfeed nodes using the SDK. Triggers on "create a new node", "add a custom node type", "build a node for X".',
      'description', 'Create custom Genfeed nodes using the SDK. Triggers on "create a new node", "add a custom node type", "build a node for X".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Node Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'node-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinonboarding',
    NULL,
    'Onboarding',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Quick onboarding for Genfeed focused on first content creation. Triggers on "how do I use genfeed", "getting started", "what is this app", "help me create my first content".',
      'description', 'Quick onboarding for Genfeed focused on first content creation. Triggers on "how do I use genfeed", "getting started", "what is this app", "help me create my first content".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Onboarding',
      'requiredProviders', jsonb_build_array(),
      'slug', 'onboarding',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinopenclawintegration',
    NULL,
    'Openclaw Integration',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Connect to Genfeed.ai to create AI videos, images, articles, and more. Use when "genfeed", "create content", "generate video", "generate image", "publish content" mentioned.',
      'description', 'Connect to Genfeed.ai to create AI videos, images, articles, and more. Use when "genfeed", "create content", "generate video", "generate image", "publish content" mentioned.',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Openclaw Integration',
      'requiredProviders', jsonb_build_array(),
      'slug', 'openclaw-integration',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinpromptgenerator',
    NULL,
    'Prompt Generator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Generate optimized prompts for AI image and video generation. Triggers on "generate a prompt for", "write me a prompt", "create an image prompt", "create a video prompt", "optimize this prompt".',
      'description', 'Generate optimized prompts for AI image and video generation. Triggers on "generate a prompt for", "write me a prompt", "create an image prompt", "create a video prompt", "optimize this prompt".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Prompt Generator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'prompt-generator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinscopevalidator',
    NULL,
    'Scope Validator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Validate feature requests against Genfeed OSS core vs Cloud scope. Helps users and contributors understand whether a feature belongs in the open-source core (submit PR) or Cloud SaaS (subscribe).',
      'description', 'Validate feature requests against Genfeed OSS core vs Cloud scope. Helps users and contributors understand whether a feature belongs in the open-source core (submit PR) or Cloud SaaS (subscribe).',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Scope Validator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'scope-validator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltintiktokwarmup',
    NULL,
    'Tiktok Warmup',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Guide a transparent TikTok 5–7 day warm-up with native-app engagement, profile and feed tuning, gradual first uploads, and evidence-aware assessment. Triggers on "tiktok warmup", "warm up tiktok account", "new tiktok account", "tiktok account warmup plan", "tiktok engagement plan", "warmup content tiktok".',
      'description', 'Guide a transparent TikTok 5–7 day warm-up with native-app engagement, profile and feed tuning, gradual first uploads, and evidence-aware assessment. Triggers on "tiktok warmup", "warm up tiktok account", "new tiktok account", "tiktok account warmup plan", "tiktok engagement plan", "warmup content tiktok".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Tiktok Warmup',
      'requiredProviders', jsonb_build_array(),
      'slug', 'tiktok-warmup',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinvisualbrandkit',
    NULL,
    'Visual Brand Kit',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create comprehensive visual brand identity systems for AI-generated content. Triggers on "create a brand kit", "visual brand identity", "brand style guide", "define brand visuals", "brand colors and style", "create visual guidelines", "brand photography style".',
      'description', 'Create comprehensive visual brand identity systems for AI-generated content. Triggers on "create a brand kit", "visual brand identity", "brand style guide", "define brand visuals", "brand colors and style", "create visual guidelines", "brand photography style".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Visual Brand Kit',
      'requiredProviders', jsonb_build_array(),
      'slug', 'visual-brand-kit',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinworkflowcreator',
    NULL,
    'Workflow Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create Genfeed workflows from natural language descriptions. Triggers on "create a workflow", "build a content pipeline", "make a video generation workflow".',
      'description', 'Create Genfeed workflows from natural language descriptions. Triggers on "create a workflow", "build a content pipeline", "make a video generation workflow".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Workflow Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'workflow-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinxcontentcreator',
    NULL,
    'X Content Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create high-performing X/Twitter content including tweets, threads, quote tweets, and reply strategies. Triggers on "write a tweet", "create a thread", "draft a tweet", "compose a tweet", "quote tweet", "tweet about".',
      'description', 'Create high-performing X/Twitter content including tweets, threads, quote tweets, and reply strategies. Triggers on "write a tweet", "create a thread", "draft a tweet", "compose a tweet", "quote tweet", "tweet about".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'X Content Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'x-content-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinxwarmup',
    NULL,
    'X Warmup',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Guide X/Twitter account warmup and source-backed X content hardening with engagement plans, reply-first strategy, warmup thread content, and post-warmup assessment. Triggers on "x warmup", "twitter warmup", "warm up x account", "new x account", "x account warmup plan", "x engagement plan", "warmup content x", "harder X content", "X content hardening".',
      'description', 'Guide X/Twitter account warmup and source-backed X content hardening with engagement plans, reply-first strategy, warmup thread content, and post-warmup assessment. Triggers on "x warmup", "twitter warmup", "warm up x account", "new x account", "x account warmup plan", "x engagement plan", "warmup content x", "harder X content", "X content hardening".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'X Warmup',
      'requiredProviders', jsonb_build_array(),
      'slug', 'x-warmup',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinyoutubecontentcreator',
    NULL,
    'Youtube Content Creator',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Create YouTube content including titles, descriptions, tags, thumbnail briefs, Shorts scripts, and retention strategies. Triggers on "write a youtube title", "youtube description", "youtube tags", "thumbnail brief", "shorts script", "youtube seo".',
      'description', 'Create YouTube content including titles, descriptions, tags, thumbnail briefs, Shorts scripts, and retention strategies. Triggers on "write a youtube title", "youtube description", "youtube tags", "thumbnail brief", "shorts script", "youtube seo".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Youtube Content Creator',
      'requiredProviders', jsonb_build_array(),
      'slug', 'youtube-content-creator',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'cskillbuiltinyoutubewarmup',
    NULL,
    'Youtube Warmup',
    jsonb_build_object(
      'category', 'writing',
      'channels', jsonb_build_array(),
      'defaultInstructions', 'Guide YouTube channel warmup with engagement plans, channel optimization, warmup Shorts content, SEO-first setup, and post-warmup assessment. Triggers on "youtube warmup", "warm up youtube channel", "new youtube channel", "youtube channel warmup plan", "youtube engagement plan", "warmup content youtube", "youtube shorts warmup".',
      'description', 'Guide YouTube channel warmup with engagement plans, channel optimization, warmup Shorts content, SEO-first setup, and post-warmup assessment. Triggers on "youtube warmup", "warm up youtube channel", "new youtube channel", "youtube channel warmup plan", "youtube engagement plan", "warmup content youtube", "youtube shorts warmup".',
      'isBuiltIn', true,
      'isEnabled', true,
      'modalities', jsonb_build_array('text'),
      'name', 'Youtube Warmup',
      'requiredProviders', jsonb_build_array(),
      'slug', 'youtube-warmup',
      'source', 'built_in',
      'status', 'published',
      'toolOverrides', jsonb_build_array(),
      'version', '1.0.0',
      'workflowStage', 'creation'
    ),
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO NOTHING;
