### Genfeed API - Credentials Collection Endpoints
### Manage third-party API credentials
### Handles: credential CRUD, encryption

########################################
# List & Filter Credentials
########################################

### Get All Credentials (Paginated)
GET {{apiBaseUrl}}/credentials
Authorization: Bearer {{bearerToken}}


### Filter Credentials by Provider
GET {{apiBaseUrl}}/credentials?provider=twitter
Authorization: Bearer {{bearerToken}}


########################################
# Get Single Credential
########################################

### Get Credential by ID
GET {{apiBaseUrl}}/credentials/{{testCredentialId}}
Authorization: Bearer {{bearerToken}}


########################################
# Create Credential
########################################

### Create Twitter Credential
POST {{apiBaseUrl}}/credentials
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "provider": "twitter",
  "accessToken": "encrypted_token",
  "accessSecret": "encrypted_secret"
}


########################################
# Update Credential
########################################

### Update Credential
PATCH {{apiBaseUrl}}/credentials/{{testCredentialId}}
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "accessToken": "new_encrypted_token"
}


########################################
# Delete Credential
########################################

### Delete Credential
DELETE {{apiBaseUrl}}/credentials/{{testCredentialId}}
Authorization: Bearer {{bearerToken}}


########################################
# Test Cases
########################################

### Test: Unauthorized Access
GET {{apiBaseUrl}}/credentials
