// Real enums + real getModelMeta/PRISMA_MODEL_METADATA — dependency-free leaf
// modules (packages/prisma/generated/prisma/client/enums.ts and
// packages/prisma/src/enum-field-map.ts). Importing this subpath never pulls
// in `PrismaClient` / `@prisma/client/runtime`, so it's safe inside
// `vi.mock('@genfeedai/prisma', ...)` factories (hoisted, evaluated before
// any real module graph loads).
import * as prismaTesting from '@genfeedai/prisma/testing';
import { vi } from 'vitest';

export type MockSql = {
  sql: string;
  text: string;
  values: unknown[];
};

function isSqlFragment(value: unknown): value is MockSql {
  return (
    typeof value === 'object' &&
    value !== null &&
    ('sql' in value || 'text' in value)
  );
}

function createSql(sql: string, values: unknown[] = []): MockSql {
  return { sql, text: sql, values };
}

function getSqlText(value: unknown): string {
  if (!isSqlFragment(value)) return '?';
  return value.sql || value.text;
}

/**
 * Stub `Prisma` namespace covering every member actually read as a VALUE
 * (not just a TypeScript type) anywhere in apps/server/api/src:
 * `Prisma.sql`, `Prisma.raw`, `Prisma.empty`, `Prisma.join`, `Prisma.Sql`,
 * `Prisma.PrismaClientKnownRequestError`. Everything else the codebase
 * writes as `Prisma.XWhereInput` etc. is a type, erased at compile time —
 * it needs no runtime stub.
 */
export class MockPrismaClientKnownRequestError extends Error {
  code: string;
  clientVersion: string;
  meta?: Record<string, unknown>;

  constructor(
    message: string,
    options: {
      code: string;
      clientVersion: string;
      meta?: Record<string, unknown>;
    },
  ) {
    super(message);
    this.name = 'PrismaClientKnownRequestError';
    this.code = options.code;
    this.clientVersion = options.clientVersion;
    this.meta = options.meta;
  }
}

export const mockPrismaNamespace = {
  empty: createSql(''),
  join: (values: unknown[], separator = ',') =>
    createSql(values.map((value) => getSqlText(value)).join(separator), values),
  PrismaClientKnownRequestError: MockPrismaClientKnownRequestError,
  raw: (sql: string) => createSql(sql),
  sql: (strings: TemplateStringsArray, ...values: unknown[]) => {
    const sql = strings.reduce((acc, part, index) => {
      const value = index < values.length ? getSqlText(values[index]) : '';
      return `${acc}${part}${value}`;
    }, '');

    return createSql(sql, values);
  },
  Sql: class MockSqlClass {
    sql: string;
    values: unknown[];

    constructor(sql: string, values: unknown[] = []) {
      this.sql = sql;
      this.values = values;
    }
  },
};

/**
 * Stub `PrismaClient` — matches the real class shape closely enough for
 * services that construct/inject it directly (e.g. `PrismaService`).
 * `$transaction` supports both the array form (`Promise.all`) and the
 * callback form (invoked with a fresh client instance).
 */
export class MockPrismaClient {
  $connect = vi.fn().mockResolvedValue(undefined);
  $disconnect = vi.fn().mockResolvedValue(undefined);
  $queryRaw = vi.fn().mockResolvedValue([]);
  $executeRaw = vi.fn().mockResolvedValue(0);
  $transaction = vi
    .fn()
    .mockImplementation((arg: unknown) =>
      Array.isArray(arg)
        ? Promise.all(arg)
        : typeof arg === 'function'
          ? (arg as (client: MockPrismaClient) => unknown)(
              new MockPrismaClient(),
            )
          : Promise.resolve(arg),
    );
}

/**
 * Canonical `@genfeedai/prisma` mock factory.
 *
 * Spread this inside `vi.mock('@genfeedai/prisma', () => canonicalPrismaMock())`
 * (or `() => ({ ...canonicalPrismaMock(), <override> })`) so every spec sees:
 * - every real enum (from the light `@genfeedai/prisma/testing` subpath —
 *   never stale, regenerated by `prisma generate`)
 * - the real `getModelMeta` / `PRISMA_MODEL_METADATA` (genuine schema-derived
 *   field/enum metadata for every model — no more hand-rolled partial maps)
 * - a `Prisma` namespace stub covering the handful of runtime-used members
 * - a `PrismaClient` stub class
 *
 * Specs needing a custom `getModelMeta` (e.g. a `vi.fn()` they drive with
 * `mockReturnValue(...)` per test, or a deliberately-missing enum to exercise
 * a fallback path) should override that key AFTER spreading this factory's
 * result — object literal key order means the override wins.
 */
export function canonicalPrismaMock() {
  return {
    ...prismaTesting,
    Prisma: mockPrismaNamespace,
    PrismaClient: MockPrismaClient,
  };
}
