import { createEntityAttributes } from '@genfeedai/helpers';

export const savedAdAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'userId',
  'source',
  'platform',
  'sourceAdId',
  'sourceRecordId',
  'channel',
  'credentialId',
  'adAccountId',
  'loginCustomerId',
  'advertiserId',
  'advertiserName',
  'title',
  'headline',
  'body',
  'cta',
  'explanation',
  'landingPageUrl',
  'previewUrl',
  'imageUrls',
  'videoUrls',
  'metrics',
  'patternSummary',
  'usagePolicy',
  'firstSeenAt',
  'lastSeenAt',
  'capturedAt',
  'note',
]);
