import { defineConfig } from 'tsup';

export default defineConfig([
  {
    clean: true,
    dts: true,
    entry: [
      'src/index.ts',
      'src/contracts/index.ts',
      'src/engine/index.ts',
      'src/generation/index.ts',
      'src/generation/comfyui/index.ts',
      'src/nodes/index.ts',
    ],
    format: ['esm'],
    sourcemap: true,
  },
  {
    bundle: false,
    clean: false,
    dts: true,
    entry: {
      canvas: 'src/ui/canvas/index.ts',
      hooks: 'src/ui/hooks/index.ts',
      index: 'src/ui/index.ts',
      lib: 'src/ui/lib/index.ts',
      nodes: 'src/ui/nodes/index.ts',
      panels: 'src/ui/panels/index.ts',
      provider: 'src/ui/provider/index.ts',
      stores: 'src/ui/stores/index.ts',
      toolbar: 'src/ui/toolbar/index.ts',
      ui: 'src/ui/ui/index.ts',
    },
    external: [
      'react',
      'react-dom',
      '@xyflow/react',
      'zustand',
      'zundo',
      'next',
      'next/image',
      '@genfeedai/pricing',
      '@genfeedai/types',
    ],
    format: ['esm'],
    jsx: 'automatic',
    noExternal: ['react-compare-slider'],
    outDir: 'dist/ui',
    outExtension: () => ({ js: '.mjs' }),
    sourcemap: true,
    treeshake: true,
    tsconfig: 'tsconfig.json',
  },
]);
