import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

// Contract for the OSS release tooling decided in #2995 (children #2999, #3001):
// one repo version, a generated changelog, and a Conventional Commits PR title
// that becomes the squash subject and the changelog line.

const REPOSITORY_ROOT = fileURLToPath(new URL('../..', import.meta.url));

function readRepoFile(relativePath) {
  return readFileSync(path.join(REPOSITORY_ROOT, relativePath), 'utf8');
}

const releaseWorkflow = readRepoFile('.github/workflows/release.yml');
const prTitleWorkflow = readRepoFile('.github/workflows/pr-title.yml');
const cliffConfig = readRepoFile('cliff.toml');
const pullRequestTemplate = readRepoFile('.github/pull_request_template.md');
const rootPackage = JSON.parse(readRepoFile('package.json'));

function jobBlock(workflow, jobId, fileName) {
  const match = workflow.match(
    new RegExp(`^ {2}${jobId}:\\n((?: {4}.*(?:\\n|$)|\\n)+)`, 'm'),
  );
  assert.ok(match, `${fileName} must define the ${jobId} job`);
  return match[1];
}

function conventionalTypesFromTemplate() {
  const match = pullRequestTemplate.match(/\(((?:\w+, )+\w+)\)\. Lowercase/);
  assert.ok(
    match,
    'pull_request_template.md must list the allowed Conventional Commits types',
  );
  return match[1].split(', ');
}

test('release ties the dispatched tag to the root package.json version', () => {
  const validate = jobBlock(releaseWorkflow, 'validate-release', 'release.yml');

  assert.match(
    validate,
    /Validate release tag shape[\s\S]*?\^v\[0-9\]\+\\\.\[0-9\]\+\\\.\[0-9\]\+\$/,
    'the tag shape is validated before it reaches any action argument',
  );
  assert.match(
    validate,
    /package_version="\$\(jq -r '\.version' package\.json\)"/,
  );
  assert.match(
    validate,
    /if \[ "v\$\{package_version\}" != "\$\{REQUESTED_TAG\}" \]; then/,
  );
  assert.match(
    rootPackage.version,
    /^\d+\.\d+\.\d+$/,
    'root package.json carries the plain semver that the release tag prefixes with v',
  );
});

test('release notes and CHANGELOG.md are generated by git-cliff, never by GitHub', () => {
  const validate = jobBlock(releaseWorkflow, 'validate-release', 'release.yml');

  assert.doesNotMatch(validate, /--generate-notes/);
  assert.match(validate, /uses: orhun\/git-cliff-action@v\d+\.\d+\.\d+/);
  assert.match(validate, /config: cliff\.toml/);
  assert.match(
    validate,
    /args: --unreleased --tag \$\{\{ inputs\.tag \}\} --strip header[\s\S]*?OUTPUT: release-notes\.md/,
    'the release body is the unreleased section for the dispatched tag',
  );
  assert.match(
    validate,
    /args: --tag \$\{\{ inputs\.tag \}\}\n[\s\S]*?OUTPUT: CHANGELOG\.md/,
    'the full changelog is generated for the release asset',
  );
  assert.match(
    validate,
    /gh release create "\$\{release_tag\}" \\\n\s+--draft \\\n\s+--notes-file release-notes\.md/,
  );
  assert.match(
    validate,
    /gh release edit "\$\{release_tag\}" --notes-file release-notes\.md/,
    'a reused draft gets refreshed notes instead of stale ones',
  );
  assert.match(
    validate,
    /gh release upload "\$\{release_tag\}" CHANGELOG\.md --clobber/,
  );
});

test('cliff.toml groups Conventional Commit PR titles and links squash PR numbers', () => {
  assert.match(cliffConfig, /^conventional_commits = true$/m);
  assert.match(cliffConfig, /^tag_pattern = "v\[0-9\]\.\*"$/m);
  assert.match(
    cliffConfig,
    /^skip_tags = "desktop-v\.\*\|mobile-v\.\*\|extension-browser-v\.\*"$/m,
    'independent surfaces never appear in the repo changelog',
  );
  assert.match(cliffConfig, /^protect_breaking_commits = true$/m);
  assert.match(cliffConfig, /### ⚠ Upgrade note/);
  assert.match(
    cliffConfig,
    /replace = "\(\[#\$\{2\}\]\(<REPO>\/pull\/\$\{2\}\)\)"/,
    'squash-merge PR numbers become links',
  );
  assert.match(
    cliffConfig,
    /pattern = '<REPO>', replace = "https:\/\/github\.com\/genfeedai\/genfeed\.ai"/,
  );

  for (const type of conventionalTypesFromTemplate()) {
    assert.match(
      cliffConfig,
      new RegExp(`message = "\\^[^"]*\\b${type}\\b[^"]*"`),
      `cliff.toml must route ${type} commits into a section`,
    );
  }
});

test('PR titles are checked without executing fork code and stay in sync with the contract', () => {
  assert.match(
    prTitleWorkflow,
    /^ {2}pull_request_target:\n {4}types: \[opened, edited, synchronize, reopened\]$/m,
  );
  assert.doesNotMatch(
    prTitleWorkflow,
    /^ {2}pull_request:/m,
    'the check must not need run-ci approval',
  );
  assert.doesNotMatch(
    prTitleWorkflow,
    /actions\/checkout/,
    'pull_request_target must never check out PR code',
  );
  assert.match(prTitleWorkflow, /^permissions:\n {2}pull-requests: read$/m);
  assert.match(
    prTitleWorkflow,
    /uses: amannn\/action-semantic-pull-request@v\d+\.\d+\.\d+/,
  );
  // `github.event.pull_request` is absent on merge_group runs (#3143); each
  // queue entry's `gh-readonly-queue/...` ref keeps the group unique there.
  assert.match(
    prTitleWorkflow,
    /group: \$\{\{ github\.workflow \}\}-\$\{\{ github\.event\.pull_request\.number \|\| github\.ref \}\}/,
  );
  assert.match(
    prTitleWorkflow,
    /^ {2}merge_group:\n {4}types: \[checks_requested\]$/m,
    'PR Title is a required context, so it must also report on the merge queue commit',
  );

  const typesBlock = prTitleWorkflow.match(
    /^ {10}types: \|\n((?: {12}\w+\n)+)/m,
  );
  assert.ok(typesBlock, 'pr-title.yml must list the allowed types');
  const workflowTypes = typesBlock[1].trim().split(/\s+/).sort();
  assert.deepEqual(
    workflowTypes,
    [...conventionalTypesFromTemplate()].sort(),
    'pr-title.yml types must equal the list in pull_request_template.md',
  );
});
