import { cdnAsset } from '@helpers/media/cdn/cdn.helper';
import type { HomeOutputAsset } from '@props/website/home.props';

// Homepage marketing media is served from the Genfeed CDN
// (s3://cdn.genfeed.ai/assets/branding/website/home/**), not committed to the
// website `public/` folder, keeping the binaries out of the repo and letting the
// assets be refreshed without a code deploy. URLs are built from the shared
// cdnAsset() helper so the CDN base is defined in exactly one place.
//
// Everything below is generated by `scripts/generate-home-video.ts` through the
// same Replicate provider the product uses. Each poster is frame 0 of its own
// encoded MP4, which is what makes the still-to-playback handoff seamless —
// regenerate a clip and its poster together, never one without the other.
const home = (file: string) =>
  cdnAsset(`/assets/branding/website/home/${file}`);

/** The four files every generated clip ships as. */
const clip = (directory: string, name: string) => ({
  mp4: home(`${directory}/${name}.mp4`),
  poster: home(`${directory}/${name}-poster.webp`),
  webm: home(`${directory}/${name}.webm`),
});

export const HOME_HERO_VIDEO = {
  ...clip('hero', 'hero-loop'),
  alt: 'Generated creator footage playing behind the Genfeed headline',
} as const;

/**
 * The output rail. Order is the argument: a campaign still, then the same brand
 * moving, then the ad, then long-form, then a presenter, then voice — widest
 * surface first, narrowest last.
 */
export const HOME_OUTPUT_CAROUSEL_ASSETS: readonly HomeOutputAsset[] = [
  {
    ...clip('formats', 'images'),
    alt: 'Generated product photography for a launch campaign',
    format: 'Product campaign',
    title: 'One visual world',
  },
  {
    ...clip('formats', 'reels'),
    alt: 'Generated short-form video staged for a reels campaign',
    format: 'Short-form video',
    title: 'Made to move',
  },
  {
    ...clip('formats', 'ads'),
    alt: 'Generated ad creative for a paid campaign',
    format: 'Ads & creative',
    title: 'Ready to perform',
  },
  {
    ...clip('formats', 'articles'),
    alt: 'Generated editorial layout for a long-form article',
    format: 'Articles & newsletters',
    title: 'Ideas with depth',
  },
  {
    ...clip('formats', 'avatars'),
    alt: 'Generated presenter clip for a spoken campaign asset',
    format: 'AI influencer',
    title: 'Always on-brand',
  },
  {
    ...clip('formats', 'voice'),
    alt: 'Generated voice production for a podcast campaign',
    format: 'Podcasts & voice',
    title: 'Worth listening to',
  },
] as const;
