export type CuratedActionSurface = 'agent' | 'mcp';

export interface CuratedActionCatalogEntry {
  isPublishingApprovalRequired?: true;
  name: string;
  surfaces: readonly [CuratedActionSurface, ...CuratedActionSurface[]];
}

/**
 * Reviewed product-action inventory for the in-app Agent and MCP server.
 *
 * This is the only source of truth for surface intent. Tool definition shards
 * provide schemas and metadata, while this catalog decides whether an action
 * is available on Agent, MCP, or both. Keep entries sorted by action name so
 * additions, removals, and surface transitions remain obvious in review.
 */
export const CURATED_ACTION_CATALOG = [
  { name: 'ai_action', surfaces: ['agent'] },
  { name: 'analyze_clip_project', surfaces: ['mcp'] },
  { name: 'analyze_performance', surfaces: ['agent', 'mcp'] },
  {
    isPublishingApprovalRequired: true,
    name: 'approve_social_draft',
    surfaces: ['mcp'],
  },
  { name: 'assign_social_conversation', surfaces: ['mcp'] },
  { name: 'batch_approve_reject', surfaces: ['agent'] },
  { name: 'capture_memory', surfaces: ['agent'] },
  { name: 'check_goal_progress', surfaces: ['agent'] },
  { name: 'check_onboarding_status', surfaces: ['agent'] },
  { name: 'compare_meta_campaigns', surfaces: ['mcp'] },
  { name: 'complete_onboarding', surfaces: ['agent'] },
  { name: 'complete_outreach_sequence', surfaces: ['agent'] },
  { name: 'connect_social_account', surfaces: ['agent'] },
  {
    isPublishingApprovalRequired: true,
    name: 'control_scheduled_release',
    surfaces: ['mcp'],
  },
  { name: 'create_ad_remix_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'create_article', surfaces: ['mcp'] },
  { name: 'create_brand', surfaces: ['agent'] },
  { name: 'create_chat', surfaces: ['mcp'] },
  { name: 'create_clip_project_from_youtube', surfaces: ['mcp'] },
  { name: 'create_goal', surfaces: ['agent'] },
  { name: 'create_instagram_remix_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'create_livestream_bot', surfaces: ['agent'] },
  { name: 'create_outreach_sequence', surfaces: ['agent'] },
  {
    isPublishingApprovalRequired: true,
    name: 'create_post',
    surfaces: ['agent', 'mcp'],
  },
  {
    isPublishingApprovalRequired: true,
    name: 'create_scheduled_release',
    surfaces: ['mcp'],
  },
  { name: 'create_social_reply_draft', surfaces: ['mcp'] },
  { name: 'create_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'discover_engagements', surfaces: ['agent'] },
  { name: 'draft_brand_voice_profile', surfaces: ['agent'] },
  { name: 'draft_engagement_reply', surfaces: ['agent'] },
  { name: 'draft_x_quote', surfaces: ['agent'] },
  { name: 'draft_x_repost', surfaces: ['agent'] },
  { name: 'duplicate_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'execute_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'fetch_x_post', surfaces: ['agent', 'mcp'] },
  { name: 'generate_ad_pack', surfaces: ['agent'] },
  { name: 'generate_as_identity', surfaces: ['agent'] },
  { name: 'generate_clips', surfaces: ['mcp'] },
  { name: 'generate_content', surfaces: ['agent'] },
  { name: 'generate_content_batch', surfaces: ['agent', 'mcp'] },
  { name: 'generate_image', surfaces: ['agent', 'mcp'] },
  { name: 'generate_linkedin_content', surfaces: ['mcp'] },
  { name: 'generate_monthly_content', surfaces: ['agent'] },
  { name: 'generate_music', surfaces: ['agent', 'mcp'] },
  { name: 'generate_onboarding_content', surfaces: ['agent'] },
  { name: 'generate_video', surfaces: ['agent', 'mcp'] },
  { name: 'generate_voice', surfaces: ['agent', 'mcp'] },
  { name: 'get_account_info', surfaces: ['mcp'] },
  { name: 'get_ad_research_detail', surfaces: ['agent', 'mcp'] },
  { name: 'get_ads_ad_insights', surfaces: ['mcp'] },
  { name: 'get_ads_adset_insights', surfaces: ['mcp'] },
  { name: 'get_analytics', surfaces: ['agent', 'mcp'] },
  { name: 'get_approval_summary', surfaces: ['agent'] },
  { name: 'get_article', surfaces: ['mcp'] },
  { name: 'get_brand', surfaces: ['mcp'] },
  { name: 'get_brand_completeness', surfaces: ['agent', 'mcp'] },
  { name: 'get_clip_highlights', surfaces: ['mcp'] },
  { name: 'get_clip_project', surfaces: ['mcp'] },
  { name: 'get_connection_status', surfaces: ['agent'] },
  { name: 'get_content_analytics', surfaces: ['mcp'] },
  { name: 'get_content_calendar', surfaces: ['agent', 'mcp'] },
  { name: 'get_credits_balance', surfaces: ['agent', 'mcp'] },
  { name: 'get_current_brand', surfaces: ['agent'] },
  { name: 'get_dashboard_layout', surfaces: ['agent'] },
  { name: 'get_google_ads_adgroup_insights', surfaces: ['mcp'] },
  { name: 'get_google_ads_campaign_metrics', surfaces: ['mcp'] },
  { name: 'get_google_ads_keyword_performance', surfaces: ['mcp'] },
  { name: 'get_google_ads_search_terms', surfaces: ['mcp'] },
  { name: 'get_instagram_inspiration_detail', surfaces: ['agent', 'mcp'] },
  { name: 'get_job_status', surfaces: ['mcp'] },
  { name: 'get_linkedin_analytics', surfaces: ['mcp'] },
  { name: 'get_linkedin_connection_status', surfaces: ['mcp'] },
  { name: 'get_meta_ad_insights', surfaces: ['mcp'] },
  { name: 'get_meta_adset_insights', surfaces: ['mcp'] },
  { name: 'get_meta_campaign_insights', surfaces: ['mcp'] },
  { name: 'get_meta_top_performers', surfaces: ['mcp'] },
  { name: 'get_outreach_sequence_analytics', surfaces: ['agent'] },
  { name: 'get_scheduled_release', surfaces: ['mcp'] },
  { name: 'get_scheduler_capability', surfaces: ['mcp'] },
  { name: 'get_social_conversation', surfaces: ['mcp'] },
  { name: 'get_tiktok_campaign_insights', surfaces: ['mcp'] },
  { name: 'get_tiktok_top_performers', surfaces: ['mcp'] },
  { name: 'get_top_ingredients', surfaces: ['agent'] },
  { name: 'get_trends', surfaces: ['agent', 'mcp'] },
  { name: 'get_usage_stats', surfaces: ['mcp'] },
  { name: 'get_video_analytics', surfaces: ['mcp'] },
  { name: 'get_video_status', surfaces: ['mcp'] },
  { name: 'get_workflow_inputs', surfaces: ['agent'] },
  { name: 'get_workflow_run', surfaces: ['agent', 'mcp'] },
  { name: 'get_workflow_status', surfaces: ['mcp'] },
  { name: 'initiate_oauth_connect', surfaces: ['agent'] },
  { name: 'inspect_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'install_official_workflow', surfaces: ['agent'] },
  { name: 'install_skills_pro_skill', surfaces: ['mcp'] },
  { name: 'install_system_workflow', surfaces: ['agent', 'mcp'] },
  { name: 'list_ads_research', surfaces: ['agent', 'mcp'] },
  { name: 'list_agent_conversations', surfaces: ['agent'] },
  { name: 'list_avatars', surfaces: ['mcp'] },
  { name: 'list_brand_publishing_readiness', surfaces: ['mcp'] },
  { name: 'list_brands', surfaces: ['agent', 'mcp'] },
  { name: 'list_characters', surfaces: ['agent', 'mcp'] },
  { name: 'list_clip_projects', surfaces: ['mcp'] },
  { name: 'list_genfeed_tools', surfaces: ['agent'] },
  { name: 'list_google_ads_campaigns', surfaces: ['mcp'] },
  { name: 'list_google_ads_customers', surfaces: ['mcp'] },
  { name: 'list_images', surfaces: ['mcp'] },
  { name: 'list_instagram_inspiration', surfaces: ['agent', 'mcp'] },
  { name: 'list_meta_ad_accounts', surfaces: ['mcp'] },
  { name: 'list_meta_ad_creatives', surfaces: ['mcp'] },
  { name: 'list_meta_campaigns', surfaces: ['mcp'] },
  { name: 'list_music', surfaces: ['mcp'] },
  { name: 'list_posts', surfaces: ['agent', 'mcp'] },
  { name: 'list_review_queue', surfaces: ['agent'] },
  { name: 'list_scheduler_capabilities', surfaces: ['mcp'] },
  { name: 'list_social_conversations', surfaces: ['mcp'] },
  { name: 'list_system_workflow_catalog', surfaces: ['agent', 'mcp'] },
  { name: 'list_tiktok_ad_accounts', surfaces: ['mcp'] },
  { name: 'list_tiktok_adgroups', surfaces: ['mcp'] },
  { name: 'list_tiktok_ads', surfaces: ['mcp'] },
  { name: 'list_tiktok_campaigns', surfaces: ['mcp'] },
  { name: 'list_videos', surfaces: ['mcp'] },
  { name: 'list_workflow_runs', surfaces: ['agent', 'mcp'] },
  { name: 'list_workflow_templates', surfaces: ['mcp'] },
  { name: 'list_workflows', surfaces: ['agent', 'mcp'] },
  { name: 'list_x_account_activity', surfaces: ['agent', 'mcp'] },
  { name: 'manage_livestream_bot', surfaces: ['agent'] },
  { name: 'mark_social_conversation_resolved', surfaces: ['mcp'] },
  { name: 'open_studio_handoff', surfaces: ['agent'] },
  { name: 'pause_outreach_sequence', surfaces: ['agent'] },
  {
    isPublishingApprovalRequired: true,
    name: 'post_social_reply',
    surfaces: ['mcp'],
  },
  { name: 'prepare_ad_launch_review', surfaces: ['agent'] },
  { name: 'prepare_clip_workflow_run', surfaces: ['agent'] },
  { name: 'prepare_generation', surfaces: ['agent'] },
  { name: 'prepare_voice_clone', surfaces: ['agent'] },
  { name: 'prepare_workflow_trigger', surfaces: ['agent'] },
  { name: 'present_payment_options', surfaces: ['agent'] },
  { name: 'rate_content', surfaces: ['agent'] },
  { name: 'rate_ingredient', surfaces: ['agent'] },
  { name: 'reframe_image', surfaces: ['agent', 'mcp'] },
  { name: 'reject_social_draft', surfaces: ['mcp'] },
  { name: 'rename_brand', surfaces: ['agent'] },
  { name: 'render_dashboard', surfaces: ['agent'] },
  { name: 'replicate_top_ingredient', surfaces: ['agent'] },
  { name: 'repurpose_post', surfaces: ['agent', 'mcp'] },
  { name: 'request_asset', surfaces: ['agent'] },
  { name: 'resolve_approval', surfaces: ['mcp'] },
  { name: 'resolve_handle', surfaces: ['agent'] },
  { name: 'save_brand_voice_profile', surfaces: ['agent'] },
  { name: 'save_dashboard_layout', surfaces: ['agent'] },
  { name: 'schedule_post', surfaces: ['agent'] },
  { name: 'score_seo', surfaces: ['agent'] },
  { name: 'search_articles', surfaces: ['mcp'] },
  { name: 'search_x_posts', surfaces: ['agent', 'mcp'] },
  { name: 'select_ingredient', surfaces: ['agent'] },
  { name: 'send_chat_message', surfaces: ['mcp'] },
  {
    isPublishingApprovalRequired: true,
    name: 'send_social_dm',
    surfaces: ['mcp'],
  },
  { name: 'set_workflow_schedule', surfaces: ['agent', 'mcp'] },
  { name: 'skip_brand_interview_question', surfaces: ['agent', 'mcp'] },
  { name: 'spawn_content_agent', surfaces: ['agent'] },
  { name: 'start_brand_interview', surfaces: ['agent', 'mcp'] },
  { name: 'start_outreach_sequence', surfaces: ['agent'] },
  { name: 'submit_brand_interview_answer', surfaces: ['agent', 'mcp'] },
  { name: 'suggest_ingredient_alternatives', surfaces: ['agent'] },
  // Agent-only: renders conversational choices as in-product controls. MCP
  // clients own their own affordances and have no card surface to render into.
  { name: 'suggest_next_steps', surfaces: ['agent'] },
  { name: 'tag_social_conversation', surfaces: ['mcp'] },
  { name: 'transfer_agent_conversation', surfaces: ['agent'] },
  { name: 'update_goal', surfaces: ['agent'] },
  {
    isPublishingApprovalRequired: true,
    name: 'update_scheduled_release',
    surfaces: ['mcp'],
  },
  { name: 'update_strategy_state', surfaces: ['agent'] },
  { name: 'upscale_image', surfaces: ['agent', 'mcp'] },
  { name: 'validate_scheduler_target', surfaces: ['mcp'] },
  { name: 'verify_skills_pro_entitlement', surfaces: ['mcp'] },
] as const satisfies readonly CuratedActionCatalogEntry[];

export type CuratedActionName = (typeof CURATED_ACTION_CATALOG)[number]['name'];

const CURATED_ACTION_NAMES = new Set<string>(
  CURATED_ACTION_CATALOG.map((entry) => entry.name),
);

export function isCuratedActionName(value: string): value is CuratedActionName {
  return CURATED_ACTION_NAMES.has(value);
}

export function isActionOnSurface(
  entry: CuratedActionCatalogEntry,
  surface: CuratedActionSurface,
): boolean {
  return entry.surfaces.some((candidate) => candidate === surface);
}

export function isPublishingApprovalRequired(
  entry: CuratedActionCatalogEntry,
): boolean {
  return entry.isPublishingApprovalRequired === true;
}
