minimumReleaseAge: 10080
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - browser-tabs-lock
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
