import type { WorkflowTemplate } from '@genfeedai/types';

export const IMAGE_TO_VIDEO_TEMPLATE: WorkflowTemplate = {
  createdAt: new Date().toISOString(),
  description: 'Create interpolated video between two images with easing animation',
  edgeStyle: 'smoothstep',
  edges: [
    {
      id: 'e1',
      source: 'image-1',
      sourceHandle: 'image',
      target: 'videoGen-1',
      targetHandle: 'image',
    },
    {
      id: 'e2',
      source: 'image-2',
      sourceHandle: 'image',
      target: 'videoGen-1',
      targetHandle: 'lastFrame',
    },
    {
      id: 'e3',
      source: 'prompt-1',
      sourceHandle: 'text',
      target: 'videoGen-1',
      targetHandle: 'prompt',
    },
    {
      id: 'e4',
      source: 'videoGen-1',
      sourceHandle: 'video',
      target: 'animation-1',
      targetHandle: 'video',
    },
    {
      id: 'e5',
      source: 'animation-1',
      sourceHandle: 'video',
      target: 'output-1',
      targetHandle: 'video',
    },
  ],
  name: 'Image to Video',
  nodes: [
    {
      data: {
        dimensions: null,
        filename: null,
        image: null,
        label: 'Starting Frame',
        source: 'upload',
        status: 'idle',
      },
      id: 'image-1',
      position: { x: 50, y: 100 },
      type: 'imageInput',
    },
    {
      data: {
        dimensions: null,
        filename: null,
        image: null,
        label: 'Ending Frame',
        source: 'upload',
        status: 'idle',
      },
      id: 'image-2',
      position: { x: 50, y: 350 },
      type: 'imageInput',
    },
    {
      data: {
        label: 'Motion Description',
        prompt: 'Smooth cinematic transition with subtle camera movement',
        status: 'idle',
        variables: {},
      },
      id: 'prompt-1',
      position: { x: 50, y: 550 },
      type: 'prompt',
    },
    {
      data: {
        aspectRatio: '16:9',
        duration: 8,
        generateAudio: false,
        inputImage: null,
        inputPrompt: null,
        jobId: null,
        label: 'Video Generator',
        lastFrame: null,
        model: 'veo-3.1-fast',
        negativePrompt: 'blurry, distorted, artifacts',
        outputVideo: null,
        referenceImages: [],
        resolution: '1080p',
        status: 'idle',
      },
      id: 'videoGen-1',
      position: { x: 400, y: 200 },
      type: 'videoGen',
    },
    {
      data: {
        curveType: 'preset',
        customCurve: [0.645, 0.045, 0.355, 1],
        inputVideo: null,
        label: 'Ease Animation',
        outputVideo: null,
        preset: 'easeInOutCubic',
        speedMultiplier: 1,
        status: 'idle',
      },
      id: 'animation-1',
      position: { x: 750, y: 200 },
      type: 'animation',
    },
    {
      data: {
        inputMedia: null,
        inputType: 'video',
        label: 'Final Video',
        outputName: 'image-to-video',
        status: 'idle',
      },
      id: 'output-1',
      position: { x: 1100, y: 200 },
      type: 'download',
    },
  ],
  updatedAt: new Date().toISOString(),
  version: 1,
};
