export type CinematicLexiconCategory =
  | 'camera-movement'
  | 'framing-composition'
  | 'lighting'
  | 'editing-transitions'
  | 'stylistic-effects';

export interface CinematicTechnique {
  aliases: readonly string[];
  category: CinematicLexiconCategory;
  definition: string;
  name: string;
  whenToUse: string;
}

function technique(
  category: CinematicLexiconCategory,
  name: string,
  definition: string,
  whenToUse: string,
  aliases: readonly string[] = [],
): CinematicTechnique {
  return { aliases, category, definition, name, whenToUse };
}

export const CINEMATIC_LEXICON: readonly CinematicTechnique[] = [
  // Camera movement
  technique(
    'camera-movement',
    'dolly in',
    'The camera physically travels toward the subject on a track or slider, keeping focal length fixed.',
    'Use when intimacy or pressure should grow without changing perspective distortion.',
    ['moves toward', 'moves towards', 'camera moves toward', 'camera toward'],
  ),
  technique(
    'camera-movement',
    'dolly out',
    'The camera physically retreats from the subject while the lens stays the same.',
    'Use to reveal context around a character or to drain intensity from a beat.',
    ['pulls away', 'moves away from'],
  ),
  technique(
    'camera-movement',
    'push-in',
    'A short, deliberate advance toward the subject that lands on a tighter frame.',
    'Use to underline a realization, threat, or emotional turn.',
    ['slowly toward', 'slow push'],
  ),
  technique(
    'camera-movement',
    'pull-out',
    'A short retreat that widens the frame and reintroduces surrounding space.',
    'Use after a close beat when the scene needs air or scale.',
  ),
  technique(
    'camera-movement',
    'trucking left',
    'The camera travels laterally left, parallel to the action, without rotating.',
    'Use to keep pace with a walk-and-talk or a moving vehicle.',
  ),
  technique(
    'camera-movement',
    'trucking right',
    'The camera travels laterally right, parallel to the action, without rotating.',
    'Use to follow a crossing subject while holding a consistent profile.',
  ),
  technique(
    'camera-movement',
    'pedestal up',
    'The camera rises vertically on a column or crane while remaining level.',
    'Use to lift from a grounded detail to a standing figure or room.',
  ),
  technique(
    'camera-movement',
    'pedestal down',
    'The camera lowers vertically while staying level.',
    'Use to drop from a face to hands, objects, or a floor-level clue.',
  ),
  technique(
    'camera-movement',
    'pan',
    'The camera rotates horizontally from a fixed position.',
    'Use to survey a space or follow a subject that does not require a traveling camera.',
  ),
  technique(
    'camera-movement',
    'tilt',
    'The camera rotates vertically from a fixed position.',
    'Use to reveal height, a body from shoes to face, or a building from street to sky.',
  ),
  technique(
    'camera-movement',
    'whip pan',
    'A pan so fast that frames smear into a directional blur.',
    'Use as an energetic connector between two related beats in the same location.',
    ['fast pan', 'swish pan'],
  ),
  technique(
    'camera-movement',
    'arc shot',
    'The camera travels a curved path around the subject, usually at a constant radius.',
    'Use to inspect a character or object from multiple sides without cutting.',
    ['spin around', 'circles around', 'circle around'],
  ),
  technique(
    'camera-movement',
    'orbit',
    'A continuous 360-degree or near-360 path around the subject.',
    'Use for hero reveals, product turnarounds, and hypnotic character moments.',
    ['spins around', '360 around'],
  ),
  technique(
    'camera-movement',
    'crane shot',
    'The camera rides a boom through a large vertical and horizontal path.',
    'Use to open or close a scene with geography, crowd scale, or a descending arrival.',
  ),
  technique(
    'camera-movement',
    'jib sweep',
    'A shorter boom move that scoops or arcs across a compact set.',
    'Use when a full crane is too large but the shot still needs aerial grace.',
  ),
  technique(
    'camera-movement',
    'steadicam follow',
    'A stabilized operator walk that floats behind, beside, or ahead of the subject.',
    'Use for long takes through architecture or crowds without handheld shake.',
  ),
  technique(
    'camera-movement',
    'tracking shot',
    'The camera travels with the subject, matching speed and direction.',
    'Use whenever motion itself is the story and cutting would break the line.',
    ['follows', 'following shot'],
  ),
  technique(
    'camera-movement',
    'handheld',
    'The camera is operator-held, admitting micro-shake and human weight shifts.',
    'Use for urgency, documentary texture, or a character whose world is unstable.',
  ),
  technique(
    'camera-movement',
    'locked-off',
    'The camera is fixed on a tripod or mount with no pan, tilt, or travel.',
    'Use for graphic compositions, comedy deadpan, and surveillance-like observation.',
    ['static camera', 'locked off', 'tripod locked'],
  ),
  technique(
    'camera-movement',
    'roll',
    'The camera rotates on its lens axis so the horizon banks.',
    'Use sparingly for disorientation, aircraft, or a world coming unmoored.',
  ),
  technique(
    'camera-movement',
    'FPV drone',
    'A first-person racing-drone path that weaves through tight architecture at speed.',
    'Use when the audience should feel like a projectile through a space.',
    ['drone flythrough', 'fpv'],
  ),
  technique(
    'camera-movement',
    'snorricam',
    'A body-mounted camera that keeps the subject locked while the world slides behind them.',
    'Use for dissociation, panic, or a character sealed inside their own head.',
  ),
  technique(
    'camera-movement',
    'speed ramp',
    'Playback speed changes mid-shot, usually from real time into slow or back out.',
    'Use to isolate a gesture, impact, or glance without cutting.',
    ['ramps to slow motion', 'speed ramps'],
  ),
  technique(
    'camera-movement',
    'slow motion',
    'Action is captured or played back well below real-time speed.',
    'Use to ritualize violence, beauty, or a walk that should feel mythic.',
    ['in slow motion', 'slow-mo', 'slo-mo'],
  ),
  technique(
    'camera-movement',
    'time-lapse',
    'Frames are captured at long intervals so hours compress into seconds.',
    'Use for weather, crowds, construction, or the passage of a day over a place.',
  ),
  technique(
    'camera-movement',
    'dolly zoom',
    'The camera dollies while the lens zooms the opposite way, warping perspective around a still subject.',
    'Use for vertigo, dread, or a sudden rewrite of how the character sees the world.',
    ['vertigo shot', 'zolly'],
  ),

  // Framing / composition
  technique(
    'framing-composition',
    'extreme close-up',
    'A frame that fills with one feature — an eye, a mouth, a ring, a trigger.',
    'Use when a tiny detail carries the scene’s meaning.',
    ['ecu', 'macro on'],
  ),
  technique(
    'framing-composition',
    'close-up',
    'Head and shoulders, or an object large enough to read emotion or texture.',
    'Use for dialogue beats, identity, and reaction.',
    ['close on', 'closeup', 'close up', 'tight on'],
  ),
  technique(
    'framing-composition',
    'medium close-up',
    'Chest-up framing that keeps face and a hint of gesture.',
    'Use as the default interview and conversation size.',
  ),
  technique(
    'framing-composition',
    'medium shot',
    'Waist-up framing that balances body language with environment.',
    'Use for blocking, props in hand, and two-person exchanges.',
  ),
  technique(
    'framing-composition',
    'cowboy shot',
    'Mid-thigh up, historically so a holster stays in frame.',
    'Use for armed or swaggering figures who need stance as well as face.',
  ),
  technique(
    'framing-composition',
    'full shot',
    'The entire body from head to toe with a modest amount of ground and headroom.',
    'Use when costume, gait, or full-body silhouette matters.',
    ['full body', 'full-body'],
  ),
  technique(
    'framing-composition',
    'wide shot',
    'The subject is small enough that architecture and geography share the frame.',
    'Use to locate people in a place before tightening.',
    ['wide', 'wide angle of', 'a wide of'],
  ),
  technique(
    'framing-composition',
    'extreme wide shot',
    'A landscape-scale frame where figures are tiny or absent.',
    'Use as an establishing image that sells climate, city, or isolation.',
    ['establishing shot', 'establishing'],
  ),
  technique(
    'framing-composition',
    'ultra wide',
    'An extremely short focal length that stretches space and exaggerates near objects.',
    'Use for immersive interiors, skate, or a slightly unhinged point of view.',
    ['ultrawide', 'ultra-wide'],
  ),
  technique(
    'framing-composition',
    'two shot',
    'Two people share the frame at roughly equal weight.',
    'Use for relationships, arguments, and paired presence.',
    ['two-shot', 'two shot of', 'both in frame'],
  ),
  technique(
    'framing-composition',
    'over-the-shoulder',
    'The camera looks past one person’s shoulder and cheek onto the facing subject.',
    'Use for conversation coverage that keeps both parties connected.',
    ['ots', 'over the shoulder'],
  ),
  technique(
    'framing-composition',
    'point of view',
    'The frame is what a character sees, including blink, height, and obstruction.',
    'Use to lock the audience into one person’s perception.',
    ['pov', "character's view"],
  ),
  technique(
    'framing-composition',
    'dutch angle',
    'The horizon is canted so verticals lean.',
    'Use for unease, intoxication, or a world whose rules have slipped.',
    ['dutch tilt', 'canted angle'],
  ),
  technique(
    'framing-composition',
    'high-angle shot',
    'The camera looks down at the subject from above eye level.',
    'Use to shrink a character, survey a table, or read a floor plan of action.',
    ['from above', 'looking down', 'shot from above', 'high angle'],
  ),
  technique(
    'framing-composition',
    'low-angle shot',
    'The camera looks up at the subject from below eye level.',
    'Use to enlarge power, monumentality, or menace.',
    ['from below', 'looking up', 'low angle'],
  ),
  technique(
    'framing-composition',
    "worm's-eye",
    'An extreme low angle from ground level, often with sky or ceiling dominating.',
    'Use when the world should tower over the viewer.',
    ['worms-eye', "worm's eye", 'ground level looking up'],
  ),
  technique(
    'framing-composition',
    'overhead shot',
    'A top-down frame perpendicular to the floor, sometimes called bird’s-eye.',
    'Use for maps of movement, ritual layouts, and graphic tableaus.',
    ["bird's-eye", 'birds-eye', 'top down', 'top-down', 'from directly above'],
  ),
  technique(
    'framing-composition',
    'central framing',
    'The subject sits on the optical center, often with symmetry around them.',
    'Use for portraits of control, ceremony, and Wes-Anderson-like order.',
    ['centered', 'dead center', 'symmetrical framing'],
  ),
  technique(
    'framing-composition',
    'rule of thirds',
    'Key masses sit on the intersections of a three-by-three grid.',
    'Use as a default for landscapes and talking heads that should feel natural.',
  ),
  technique(
    'framing-composition',
    'leading lines',
    'Architecture, roads, or light beams steer the eye to the subject.',
    'Use when a location can point at the character without extra camera work.',
  ),
  technique(
    'framing-composition',
    'negative space',
    'A large empty field around a small subject.',
    'Use for loneliness, waiting, or a title-safe graphic beat.',
  ),
  technique(
    'framing-composition',
    'frame within a frame',
    'Doorways, windows, mirrors, or screens crop a second picture inside the shot.',
    'Use to trap a character, spy on them, or stack two story worlds.',
  ),
  technique(
    'framing-composition',
    'profile shot',
    'The subject is seen from the side, silhouetting nose, brow, and posture.',
    'Use for confrontations, cameos against windows, and non-humanoid identity sheets.',
    ['side profile', 'in profile'],
  ),
  technique(
    'framing-composition',
    'three-quarter view',
    'The face or body is turned about 45 degrees from the camera.',
    'Use as the most dimensional default for portraits and product heroes.',
  ),
  technique(
    'framing-composition',
    'insert shot',
    'A brief close view of a relevant object or action detail.',
    'Use to plant a clue, a text, a button press, or a ticking clock.',
  ),
  technique(
    'framing-composition',
    'cutaway',
    'A shot of something other than the main action, used to bridge or comment.',
    'Use to hide an edit, show reaction in the room, or add documentary evidence.',
  ),

  // Lighting
  technique(
    'lighting',
    'hard light',
    'A small, sharp source that throws crisp shadows and specular hits.',
    'Use for noon sun, interrogation, and graphic contrast.',
    ['harsh light', 'sharp shadows', 'hard shadows'],
  ),
  technique(
    'lighting',
    'soft light',
    'A large, diffused source that wraps the subject and melts shadow edges.',
    'Use for beauty, overcast days, and gentle interiors.',
    ['soft lighting', 'diffused light', 'gentle light'],
  ),
  technique(
    'lighting',
    'high-key',
    'A bright, low-contrast scheme with open shadows and pale backgrounds.',
    'Use for comedy, retail, wellness, and optimistic advertising.',
    ['bright and airy', 'high key'],
  ),
  technique(
    'lighting',
    'low-key',
    'A dark scheme that withholds fill so most of the frame falls toward black.',
    'Use for mystery, night, and anything described as moody or dramatic.',
    ['moody', 'dark and moody', 'in the dark', 'dim lighting'],
  ),
  technique(
    'lighting',
    'Rembrandt lighting',
    'Key light at 45 degrees that leaves a triangle of light on the shadowed cheek.',
    'Use for classical portraits that need both shape and dignity.',
  ),
  technique(
    'lighting',
    'butterfly lighting',
    'A key placed on axis above the lens, dropping a butterfly-shaped shadow under the nose.',
    'Use for glamour portraits and beauty campaigns.',
  ),
  technique(
    'lighting',
    'split lighting',
    'The key hits one half of the face; the other half falls into shadow.',
    'Use for duality, moral conflict, and severe character studies.',
  ),
  technique(
    'lighting',
    'rim light',
    'A backlight that traces the subject’s edge with a thin highlight.',
    'Use to separate dark hair or clothing from a dark background.',
    ['hair light', 'edge light', 'kicker'],
  ),
  technique(
    'lighting',
    'backlight',
    'The primary source sits behind the subject, toward the camera.',
    'Use for halos, rain sparkle, and subjects defined by silhouette plus glow.',
  ),
  technique(
    'lighting',
    'silhouette',
    'The subject is underexposed against a brighter background so only the outline reads.',
    'Use for identity-as-shape, sunsets, and anonymous figures.',
    ['silhouetted', 'as a silhouette'],
  ),
  technique(
    'lighting',
    'practicals',
    'Lamps, neon, screens, and other sources that exist in the set and are photographed on.',
    'Use to motivate night interiors and keep light grounded in the world.',
    ['practical lighting', 'lamps in frame'],
  ),
  technique(
    'lighting',
    'motivated lighting',
    'Off-camera units that pretend to be a visible source such as a window or sign.',
    'Use whenever the audience should believe the light belongs to the location.',
  ),
  technique(
    'lighting',
    'golden hour',
    'The low, warm sun shortly after dawn or before dusk.',
    'Use for romance, travel, and any prompt that mentions sunset or sunrise.',
    ['sunset', 'sunrise', 'sunset light', 'golden sunlight'],
  ),
  technique(
    'lighting',
    'blue hour',
    'The cool, even skylight just before sunrise or after sunset.',
    'Use for city lights mixing with residual daylight and quiet melancholy.',
    ['twilight', 'dusk blue'],
  ),
  technique(
    'lighting',
    'overcast',
    'Cloud-diffused daylight that acts like a giant softbox.',
    'Use for even skin, documentary honesty, and outdoor product shots.',
  ),
  technique(
    'lighting',
    'spotlight',
    'A focused cone that isolates one subject from a darker surround.',
    'Use for stages, interrogations, and single-object hero moments.',
    ['spot lit', 'in a spotlight'],
  ),
  technique(
    'lighting',
    'chiaroscuro',
    'Painting-like contrast of a few lit planes against deep shadow.',
    'Use when “dramatic” should mean sculpted light, not just darkness.',
    ['dramatic lighting', 'dramatic', 'painterly contrast'],
  ),
  technique(
    'lighting',
    'bounce fill',
    'Light redirected from a wall, card, or ceiling to lift shadows without a second hard source.',
    'Use to keep a key dramatic while still reading eyes and wardrobe.',
  ),
  technique(
    'lighting',
    'haze',
    'Airborne scatter that makes beams visible and softens distant contrast.',
    'Use for shafts through windows, clubs, forests, and dream distance.',
    ['atmospheric haze', 'foggy air', 'misty interior', 'like a dream'],
  ),
  technique(
    'lighting',
    'halation',
    'Highlights bloom and bleed, as if the emulsion cannot contain them.',
    'Use for analog warmth, night neon, and memory.',
  ),
  technique(
    'lighting',
    'neon practicals',
    'Colored tube or LED signage that both keys the scene and paints the set.',
    'Use for nightlife, rain streets, and cyber or retro-future looks.',
    ['neon', 'neon lights'],
  ),
  technique(
    'lighting',
    'window light',
    'A single large opening that keys the subject from one side.',
    'Use for interiors that should feel observed rather than lit.',
  ),
  technique(
    'lighting',
    'top light',
    'A source directly above, pooling on shoulders and burying the eyes.',
    'Use for menace, factory floors, and interrogation rooms.',
  ),
  technique(
    'lighting',
    'underlighting',
    'A source from below the face, inverting the usual daylight pattern.',
    'Use for campfire stories, horror, and unnatural presence.',
    ['lit from below', 'uplighting'],
  ),
  technique(
    'lighting',
    'volumetric light',
    'Visible beams carved through haze, dust, or smoke.',
    'Use when the air itself should feel thick and directional.',
    ['god rays', 'light shafts', 'crepuscular rays'],
  ),

  // Editing / transitions
  technique(
    'editing-transitions',
    'match cut',
    'Two shots join because shape, motion, or idea continues across the cut.',
    'Use to rhyme images and collapse time without a dissolve.',
  ),
  technique(
    'editing-transitions',
    'jump cut',
    'A cut within the same setup that skips time and makes the subject pop.',
    'Use for restlessness, montage of process, or a narrator talking to camera.',
    ['cut quickly', 'quick cuts', 'jumpy cuts'],
  ),
  technique(
    'editing-transitions',
    'smash cut',
    'An abrupt join between two shots of maximally different energy or volume.',
    'Use to jolt from quiet to loud or from dream to alarm.',
    ['smash to', 'abrupt cut'],
  ),
  technique(
    'editing-transitions',
    'crash cut',
    'A violent, almost colliding join used as a rhythmic punch.',
    'Use in action and music video when the beat itself is the cut.',
  ),
  technique(
    'editing-transitions',
    'cross dissolve',
    'One image fades in as the other fades out, overlapping in time.',
    'Use for memory, elapsed time, or a gentle change of place.',
    ['dissolve', 'crossfade'],
  ),
  technique(
    'editing-transitions',
    'fade to black',
    'The image decays to black, ending a chapter.',
    'Use at act breaks and deaths, never between ordinary coverage.',
  ),
  technique(
    'editing-transitions',
    'fade from black',
    'The image is born out of black.',
    'Use to open a new chapter or a morning after.',
  ),
  technique(
    'editing-transitions',
    'whip-pan transition',
    'A whip pan’s blur is used as the join to another whip pan.',
    'Use to stitch two locations that share momentum.',
  ),
  technique(
    'editing-transitions',
    'L-cut',
    'Picture cuts away while the outgoing audio continues.',
    'Use so dialogue or score can pull the viewer into the next image.',
  ),
  technique(
    'editing-transitions',
    'J-cut',
    'Incoming audio arrives before the picture of the next shot.',
    'Use to pre-lap a new space, a voice, or a threat.',
  ),
  technique(
    'editing-transitions',
    'montage',
    'A designed sequence of short shots that compresses process or argument.',
    'Use for training, travel, and any “time passed” that needs rhythm.',
  ),
  technique(
    'editing-transitions',
    'parallel action',
    'Two or more lines of action intercut so they feel simultaneous.',
    'Use for chases, countdowns, and destinies that are about to collide.',
    ['cross cutting', 'intercut'],
  ),
  technique(
    'editing-transitions',
    'cross cut',
    'Alternating shots from two scenes to build comparison or suspense.',
    'Use when the audience should hold two places in mind at once.',
  ),
  technique(
    'editing-transitions',
    'freeze frame',
    'Motion stops on a still that is held as a graphic.',
    'Use for endings, evidence, or a joke that needs a button.',
  ),
  technique(
    'editing-transitions',
    'iris',
    'A circular mask closes or opens on a point of interest.',
    'Use for period pastiche and to single out a clue.',
  ),
  technique(
    'editing-transitions',
    'wipe',
    'A traveling edge replaces one shot with another.',
    'Use for serial adventure, chaptering, and graphic play.',
  ),
  technique(
    'editing-transitions',
    'cut on action',
    'The join happens during a continuous gesture so the motion hides the cut.',
    'Use as the default invisible way to change size or angle.',
  ),
  technique(
    'editing-transitions',
    'axial cut',
    'A cut along the lens axis, jumping closer or farther without changing angle.',
    'Use for emphasis that still feels like the same point of view.',
  ),
  technique(
    'editing-transitions',
    'smash cut to silence',
    'A loud or busy shot cuts to a still, quiet image.',
    'Use after an explosion, a scream, or a party to make absence felt.',
  ),
  technique(
    'editing-transitions',
    'match on motion',
    'The direction and speed of movement continue across a cut into a new space.',
    'Use to teleport a character while keeping kinetic logic.',
  ),

  // Stylistic effects
  technique(
    'stylistic-effects',
    'bullet time',
    'Time appears frozen or slowed while the camera still travels around the subject.',
    'Use for iconic action punctuation, not as a default look.',
  ),
  technique(
    'stylistic-effects',
    'double exposure',
    'Two images occupy the same frame, stacked by opacity or blend.',
    'Use for memory, haunting, and interior states.',
    ['overlaid images', 'ghost overlay'],
  ),
  technique(
    'stylistic-effects',
    'tilt-shift',
    'Selective focus and often a miniature-like perspective.',
    'Use to make a city look like a model or to isolate a thin plane of sharpness.',
    ['tilt shift', 'miniature look'],
  ),
  technique(
    'stylistic-effects',
    'thermal',
    'A false-color heat map instead of reflected light.',
    'Use for night search, science fiction sensors, and animal vision.',
    ['heat vision', 'infrared thermal'],
  ),
  technique(
    'stylistic-effects',
    'anamorphic flare',
    'Horizontal streaks from a bright source, characteristic of anamorphic glass.',
    'Use for widescreen cinema texture and night headlights.',
    ['anamorphic', 'horizontal flare'],
  ),
  technique(
    'stylistic-effects',
    'film grain',
    'Visible silver or digital grain structure over the image.',
    'Use to age a picture, hide digital smoothness, or match analog references.',
  ),
  technique(
    'stylistic-effects',
    'teal-and-orange grade',
    'Shadows push cyan-teal while skin and practicals hold orange.',
    'Use as a contemporary blockbuster color contrast, not a default for every scene.',
    ['teal and orange', 'blockbuster grade'],
  ),
  technique(
    'stylistic-effects',
    'bleach bypass',
    'A desaturated, silver-heavy look with crushed blacks and retained density.',
    'Use for war, crime, and moral exhaustion.',
  ),
  technique(
    'stylistic-effects',
    'lens flare',
    'Internal glass reflections from a source in or near the frame.',
    'Use when the sun or headlights should invade the lens, sparingly.',
  ),
  technique(
    'stylistic-effects',
    'bokeh',
    'Out-of-focus highlights rendered as discs or polygons.',
    'Use to romanticize night cities and isolate a subject from sparkle.',
    ['blurry lights', 'background orbs'],
  ),
  technique(
    'stylistic-effects',
    'shallow depth of field',
    'Only a thin plane is sharp; foreground and background fall off quickly.',
    'Use for portraits, product heroes, and any “blurry background” request.',
    ['blurry background', 'blurred background', 'out of focus background'],
  ),
  technique(
    'stylistic-effects',
    'deep focus',
    'Near and far planes are simultaneously sharp.',
    'Use when blocking in depth is the composition, from foreground prop to distant door.',
  ),
  technique(
    'stylistic-effects',
    'rack focus',
    'Focus travels from one plane to another during the shot.',
    'Use to hand attention from a face to a clue, or from a gun to a reaction.',
    ['focus pull', 'pull focus'],
  ),
  technique(
    'stylistic-effects',
    'glitch',
    'Digital tearing, channel offset, and compression wounds used as style.',
    'Use for hacked feeds, broken memory, and electronic unease.',
  ),
  technique(
    'stylistic-effects',
    'vignette',
    'The corners darken or desaturate, pooling attention in the center.',
    'Use to age a lens, hide edges, or intensify a portrait.',
  ),
  technique(
    'stylistic-effects',
    'motion blur',
    'Moving masses streak according to shutter angle.',
    'Use to sell speed; avoid it when the brief wants razor-frozen action.',
  ),
  technique(
    'stylistic-effects',
    'light leak',
    'Streaks and veils of unexposed-looking color invading the frame.',
    'Use for analog accident, summer memory, and super-8 pastiche.',
  ),
  technique(
    'stylistic-effects',
    'infrared',
    'Foliage goes pale, skies go dark, and skin tones shift into an otherworldly register.',
    'Use for dream forests, surveillance, and uncanny daylight.',
  ),
  technique(
    'stylistic-effects',
    'chromatic aberration',
    'Color channels misregister at high-contrast edges.',
    'Use lightly for cheap optics, VR, or a world slightly out of calibration.',
    ['color fringing'],
  ),
  technique(
    'stylistic-effects',
    'split diopter',
    'A half-lens that holds two different focus distances sharp in one frame.',
    'Use for two-plane tension without racking focus.',
  ),
  technique(
    'stylistic-effects',
    'day for night',
    'Daylight is underexposed and cooled to stand in for night.',
    'Use when true night capture is impractical; keep skies dark and highlights restrained.',
  ),
];

export const CINEMATIC_TECHNIQUE_NAMES: readonly string[] =
  CINEMATIC_LEXICON.map((entry) => entry.name);
