import { buildArtifactContentDigest } from '@api/agent-artifacts/agent-artifact-material.util';
import {
  hashBrandedGenerationArtifactManifestV1,
  hashBrandedGenerationTextV1,
} from '@api/services/branded-generation-receipts/branded-generation-hash.util';
import type {
  BrandedGenerationActorV1,
  BrandedGenerationArtifactBindingV1,
} from '@api/services/branded-generation-receipts/branded-generation-receipts.types';
import {
  IngredientCategory,
  PostCategory,
  PostFormat,
} from '@genfeedai/contracts';
import type { LearningFormat } from '@genfeedai/contracts/interfaces/analytics/content-learning.interface';
import type { BrandGenerationArtifactV1 } from '@genfeedai/contracts/interfaces/content/branded-generation.interface';
import type { Prisma } from '@genfeedai/prisma';
import { STORAGE_READ_MAX_BYTES } from '@genfeedai/storage';
import { BadRequestException, ConflictException } from '@nestjs/common';

const ingredientSelect = {
  id: true,
  organizationId: true,
  brandId: true,
  isDeleted: true,
  category: true,
  s3Key: true,
  version: true,
  mimeType: true,
  fileSize: true,
  cdnUrl: true,
} satisfies Prisma.IngredientSelect & { cdnUrl?: boolean }; // cdnUrl is a Prisma result extension
const segmentSelect = {
  id: true,
  organizationId: true,
  brandId: true,
  isDeleted: true,
  parentId: true,
  order: true,
  platform: true,
  credentialId: true,
  category: true,
  format: true,
  description: true,
  targetAttachments: true,
  targetSettings: true,
  ingredients: {
    select: ingredientSelect,
    orderBy: { id: 'asc' as const },
    take: 9,
  },
} satisfies Prisma.PostSelect;
export const brandedPostMaterialSelect = {
  ...segmentSelect,
  children: {
    where: { isDeleted: false },
    orderBy: [{ order: 'asc' as const }, { id: 'asc' as const }],
    take: 9,
    select: { ...segmentSelect, children: { select: { id: true }, take: 1 } },
  },
} satisfies Prisma.PostSelect;
type PostMaterialPayload = Prisma.PostGetPayload<{
  select: typeof brandedPostMaterialSelect;
}>;
/** `cdnUrl` is a Prisma result extension, so the static payload types it as `never`. */
type WithMediaUrl<Row> = Omit<Row, 'cdnUrl'> & { cdnUrl: string | null };
type PostMaterialSegment = Omit<
  PostMaterialPayload,
  'children' | 'ingredients'
> & {
  ingredients: Array<WithMediaUrl<PostMaterialPayload['ingredients'][number]>>;
};
export type BrandedPostMaterialRecord = PostMaterialSegment & {
  children: Array<
    Omit<PostMaterialPayload['children'][number], 'children' | 'ingredients'> &
      Pick<PostMaterialPayload['children'][number], 'children'> & {
        ingredients: Array<
          WithMediaUrl<
            PostMaterialPayload['children'][number]['ingredients'][number]
          >
        >;
      }
  >;
};
export type BrandedPostMaterialEntry =
  | { kind: 'media'; id: string; role: 'image' | 'video' }
  | {
      kind: 'text';
      id: string;
      role: 'text';
      bytes: Uint8Array;
      version: string;
      contentHash: string;
    };
export interface BrandedPostMaterialLayout {
  postId: string;
  format: LearningFormat;
  mediaKind: BrandGenerationArtifactV1['mediaKind'];
  textBytes: Uint8Array | null;
  textHash: string | null;
  layoutDigest: string;
  legacyTextIdentity: boolean;
  entries: BrandedPostMaterialEntry[];
}

/** Canonical content only: scheduling/review metadata does not change generated bytes. */
export function describeBrandedPostMaterialLayout(
  actor: Readonly<Pick<BrandedGenerationActorV1, 'organizationId' | 'brandId'>>,
  post: Readonly<BrandedPostMaterialRecord>,
): BrandedPostMaterialLayout {
  if (post.parentId !== null || post.children.length > 8)
    throw new BadRequestException('receipt_artifact_unsupported');
  const segments = [
    post,
    ...[...post.children].sort(
      (left, right) =>
        left.order - right.order || left.id.localeCompare(right.id),
    ),
  ];
  const orders = new Set<number>();
  const ids = new Set<string>();
  const entries: BrandedPostMaterialEntry[] = [];
  const mediaRoles = new Map<string, 'image' | 'video'>();
  const thread = post.format === PostFormat.THREAD || post.children.length > 0;
  let textSize = Buffer.byteLength(post.description);
  if (textSize > STORAGE_READ_MAX_BYTES)
    throw new BadRequestException('receipt_material_limit_exceeded');
  for (const segment of segments) {
    if (
      segment.organizationId !== actor.organizationId ||
      segment.brandId !== actor.brandId ||
      segment.isDeleted ||
      segment.platform !== post.platform ||
      segment.credentialId !== post.credentialId ||
      (segment !== post && segment.parentId !== post.id)
    )
      throw new BadRequestException('receipt_artifact_unsupported');
    if (ids.has(segment.id) || segment.ingredients.length > 8)
      throw new BadRequestException('receipt_artifact_unsupported');
    ids.add(segment.id);
    if (segment !== post) {
      if (
        !Number.isSafeInteger(segment.order) ||
        segment.order < 0 ||
        orders.has(segment.order) ||
        ('children' in segment && segment.children.length > 0)
      )
        throw new BadRequestException('receipt_artifact_unsupported');
      orders.add(segment.order);
      if (segment.description) {
        textSize += Buffer.byteLength(segment.description);
        if (textSize > STORAGE_READ_MAX_BYTES)
          throw new BadRequestException('receipt_material_limit_exceeded');
        const hash = hashBrandedGenerationTextV1(segment.description);
        entries.push({
          kind: 'text',
          id: `post-text:${segment.id}`,
          role: 'text',
          bytes: Buffer.from(segment.description),
          version: hash,
          contentHash: hash,
        });
      }
    }
    if (!segment.description && segment.ingredients.length === 0)
      throw new BadRequestException('receipt_artifact_unsupported');
    const attachments = segment.targetAttachments;
    if (attachments !== null && !Array.isArray(attachments))
      throw new BadRequestException('receipt_artifact_unsupported');
    let ingredients = [...segment.ingredients];
    if (Array.isArray(attachments) && attachments.length > 0) {
      if (
        attachments.length !== ingredients.length ||
        new Set(attachments).size !== attachments.length
      )
        throw new BadRequestException('receipt_artifact_unsupported');
      const ordered = attachments.map((url) => {
        const matches = ingredients.filter((item) => item.cdnUrl === url);
        if (typeof url !== 'string' || matches.length !== 1)
          throw new BadRequestException('receipt_artifact_unsupported');
        return matches[0];
      });
      ingredients = ordered;
    }
    for (const ingredient of ingredients) {
      const role = [
        IngredientCategory.IMAGE,
        IngredientCategory.IMAGE_EDIT,
      ].some((value) => value === ingredient.category)
        ? 'image'
        : [IngredientCategory.VIDEO, IngredientCategory.VIDEO_EDIT].some(
              (value) => value === ingredient.category,
            )
          ? 'video'
          : null;
      if (
        !role ||
        !ingredient.s3Key ||
        ingredient.isDeleted ||
        ingredient.organizationId !== actor.organizationId ||
        ingredient.brandId !== actor.brandId
      )
        throw new BadRequestException('receipt_artifact_unsupported');
      const previous = mediaRoles.get(ingredient.s3Key);
      if (previous && previous !== role)
        throw new BadRequestException('receipt_artifact_unsupported');
      if (!previous)
        entries.push({ kind: 'media', id: ingredient.s3Key, role });
      mediaRoles.set(ingredient.s3Key, role);
    }
  }
  if (entries.length > 8)
    throw new BadRequestException('receipt_material_limit_exceeded');
  const video = entries.some((entry) => entry.role === 'video');
  const images = entries.filter((entry) => entry.role === 'image').length;
  const rootImages = post.ingredients.filter((ingredient) =>
    [IngredientCategory.IMAGE, IngredientCategory.IMAGE_EDIT].some(
      (value) => value === ingredient.category,
    ),
  ).length;
  const format: LearningFormat = thread
    ? 'thread'
    : post.category === PostCategory.REEL
      ? 'short'
      : video
        ? 'video'
        : rootImages > 1
          ? 'carousel'
          : images === 1
            ? 'image'
            : 'text';
  if ((format === 'short' || post.category === PostCategory.VIDEO) && !video)
    throw new BadRequestException('receipt_artifact_unsupported');
  if (
    [PostCategory.IMAGE, PostCategory.STORY].some(
      (value) => value === post.category,
    ) &&
    images === 0
  )
    throw new BadRequestException('receipt_artifact_unsupported');
  const textBytes = post.description ? Buffer.from(post.description) : null;
  const textHash = post.description
    ? hashBrandedGenerationTextV1(post.description)
    : null;
  if (!textBytes && !video && !images)
    throw new BadRequestException('receipt_artifact_unsupported');
  return {
    postId: post.id,
    format,
    mediaKind: video ? 'video' : images ? 'image' : 'text',
    textBytes,
    textHash,
    entries,
    legacyTextIdentity: segments.every(
      (segment) =>
        (!Array.isArray(segment.targetAttachments) ||
          segment.targetAttachments.length === 0) &&
        (segment.targetSettings === null ||
          (typeof segment.targetSettings === 'object' &&
            !Array.isArray(segment.targetSettings) &&
            Object.keys(segment.targetSettings).length === 0)),
    ),
    layoutDigest: buildArtifactContentDigest({
      format,
      segments: segments.map((segment) => ({
        id: segment.id,
        order: segment.order,
        description: segment.description,
        category: segment.category,
        format: segment.format,
        ingredients: segment.ingredients,
        targetAttachments: segment.targetAttachments,
        targetSettings: segment.targetSettings,
      })),
    }),
  };
}

export function bindBrandedPostMaterialLayout(
  layout: Readonly<BrandedPostMaterialLayout>,
  parts: BrandGenerationArtifactV1['parts'],
): BrandedGenerationArtifactBindingV1 {
  if (
    parts.length !== layout.entries.length ||
    parts.some((part, index) => {
      const entry = layout.entries[index];
      return (
        part.id !== entry.id ||
        part.role !== entry.role ||
        (entry.kind === 'text' &&
          (part.version !== entry.version ||
            part.contentHash !== entry.contentHash))
      );
    })
  )
    throw new ConflictException('receipt_artifact_version_mismatch');
  const contentHash = hashBrandedGenerationArtifactManifestV1({
    mediaKind: layout.mediaKind,
    textHash: layout.textHash,
    parts,
  });
  return {
    artifact: {
      kind: 'post',
      id: layout.postId,
      mediaKind: layout.mediaKind,
      parts,
      contentHash,
      version:
        layout.format === 'text' && layout.textHash && layout.legacyTextIdentity
          ? layout.textHash
          : buildArtifactContentDigest({
              layoutDigest: layout.layoutDigest,
              contentHash,
            }),
    },
    textHash: layout.textHash,
  };
}
