import { createEntityAttributes } from '@genfeedai/helpers';

export const contentRunAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'brand',
  'contract',
  'version',
  'skillSlug',
  'status',
  'phase',
  'revision',
  'recipeVersion',
  'input',
  'output',
  'brief',
  'draft',
  'readiness',
  'execution',
  'variants',
  'review',
  'publish',
  'paidDraft',
  'analyticsSummary',
  'recommendations',
  'error',
  'duration',
  'creditsUsed',
  'source',
  'sourceSnapshot',
]);
