import { createEntityAttributes } from '@genfeedai/helpers';

export const contentPerformanceAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'userId',
  'postId',
  'contentRunId',
  'workflowExecutionId',
  'variantId',
  'generationId',
  'platform',
  'externalPostId',
  'contentType',
  'views',
  'likes',
  'comments',
  'shares',
  'saves',
  'clicks',
  'revenue',
  'engagementRate',
  'performanceScore',
  'measuredAt',
  'cycleNumber',
  'source',
]);
