import { createEntityAttributes } from '@genfeedai/helpers';

export const knowledgeSourceAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'userId',
  'scope',
  'title',
  'kind',
  'purpose',
  'isVisible',
  'mediaReferenceKey',
  'isRefreshEnabled',
  'refreshIntervalMinutes',
  'gracePeriodMinutes',
  'refreshWorkflowId',
  'referenceUrl',
  'syncState',
  'lastCheckedAt',
  'lastSuccessfulSyncAt',
  'nextCheckAt',
  'firstFailureAt',
  'consecutiveFailures',
  'staleAt',
  'lastSyncError',
]);
