import { createEntityAttributes } from '@genfeedai/helpers';

export const personaAttributes = createEntityAttributes([
  'user',
  'organization',
  'brand',
  'label',
  'handle',
  'bio',
  'profileImageUrl',
  'avatar',
  'avatarProvider',
  'avatarExternalId',
  'voice',
  'voiceProvider',
  'voiceExternalId',
  'contentStrategy',
  'credentials',
  'assignedMembers',
  'status',
  'tags',
  'slug',
  'triggerWord',
  'loraStatus',
  'loraModelPath',
  'niche',
  'emoji',
  'darkroomSources',
]);
