import { createEntityAttributes } from '@genfeedai/helpers';

export const studioLookAttributes = createEntityAttributes([
  'organizationId',
  'brandId',
  'userId',
  'label',
  'assetType',
  'promptTemplate',
  'style',
  'mood',
  'scene',
  'camera',
  'lens',
  'lighting',
  'cameraMovement',
  'modelKey',
  'prioritize',
  'outputs',
  'aspectRatio',
  'duration',
  'resolution',
  'brandingMode',
  'isPromptEnhanceEnabled',
]);
