import { createEntityAttributes } from '@genfeedai/helpers';

export const workspaceTaskAttributes = createEntityAttributes([
  'organization',
  'brand',
  'user',
  'title',
  'request',
  'outputType',
  'platforms',
  'priority',
  'status',
  'reviewState',
  'executionPathUsed',
  'chosenModel',
  'chosenProvider',
  'routingSummary',
  'skillsUsed',
  'skillVariantIds',
  'reviewTriggered',
  'linkedIssueId',
  'linkedRunIds',
  'linkedOutputIds',
  'approvedOutputIds',
  'linkedApprovalIds',
  'planningThreadId',
  'resultPreview',
  'qualityAssessment',
  'progress',
  'eventStream',
  'failureReason',
  'requestedChangesReason',
  'completedAt',
  'dismissedAt',
]);
