import { createEntityAttributes } from '@genfeedai/helpers';

export const modelAttributes = createEntityAttributes([
  'label',
  'description',
  'category',
  'key',
  'provider',
  'cost',
  'isActive',
  'isDefault',
  'isHighlighted',
  'capabilities',
  'costTier',
  'recommendedFor',
  'speedTier',
  'qualityTier',
  'supportsFeatures',
  'minDimensions',
  'maxDimensions',
  'pricingType',
  'costPerUnit',
  'minCost',
  'inputCostPerMillionTokens',
  'outputCostPerMillionTokens',
  'providerCostUsd',
  // Output capability fields
  'aspectRatios',
  'defaultAspectRatio',
  'maxOutputs',
  'maxReferences',
  'isBatchSupported',
  'durations',
  'defaultDuration',
  'hasEndFrame',
  'hasInterpolation',
  'hasSpeech',
  'hasAudioToggle',
  'hasResolutionOptions',
  'isImagenModel',
  'isReferencesMandatory',
  'usesOrientation',
  'hasDurationEditing',
  // Lifecycle fields
  'succeededBy',
  'predecessorOf',
  'isDeprecated',
  'deprecatedAt',
]);
