import { createEntityAttributes } from '@genfeedai/helpers';

export const platformSettingAttributes = createEntityAttributes([
  'marginMultiplierGeneration',
  'marginMultiplierAgentChat',
  'marginInputMode',
  'typedDecisionProvider',
  'isMediaPerceptionEnabled',
  'mediaPerceptionFrameCount',
  'mediaPerceptionLookbackHours',
  'mediaPerceptionVisionModel',
  'mediaGateVisionMode',
  'mediaTextGateDecisionMode',
  'mediaTextGateMinConfidence',
  'moderationMode',
  'moderationProvider',
  'moderationThresholds',
  'agentAutoRoutingDecisionMode',
  'modelDiscoveryDecisionMode',
  'modelDiscoveryMinConfidence',
  'patternAnalyzerDecisionMode',
  'patternAnalyzerMinConfidence',
  'replyBotIntentDecisionMode',
  'replyBotIntentMinConfidence',
  'taskRoutingDecisionMode',
  'taskRoutingMinConfidence',
  'untrustedContentDecisionMode',
  'untrustedContentMinConfidence',
  'isAgentContextCompressionEnabled',
  'isAgentTokenStreamingEnabled',
  'systemEventsEnabledAt',
  'isEmailVerificationRequired',
  'flags',
]);
