import { createEntityAttributes } from '@genfeedai/helpers';

export const promptAttributes = createEntityAttributes([
  'organization',
  'brand',
  'user',
  'ingredient',
  'original',
  'enhanced',
  'status',
  'category',
  'style',
  'mood',
  'camera',
  'scene',
  'fontFamily',
  'blacklists',
  'tags',
  'model',
  'modelSettings',
  'metadata',
  'tokens',
  'version',
  'duration',
  'ratio',
  'resolution',
  'isSkipEnhancement',
  'systemPromptKey',
  'scope',
  'isFavorite',
]);
