import { createEntityAttributes } from '@genfeedai/helpers';

export const trainingAttributes = createEntityAttributes([
  'user',
  'organization',
  'brand',
  'label',
  'trigger',
  'status',
  'sources',
  'externalId',
  'category',
  'steps',
  'seed',
  'model',
  'provider',
  'description',
  'persona',
  'personaSlug',
  'loraName',
  'baseModel',
  'stage',
  'progress',
  'error',
  'loraRank',
  'learningRate',
  'startedAt',
  'completedAt',
  'totalSources',
  'totalGeneratedImages',
]);
