import { createEntityAttributes } from '@genfeedai/helpers';

export const brandAttributes = createEntityAttributes([
  'user',
  'organization',
  'tags',
  'slug',
  'label',
  'description',
  'text',
  'fontFamily',
  'primaryColor',
  'secondaryColor',
  'backgroundColor',
  'defaultVideoModel',
  'defaultImageModel',
  'defaultImageToVideoModel',
  'defaultMusicModel',
  'isSelected',
  'scope',
  'isActive',
  'isHighlighted',
  'isDarkroomEnabled',
  'isDefault',
  'logoUrl',
  'bannerUrl',
  'logo',
  'banner',
  'references',
  'credentials',
  'links',
  'agentConfig',
  'instagramHandle',
  'externalId',
  'externalHandle',
]);
