import { APP_ROUTES } from '@genfeedai/contracts/constants';
import type { MenuItemConfig } from '@genfeedai/contracts/interfaces/ui/menu-config.interface';
import {
  Banknote,
  ChartColumn,
  ClipboardList,
  Cpu,
  CreditCard,
  FileText,
  Gift,
  Image,
  Mail,
  Megaphone,
  Newspaper,
  Settings,
  ShieldCheck,
  Tag,
  Users,
  Volume2,
} from 'lucide-react';

/**
 * Admin nav is long — mark the first item of each named group collapsible so
 * CollapsibleGroup shows a chevron header. Other app shells leave
 * `isCollapsible` unset and keep static section labels.
 */
function withAdminCollapsibleGroups(items: MenuItemConfig[]): MenuItemConfig[] {
  const seenGroups = new Set<string>();
  return items.map((item) => {
    const group = item.group ?? '';
    if (!group || seenGroups.has(group)) {
      return item;
    }
    seenGroups.add(group);
    return { ...item, isCollapsible: true };
  });
}

export const ADMIN_MENU_ITEMS: MenuItemConfig[] = withAdminCollapsibleGroups([
  {
    group: 'Overview',
    hrefScope: 'global',
    // Real page is `/admin/overview/dashboard`. Bare `/admin` re-exports it and
    // permanently redirects here; never link to `/admin/overview` (no page).
    href: APP_ROUTES.ADMIN.OVERVIEW.DASHBOARD,
    label: 'Dashboard',
    matchPaths: [APP_ROUTES.ADMIN.ROOT, APP_ROUTES.ADMIN.OVERVIEW.DASHBOARD],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Overview',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS_ALL,
    label: 'Analytics',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Overview',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES,
    label: 'Activities',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES],
    outline: ClipboardList,
    solid: ClipboardList,
  },
  {
    group: 'Content',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONTENT.POSTS,
    label: 'Posts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.POSTS],
    outline: Newspaper,
    solid: Newspaper,
  },
  {
    group: 'Content',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONTENT.TEMPLATES,
    label: 'Templates',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.TEMPLATES],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Content',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONTENT.PROMPTS_LIST,
    label: 'Prompts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.PROMPTS],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Content',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONTENT.INGREDIENTS_VIDEOS,
    label: 'Ingredients',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.INGREDIENTS],
    outline: Image,
    solid: Image,
  },
  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.AUTOMATION.MODELS_ALL,
    label: 'Models',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.MODELS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.AUTOMATION.TRAININGS,
    label: 'Trainings',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.TRAININGS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.AUTOMATION.BOTS,
    label: 'Bots',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.BOTS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.LIBRARY.VOICES,
    label: 'Voice Library',
    matchPaths: [APP_ROUTES.ADMIN.LIBRARY.VOICES],
    outline: Volume2,
    solid: Volume2,
  },
  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS,
    label: 'Workflows',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS],
    outline: ClipboardList,
    solid: ClipboardList,
  },

  {
    group: 'AI & Automation',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.AUTOMATION.FAILURES,
    label: 'Agent Failures',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.FAILURES],
    outline: ClipboardList,
    solid: ClipboardList,
  },
  {
    group: 'Configuration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS_BLACKLISTS,
    label: 'Elements',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS],
    outline: Tag,
    solid: Tag,
  },
  {
    group: 'Configuration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONFIGURATION.PRESETS,
    label: 'Presets',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.PRESETS],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Configuration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES,
    label: 'Font Families',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES],
    outline: Settings,
    solid: Settings,
  },
  {
    group: 'Configuration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.CONFIGURATION.TAGS_ALL,
    label: 'Tags',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.TAGS],
    outline: Tag,
    solid: Tag,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS_ORGANIZATIONS,
    label: 'Organizations',
    matchPaths: [
      APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS_ORGANIZATIONS,
      APP_ROUTES.ADMIN.ORGANIZATION,
    ],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.USERS,
    label: 'Users',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.USERS],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS,
    label: 'Warm-up accounts',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ROLES,
    label: 'Roles',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ROLES],
    outline: ShieldCheck,
    solid: ShieldCheck,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS,
    label: 'Subscriptions',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS],
    outline: CreditCard,
    solid: CreditCard,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.CREDIT_USAGE,
    label: 'Credit Usage',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.CREDIT_USAGE],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.REFERRALS,
    label: 'Referral Rewards',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.REFERRALS],
    outline: Gift,
    solid: Gift,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS,
    label: 'Announcements',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS],
    outline: Megaphone,
    solid: Megaphone,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.SYSTEM_EMAILS,
    label: 'System Emails',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.SYSTEM_EMAILS],
    outline: Mail,
    solid: Mail,
  },
  {
    group: 'Administration',
    hrefScope: 'global',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.PLATFORM_SETTINGS,
    label: 'Platform Settings',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.PLATFORM_SETTINGS],
    outline: Banknote,
    solid: Banknote,
  },
]);
