import { APP_ROUTES } from '@genfeedai/constants';
import type { MenuItemConfig } from '@genfeedai/interfaces/ui/menu-config.interface';
import {
  HiChartBar,
  HiChatBubbleLeftRight,
  HiClipboardDocumentList,
  HiCog6Tooth,
  HiCpuChip,
  HiCreditCard,
  HiDocumentText,
  HiMegaphone,
  HiNewspaper,
  HiOutlineChartBar,
  HiOutlineChatBubbleLeftRight,
  HiOutlineClipboardDocumentList,
  HiOutlineCog6Tooth,
  HiOutlineCpuChip,
  HiOutlineCreditCard,
  HiOutlineDocumentText,
  HiOutlineMegaphone,
  HiOutlineNewspaper,
  HiOutlinePhoto,
  HiOutlineShieldCheck,
  HiOutlineSpeakerWave,
  HiOutlineTag,
  HiOutlineUserGroup,
  HiOutlineVideoCamera,
  HiPhoto,
  HiShieldCheck,
  HiSpeakerWave,
  HiTag,
  HiUserGroup,
  HiVideoCamera,
} from 'react-icons/hi2';

export const ADMIN_LOGO_HREF = APP_ROUTES.ADMIN.ROOT;

export const ADMIN_MENU_ITEMS: MenuItemConfig[] = [
  {
    group: '',
    href: APP_ROUTES.ADMIN.AGENT,
    label: 'Agent',
    matchPaths: [APP_ROUTES.ADMIN.AGENT],
    outline: HiOutlineChatBubbleLeftRight,
    solid: HiChatBubbleLeftRight,
  },
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.ROOT,
    label: 'Dashboard',
    matchPaths: [APP_ROUTES.ADMIN.ROOT, APP_ROUTES.ADMIN.OVERVIEW.DASHBOARD],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS_ALL,
    label: 'Analytics',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES,
    label: 'Activities',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES],
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.POSTS,
    label: 'Posts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.POSTS],
    outline: HiOutlineNewspaper,
    solid: HiNewspaper,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.TEMPLATES,
    label: 'Templates',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.TEMPLATES],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.PROMPTS_LIST,
    label: 'Prompts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.PROMPTS],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.INGREDIENTS_VIDEOS,
    label: 'Ingredients',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.INGREDIENTS],
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.MODELS_ALL,
    label: 'Models',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.MODELS],
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.TRAININGS,
    label: 'Trainings',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.TRAININGS],
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.BOTS,
    label: 'Bots',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.BOTS],
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.LIBRARY.VOICES,
    label: 'Voice Library',
    matchPaths: [APP_ROUTES.ADMIN.LIBRARY.VOICES],
    outline: HiOutlineSpeakerWave,
    solid: HiSpeakerWave,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS,
    label: 'Workflows',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS],
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS_BLACKLISTS,
    label: 'Elements',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS],
    outline: HiOutlineTag,
    solid: HiTag,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.PRESETS,
    label: 'Presets',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.PRESETS],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES,
    label: 'Font Families',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES],
    outline: HiOutlineCog6Tooth,
    solid: HiCog6Tooth,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.TAGS_ALL,
    label: 'Tags',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.TAGS],
    outline: HiOutlineTag,
    solid: HiTag,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ORGANIZATION,
    label: 'Organizations',
    matchPaths: [APP_ROUTES.ADMIN.ORGANIZATION],
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.USERS,
    label: 'Users',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.USERS],
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS,
    label: 'Warm-up accounts',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS],
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ROLES,
    label: 'Roles',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ROLES],
    outline: HiOutlineShieldCheck,
    solid: HiShieldCheck,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS,
    label: 'Subscriptions',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS],
    outline: HiOutlineCreditCard,
    solid: HiCreditCard,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS,
    label: 'Announcements',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS],
    outline: HiOutlineMegaphone,
    solid: HiMegaphone,
  },
  {
    group: 'Fleet',
    hasDividerAbove: true,
    href: APP_ROUTES.ADMIN.FLEET.CHARACTERS,
    label: 'Characters',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.CHARACTERS],
    outline: HiOutlineUserGroup,
    solid: HiUserGroup,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.GALLERY,
    label: 'Gallery',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.GALLERY],
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.TRAINING,
    label: 'Training',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.TRAINING],
    outline: HiOutlineCpuChip,
    solid: HiCpuChip,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.PIPELINE,
    label: 'Pipeline',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.PIPELINE],
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.GENERATE,
    label: 'Generate',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.GENERATE],
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.LIP_SYNC,
    label: 'Lip Sync',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.LIP_SYNC],
    outline: HiOutlineVideoCamera,
    solid: HiVideoCamera,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.VOICES,
    label: 'Voices',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.VOICES],
    outline: HiOutlineSpeakerWave,
    solid: HiSpeakerWave,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.INFRASTRUCTURE,
    label: 'Infrastructure',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.INFRASTRUCTURE],
    outline: HiOutlineCog6Tooth,
    solid: HiCog6Tooth,
  },
];
