import { APP_ROUTES } from '@genfeedai/constants';
import type { MenuItemConfig } from '@genfeedai/interfaces/ui/menu-config.interface';
import {
  Banknote,
  ChartColumn,
  ClipboardList,
  Cpu,
  CreditCard,
  FileText,
  Image,
  Mail,
  Megaphone,
  Newspaper,
  Settings,
  ShieldCheck,
  Tag,
  Users,
  Video,
  Volume2,
} from 'lucide-react';

export const ADMIN_LOGO_HREF = APP_ROUTES.ADMIN.ROOT;

export const ADMIN_MENU_ITEMS: MenuItemConfig[] = [
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.ROOT,
    label: 'Overview',
    matchPaths: [APP_ROUTES.ADMIN.ROOT, APP_ROUTES.ADMIN.OVERVIEW.DASHBOARD],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS_ALL,
    label: 'Analytics',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ANALYTICS],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Overview',
    href: APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES,
    label: 'Activities',
    matchPaths: [APP_ROUTES.ADMIN.OVERVIEW.ACTIVITIES],
    outline: ClipboardList,
    solid: ClipboardList,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.POSTS,
    label: 'Posts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.POSTS],
    outline: Newspaper,
    solid: Newspaper,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.TEMPLATES,
    label: 'Templates',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.TEMPLATES],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.PROMPTS_LIST,
    label: 'Prompts',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.PROMPTS],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Content',
    href: APP_ROUTES.ADMIN.CONTENT.INGREDIENTS_VIDEOS,
    label: 'Ingredients',
    matchPaths: [APP_ROUTES.ADMIN.CONTENT.INGREDIENTS],
    outline: Image,
    solid: Image,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.MODELS_ALL,
    label: 'Models',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.MODELS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.TRAININGS,
    label: 'Trainings',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.TRAININGS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.BOTS,
    label: 'Bots',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.BOTS],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.LIBRARY.VOICES,
    label: 'Voice Library',
    matchPaths: [APP_ROUTES.ADMIN.LIBRARY.VOICES],
    outline: Volume2,
    solid: Volume2,
  },
  {
    group: 'AI & Automation',
    href: APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS,
    label: 'Workflows',
    matchPaths: [APP_ROUTES.ADMIN.AUTOMATION.WORKFLOWS],
    outline: ClipboardList,
    solid: ClipboardList,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS_BLACKLISTS,
    label: 'Elements',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.ELEMENTS],
    outline: Tag,
    solid: Tag,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.PRESETS,
    label: 'Presets',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.PRESETS],
    outline: FileText,
    solid: FileText,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES,
    label: 'Font Families',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.FONT_FAMILIES],
    outline: Settings,
    solid: Settings,
  },
  {
    group: 'Configuration',
    href: APP_ROUTES.ADMIN.CONFIGURATION.TAGS_ALL,
    label: 'Tags',
    matchPaths: [APP_ROUTES.ADMIN.CONFIGURATION.TAGS],
    outline: Tag,
    solid: Tag,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ORGANIZATION,
    label: 'Organizations',
    matchPaths: [APP_ROUTES.ADMIN.ORGANIZATION],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.USERS,
    label: 'Users',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.USERS],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS,
    label: 'Warm-up accounts',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.WARMUP_ACCOUNTS],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ROLES,
    label: 'Roles',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ROLES],
    outline: ShieldCheck,
    solid: ShieldCheck,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS,
    label: 'Subscriptions',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.SUBSCRIPTIONS],
    outline: CreditCard,
    solid: CreditCard,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.CREDIT_USAGE,
    label: 'Credit Usage',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.CREDIT_USAGE],
    outline: ChartColumn,
    solid: ChartColumn,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS,
    label: 'Announcements',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.ANNOUNCEMENTS],
    outline: Megaphone,
    solid: Megaphone,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.SYSTEM_EMAILS,
    label: 'System Emails',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.SYSTEM_EMAILS],
    outline: Mail,
    solid: Mail,
  },
  {
    group: 'Administration',
    href: APP_ROUTES.ADMIN.ADMINISTRATION.PLATFORM_SETTINGS,
    label: 'Platform Settings',
    matchPaths: [APP_ROUTES.ADMIN.ADMINISTRATION.PLATFORM_SETTINGS],
    outline: Banknote,
    solid: Banknote,
  },
  {
    group: 'Fleet',
    hasDividerAbove: true,
    href: APP_ROUTES.ADMIN.FLEET.CHARACTERS,
    label: 'Characters',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.CHARACTERS],
    outline: Users,
    solid: Users,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.GALLERY,
    label: 'Gallery',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.GALLERY],
    outline: Image,
    solid: Image,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.TRAINING,
    label: 'Training',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.TRAINING],
    outline: Cpu,
    solid: Cpu,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.PIPELINE,
    label: 'Pipeline',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.PIPELINE],
    outline: ClipboardList,
    solid: ClipboardList,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.GENERATE,
    label: 'Generate',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.GENERATE],
    outline: Image,
    solid: Image,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.LIP_SYNC,
    label: 'Lip Sync',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.LIP_SYNC],
    outline: Video,
    solid: Video,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.VOICES,
    label: 'Voices',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.VOICES],
    outline: Volume2,
    solid: Volume2,
  },
  {
    group: 'Fleet',
    href: APP_ROUTES.ADMIN.FLEET.INFRASTRUCTURE,
    label: 'Infrastructure',
    matchPaths: [APP_ROUTES.ADMIN.FLEET.INFRASTRUCTURE],
    outline: Settings,
    solid: Settings,
  },
];
