import type { MenuItemConfig } from '@genfeedai/interfaces/ui/menu-config.interface';
import {
  HiArrowTrendingUp,
  HiBuildingOffice2,
  HiCalendar,
  HiChartBar,
  HiClipboardDocumentCheck,
  HiClipboardDocumentList,
  HiClock,
  HiCog6Tooth,
  HiDocumentText,
  HiFilm,
  HiFolder,
  HiInboxStack,
  HiMicrophone,
  HiMusicalNote,
  HiOutlineArrowTrendingUp,
  HiOutlineBuildingOffice2,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineClipboardDocumentCheck,
  HiOutlineClipboardDocumentList,
  HiOutlineClock,
  HiOutlineCog6Tooth,
  HiOutlineDocumentText,
  HiOutlineFilm,
  HiOutlineFolder,
  HiOutlineInboxStack,
  HiOutlineMicrophone,
  HiOutlineMusicalNote,
  HiOutlinePencilSquare,
  HiOutlinePhoto,
  HiOutlinePlayCircle,
  HiOutlineSparkles,
  HiOutlineSquares2X2,
  HiOutlineWrenchScrewdriver,
  HiPencilSquare,
  HiPhoto,
  HiPlayCircle,
  HiSparkles,
  HiSquares2X2,
  HiWrenchScrewdriver,
} from 'react-icons/hi2';

/** Label after which dynamic credential items are inserted in the Posts group */
export const POSTS_INSERT_AFTER_LABEL = 'Review';

export const APP_MENU_ITEMS: MenuItemConfig[] = [
  {
    group: '',
    href: '/workspace/overview',
    label: 'Dashboard',
    matchPaths: ['/workspace', '/workspace/overview'],
    outline: HiOutlineSquares2X2,
    solid: HiSquares2X2,
  },
  {
    group: '',
    href: '/workspace/inbox/unread',
    label: 'Inbox',
    matchPaths: [
      '/workspace/inbox',
      '/workspace/inbox/unread',
      '/workspace/inbox/recent',
      '/workspace/inbox/all',
    ],
    outline: HiOutlineInboxStack,
    solid: HiInboxStack,
  },
  {
    group: '',
    href: '/issues',
    label: 'Issues',
    matchPaths: ['/issues'],
    outline: HiOutlineClipboardDocumentList,
    solid: HiClipboardDocumentList,
  },
  {
    drillDown: true,
    group: 'Library',
    href: '/library/ingredients',
    label: 'Library',
    matchPaths: ['/library', '/library/ingredients'],
    outline: HiOutlineFolder,
    solid: HiFolder,
  },
  {
    group: 'Library',
    href: '/library/images',
    label: 'Images',
    matchPaths: ['/library/images'],
    outline: HiOutlinePhoto,
    solid: HiPhoto,
  },
  {
    group: 'Library',
    href: '/library/videos',
    label: 'Videos',
    matchPaths: ['/library/videos'],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Library',
    href: '/library/gifs',
    label: 'GIFs',
    matchPaths: ['/library/gifs'],
    outline: HiOutlinePlayCircle,
    solid: HiPlayCircle,
  },
  {
    group: 'Library',
    href: '/library/voices',
    label: 'Voices',
    matchPaths: ['/library/voices'],
    outline: HiOutlineMicrophone,
    solid: HiMicrophone,
  },
  {
    group: 'Library',
    href: '/library/music',
    label: 'Music',
    matchPaths: ['/library/music'],
    outline: HiOutlineMusicalNote,
    solid: HiMusicalNote,
  },
  {
    group: 'Library',
    href: '/library/captions',
    label: 'Captions',
    matchPaths: ['/library/captions', '/captions'],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    drillDown: true,
    group: 'Analytics',
    href: '/analytics/overview',
    label: 'Overview',
    matchPaths: ['/analytics', '/analytics/overview'],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Analytics',
    href: '/analytics/posts',
    label: 'Posts',
    matchPaths: ['/analytics/posts'],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    group: 'Analytics',
    href: '/analytics/brands',
    label: 'Brands',
    matchPaths: ['/analytics/brands'],
    outline: HiOutlineBuildingOffice2,
    solid: HiBuildingOffice2,
  },
  {
    group: 'Analytics',
    href: '/analytics/insights',
    label: 'Insights',
    matchPaths: ['/analytics/insights'],
    outline: HiOutlineSparkles,
    solid: HiSparkles,
  },
  {
    group: 'Analytics',
    href: '/analytics/hooks',
    label: 'Hooks',
    matchPaths: ['/analytics/hooks'],
    outline: HiOutlineArrowTrendingUp,
    solid: HiArrowTrendingUp,
  },
  {
    group: 'Analytics',
    href: '/analytics/performance-lab',
    label: 'Performance Lab',
    matchPaths: ['/analytics/performance-lab'],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Analytics',
    href: '/analytics/trend-turnover',
    label: 'Trend Turnover',
    matchPaths: ['/analytics/trend-turnover'],
    outline: HiOutlineArrowTrendingUp,
    solid: HiArrowTrendingUp,
  },
  {
    drillDown: true,
    group: 'Posts',
    href: '/posts/analytics',
    label: 'Analytics',
    matchPaths: ['/posts/analytics'],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Posts',
    href: '/posts/remix',
    label: 'Remix',
    matchPaths: ['/posts/remix'],
    outline: HiOutlinePlayCircle,
    solid: HiPlayCircle,
  },
  {
    group: 'Posts',
    href: '/posts/calendar',
    label: 'Calendar',
    matchPaths: ['/posts/calendar'],
    outline: HiOutlineCalendar,
    solid: HiCalendar,
  },
  {
    group: 'Posts',
    href: '/posts/review',
    label: 'Review',
    matchPaths: ['/posts/review'],
    outline: HiOutlineClipboardDocumentCheck,
    solid: HiClipboardDocumentCheck,
  },
  {
    group: 'Posts',
    href: '/posts',
    label: 'Posts',
    matchPaths: ['/posts'],
    outline: HiOutlineDocumentText,
    solid: HiDocumentText,
  },
  {
    drillDown: true,
    group: 'Operations',
    href: '/workflows/executions',
    label: 'Runs',
    matchPaths: ['/workflows/executions', '/orchestration/runs'],
    outline: HiOutlineChartBar,
    solid: HiChartBar,
  },
  {
    group: 'Operations',
    href: '/workflows',
    label: 'Workflows',
    matchPaths: ['/orchestration/workflows', '/workflows'],
    outline: HiOutlineWrenchScrewdriver,
    solid: HiWrenchScrewdriver,
  },
  {
    group: 'Operations',
    href: '/orchestration/skills',
    label: 'Skills',
    matchPaths: ['/orchestration/skills'],
    outline: HiOutlineSparkles,
    solid: HiSparkles,
  },
  {
    group: 'Operations',
    href: '/workflows/autopilot',
    label: 'Autopilot',
    matchPaths: [
      '/workflows/autopilot',
      '/orchestration/autopilot',
      '/orchestration/strategies',
    ],
    outline: HiOutlineSparkles,
    solid: HiSparkles,
  },
  {
    group: 'Operations',
    href: '/workflows/configuration',
    label: 'Configuration',
    matchPaths: ['/workflows/configuration', '/orchestration/configuration'],
    outline: HiOutlineCog6Tooth,
    solid: HiCog6Tooth,
  },
  {
    drillDown: true,
    group: 'Create',
    href: '/studio/image',
    label: 'Studio',
    matchPaths: ['/studio', '/studio/image', '/studio/video'],
    outline: HiOutlineSparkles,
    solid: HiSparkles,
  },
  {
    group: 'Create',
    href: '/compose/post',
    label: 'Compose',
    matchPaths: [
      '/compose',
      '/compose/post',
      '/compose/article',
      '/compose/newsletter',
    ],
    outline: HiOutlinePencilSquare,
    solid: HiPencilSquare,
  },
  {
    group: 'Create',
    href: '/editor',
    label: 'Editor',
    matchPaths: ['/editor'],
    outline: HiOutlineFilm,
    solid: HiFilm,
  },
];

export const APP_SECONDARY_MENU_ITEMS: MenuItemConfig[] = [
  {
    group: '',
    href: '/workspace/activity',
    label: 'Activity',
    matchPaths: ['/workspace/activity'],
    outline: HiOutlineClock,
    solid: HiClock,
  },
];

export function getAppSecondaryMenuItems(
  brandId?: string | null,
): MenuItemConfig[] {
  if (!brandId) {
    return APP_SECONDARY_MENU_ITEMS;
  }

  return [
    ...APP_SECONDARY_MENU_ITEMS,
    {
      group: '',
      href: `/settings/brands/${brandId}`,
      label: 'Settings',
      matchPaths: [`/settings/brands/${brandId}`],
      outline: HiOutlineCog6Tooth,
      solid: HiCog6Tooth,
    },
  ];
}

export const APP_LOGO_HREF = '/workspace/overview';
