/**
 * Avatars Module
 * Avatar system: character avatars, avatar customization, avatar library,
and avatar animation settings.
 */
import { AvatarsController } from '@api/collections/avatars/controllers/avatars.controller';
import { AvatarsService } from '@api/collections/avatars/services/avatars.service';
import { CreditsModule } from '@api/collections/credits/credits.module';
import { IngredientsModule } from '@api/collections/ingredients/ingredients.module';
import { MetadataModule } from '@api/collections/metadata/metadata.module';
import { ModelsModule } from '@api/collections/models/models.module';
import { UsersModule } from '@api/collections/users/users.module';
import { VotesModule } from '@api/collections/votes/votes.module';
import { CreditsGuard } from '@api/helpers/guards/credits/credits.guard';
import { CreditsInterceptor } from '@api/helpers/interceptors/credits/credits.interceptor';
import { ByokModule } from '@api/services/byok/byok.module';
import { ElevenLabsModule } from '@api/services/integrations/elevenlabs/elevenlabs.module';
import { HedraModule } from '@api/services/integrations/hedra/hedra.module';
import { HeyGenModule } from '@api/services/integrations/heygen/heygen.module';
import { FailedGenerationModule } from '@api/shared/services/failed-generation/failed-generation.module';
import { forwardRef, Module } from '@nestjs/common';

// The avatars are generated by HeyGen or Hedra.
// The video generated are stored as video inggredient with the transformation of the avatar.

@Module({
  controllers: [AvatarsController],
  exports: [AvatarsService],
  imports: [
    ByokModule,
    forwardRef(() => CreditsModule),
    forwardRef(() => IngredientsModule),
    forwardRef(() => MetadataModule),
    forwardRef(() => ModelsModule),

    ElevenLabsModule,
    FailedGenerationModule,
    HedraModule,
    HeyGenModule,
    UsersModule,
    VotesModule,
  ],
  providers: [AvatarsService, CreditsGuard, CreditsInterceptor],
})
export class AvatarsModule {}
