import { createEntityAttributes } from '@genfeedai/helpers';

export const leadAttributes = createEntityAttributes([
  'assignedTo',
  'brandUrl',
  'company',
  'companyRef',
  'contactDate',
  'convertedAt',
  'currency',
  'dealValue',
  'discordHandle',
  'email',
  'instagramHandle',
  'invitedAt',
  'lastContactedAt',
  'lastOutreachFailedAt',
  'lastOutreachMessageId',
  'lastOutreachSentAt',
  'lastOutreachStatus',
  'name',
  'nextFollowUpAt',
  'notes',
  'organization',
  'phone',
  'productOffering',
  'proactiveBatchId',
  'proactiveBrand',
  'proactiveOrganization',
  'proactiveStatus',
  'source',
  'status',
  'tags',
  'telegramHandle',
  'title',
  'twitterHandle',
]);
