import { formatEnumLabel } from '@genfeedai/contracts';

export const TOOL_LABELS: Record<string, string> = {
  ai_action: 'AI Action',
  batch_approve_reject: 'Batch Review Action',
  check_onboarding_status: 'Check Onboarding',
  complete_outreach_sequence: 'Complete outreach sequence',
  complete_onboarding: 'Complete Onboarding',
  connect_social_account: 'Connect Account',
  create_brand: 'Create Brand',
  create_outreach_sequence: 'Create outreach sequence',
  create_post: 'Create Post',
  create_workflow: 'Create Workflow',
  discover_engagements: 'Discover Engagements',
  draft_brand_voice_profile: 'Draft Brand Voice',
  draft_engagement_reply: 'Draft Reply',
  draft_x_quote: 'Draft X Quote',
  draft_x_repost: 'Draft X Repost',
  execute_workflow: 'Execute Workflow',
  fetch_x_post: 'Fetch X Post',
  generate_content: 'Generate Content',
  generate_content_batch: 'Batch Generate',
  generate_image: 'Generate Image',
  generate_monthly_content: 'Monthly Content',
  generate_onboarding_content: 'Generate Sample Content',
  generate_video: 'Generate Video',
  generate_voice: 'Generate Voice',
  get_analytics: 'Analytics',
  get_outreach_sequence_analytics: 'Outreach sequence analytics',
  get_connection_status: 'Connection Status',
  get_credits_balance: 'Credit Balance',
  get_current_brand: 'Current Brand',
  get_dashboard_layout: 'Get Dashboard Layout',
  get_trends: 'Trends',
  initiate_oauth_connect: 'Connect Account',
  list_brands: 'List Brands',
  list_posts: 'List Posts',
  list_review_queue: 'Review Queue',
  list_workflows: 'List Workflows',
  list_x_account_activity: 'X Account Activity',
  open_studio_handoff: 'Open in Studio',
  pause_outreach_sequence: 'Pause outreach sequence',
  prepare_clip_workflow_run: 'Prepare Clip Run',
  prepare_generation: 'Prepare Generation',
  prepare_workflow_trigger: 'Prepare Workflow Trigger',
  present_payment_options: 'Payment Options',
  rate_content: 'Rate Content',
  score_seo: 'Score SEO',
  rate_ingredient: 'Rate Ingredient',
  reframe_image: 'Reframe Image',
  rename_brand: 'Rename Brand',
  repurpose_post: 'Repurpose Post',
  resolve_handle: 'Resolve Handle',
  save_brand_voice_profile: 'Save Brand Voice',
  save_dashboard_layout: 'Save Dashboard Layout',
  schedule_post: 'Schedule Post',
  search_x_posts: 'Search X Posts',
  start_outreach_sequence: 'Start outreach sequence',
  suggest_ingredient_alternatives: 'Find Stronger Alternatives',
  suggest_next_steps: 'Suggest Next Steps',
  upscale_image: 'Upscale Image',
};

/** Product copy for tool activity; provider identifiers never reach the UI. */
export function getAgentToolLabel(toolName: string): string {
  return TOOL_LABELS[toolName] ?? formatEnumLabel(toolName) ?? 'Working';
}
