import { createEntityAttributes } from '@genfeedai/helpers';

export const agentThreadAttributes = createEntityAttributes([
  'attentionState',
  'brandId',
  'brandLabel',
  'contextVersion',
  'lastActivityAt',
  'lastAssistantPreview',
  'lastGeneratedAssetUrl',
  'organizationId',
  'pendingInputCount',
  'runStatus',
  'runtimeState',
  'decisionHref',
  'organization',
  'user',
  'isPinned',
  'planModeEnabled',
  'requestedModel',
  'runtimeKey',
  'title',
  'source',
  'status',
]);
