import {
  ContentTemplateKey,
  IngredientCategory,
  IngredientFormat,
  RouterPriority,
} from '@genfeedai/contracts';
import { MODEL_KEYS } from '@genfeedai/contracts/constants';
import type { IIngredient, IModel } from '@genfeedai/contracts/interfaces';
import type { CrunInputControls } from '@genfeedai/contracts/interfaces/content/crun-contract.interface';
import { describe, expect, it } from 'vitest';
import {
  buildAvatarPayload,
  buildBaseGenerationPayload,
  buildImagePayload,
  buildMusicPayload,
  buildRepromptData,
  buildStudioCrunQuoteRequest,
  buildStudioCrunVideoQuoteRequest,
  buildVideoPayload,
} from './generation-payloads';
import { getDefaultStudioGenerateSettings } from './studio-generate-settings';

type PromptData = Parameters<typeof buildMusicPayload>[0];

function makePromptData(overrides: Partial<PromptData> = {}): PromptData {
  return {
    isValid: true,
    text: 'A cinematic product shot',
    ...overrides,
  } as PromptData;
}

describe('buildBaseGenerationPayload', () => {
  it('builds defaults from a minimal prompt', () => {
    const payload = buildBaseGenerationPayload(
      makePromptData(),
      'model-key',
      'brand-1',
    );

    expect(payload).toMatchObject({
      autoSelectModel: false,
      blacklist: [],
      brand: 'brand-1',
      brandingMode: 'off',
      height: 1920,
      isBrandingEnabled: false,
      model: 'model-key',
      outputs: 1,
      prioritize: RouterPriority.BALANCED,
      references: [],
      tags: [],
      text: 'A cinematic product shot',
      useTemplate: true,
      width: 1080,
    });
    expect(payload.promptTemplate).toBeUndefined();
  });

  it('omits the model and derives branding when auto-select and branding are on', () => {
    const payload = buildBaseGenerationPayload(
      makePromptData({
        autoSelectModel: true,
        blacklist: ['text, logos', 'watermark'],
        camera: ' 35mm ',
        isBrandingEnabled: true,
        outputs: 3,
      }),
      'model-key',
      'brand-1',
    );

    expect(payload.autoSelectModel).toBe(true);
    expect(payload.model).toBeUndefined();
    expect(payload.brandingMode).toBe('brand');
    expect(payload.isBrandingEnabled).toBe(true);
    expect(payload.blacklist).toEqual(['text, logos', 'watermark']);
    expect(payload.camera).toBe('35mm');
    expect(payload.outputs).toBe(3);
  });

  it('maps legacy preset keys to content template keys', () => {
    const payload = buildBaseGenerationPayload(
      makePromptData({ prompt_template: 'product-photo' }),
      'model-key',
      'brand-1',
    );

    expect(payload.promptTemplate).toBe(ContentTemplateKey.IMAGE_PRODUCT);
  });

  it('passes through unknown template keys unchanged', () => {
    const payload = buildBaseGenerationPayload(
      makePromptData({ prompt_template: 'custom-template' }),
      'model-key',
      'brand-1',
    );

    expect(payload.promptTemplate).toBe('custom-template');
  });
});

describe('buildVideoPayload', () => {
  it('extends the base payload with video fields and defaults', () => {
    const base = buildBaseGenerationPayload(
      makePromptData(),
      'model-key',
      'brand-1',
    );
    const payload = buildVideoPayload(
      base,
      makePromptData({
        cameraMovement: ' dolly ',
        duration: 8,
        isAudioEnabled: true,
        sounds: ['whoosh'],
      }),
    );

    expect(payload.cameraMovement).toBe('dolly');
    expect(payload.duration).toBe(8);
    expect(payload.format).toBe(IngredientFormat.PORTRAIT);
    expect(payload.isAudioEnabled).toBe(true);
    expect(payload.sounds).toEqual(['whoosh']);
  });

  it('defaults audio off and sounds empty', () => {
    const base = buildBaseGenerationPayload(
      makePromptData(),
      'model-key',
      'brand-1',
    );
    const payload = buildVideoPayload(base, makePromptData());

    expect(payload.isAudioEnabled).toBe(false);
    expect(payload.sounds).toEqual([]);
    expect(payload.duration).toBeUndefined();
  });
});

describe('buildImagePayload', () => {
  it('uses the provided format or falls back to portrait', () => {
    const base = buildBaseGenerationPayload(
      makePromptData(),
      'model-key',
      'brand-1',
    );

    expect(
      buildImagePayload(
        base,
        makePromptData({ format: IngredientFormat.SQUARE }),
      ).format,
    ).toBe(IngredientFormat.SQUARE);
    expect(buildImagePayload(base, makePromptData()).format).toBe(
      IngredientFormat.PORTRAIT,
    );
  });
});

describe('buildMusicPayload', () => {
  it('builds a music payload with an autogenerated label', () => {
    const payload = buildMusicPayload(
      makePromptData({ text: '  lofi beat  ' }),
      'music-model',
      30,
    );

    expect(payload.duration).toBeUndefined();
    expect(payload.label).toMatch(/^music-\d+$/);
    expect(payload.model).toBe('music-model');
    expect(payload.text).toBe('lofi beat');
  });

  it('omits unresolved Auto duration and model', () => {
    const payload = buildMusicPayload(
      makePromptData({ autoSelectModel: true }),
      'music-model',
    );

    expect(payload.duration).toBeUndefined();
    expect(payload.model).toBeUndefined();
  });

  it('drops lyrics when instrumental is requested', () => {
    const payload = buildMusicPayload(
      makePromptData({
        instrumental: true,
        lyrics: 'Verse one\nChorus',
      }),
      MODEL_KEYS.FAL_ELEVENLABS_MUSIC,
      30,
    );

    expect(payload.instrumental).toBe(true);
    expect(payload.lyrics).toBeUndefined();
  });

  it('carries lyrics through for a model that supports them', () => {
    const payload = buildMusicPayload(
      makePromptData({ lyrics: '  Verse one\nChorus \n' }),
      MODEL_KEYS.FAL_ELEVENLABS_MUSIC,
      30,
    );

    expect(payload.lyrics).toBe('Verse one\nChorus');
  });

  it('drops lyrics and forces instrumental true for a model with no vocal support (MusicGen)', () => {
    const payload = buildMusicPayload(
      makePromptData({
        instrumental: true,
        lyrics: 'stale text from a previous model selection',
      }),
      MODEL_KEYS.REPLICATE_META_MUSICGEN,
      10,
    );

    expect(payload.instrumental).toBe(true);
    expect(payload.lyrics).toBeUndefined();
  });

  it('drops stale lyrics text for MusicGen even without the instrumental flag', () => {
    const payload = buildMusicPayload(
      makePromptData({ lyrics: 'stale text' }),
      MODEL_KEYS.REPLICATE_META_MUSICGEN,
      10,
    );

    expect(payload.lyrics).toBeUndefined();
  });

  it('clears settings until Auto resolves a model', () => {
    const payload = buildMusicPayload(
      makePromptData({
        autoSelectModel: true,
        instrumental: true,
        lyrics: 'Verse one',
      }),
      MODEL_KEYS.REPLICATE_META_MUSICGEN,
      10,
    );

    expect(payload.instrumental).toBeUndefined();
    expect(payload.lyrics).toBeUndefined();
    expect(payload.duration).toBeUndefined();
  });
});

describe('buildAvatarPayload', () => {
  it('builds avatar payloads with trimmed speech', () => {
    const payload = buildAvatarPayload(
      makePromptData({
        avatarId: 'avatar-1',
        speech: '  hello world  ',
        voiceId: 'voice-1',
      }),
    );

    expect(payload).toEqual({
      avatarId: 'avatar-1',
      speech: 'hello world',
      text: 'A cinematic product shot',
      voiceId: 'voice-1',
    });
  });

  it('defaults speech to an empty string', () => {
    expect(buildAvatarPayload(makePromptData()).speech).toBe('');
  });

  it('uses a Genfeed portrait URL instead of its internal ingredient id', () => {
    const payload = buildAvatarPayload(
      makePromptData({ avatarId: 'ingredient-1' }),
      'https://cdn.genfeed.test/portrait.png',
    );

    expect(payload).toMatchObject({
      photoUrl: 'https://cdn.genfeed.test/portrait.png',
    });
    expect(payload).not.toHaveProperty('avatarId');
  });
});

describe('buildRepromptData', () => {
  const models = [{ key: 'fallback-model' }] as IModel[];

  it('rebuilds prompt data from ingredient metadata', () => {
    const ingredient = {
      height: 720,
      metadata: {
        blacklist: ['bad', 42],
        camera: '85mm',
        duration: 6,
        isAudioEnabled: true,
        mood: 'moody',
        sounds: ['rain', 7],
        style: 'noir',
      },
      metadataHeight: 1440,
      metadataModel: 'ingredient-model',
      metadataWidth: 810,
      promptText: 'Original prompt',
      references: ['ref-1', 99],
      tags: [{ id: 'tag-id', key: 'tag-key', label: 'Tag' }, { id: 'only-id' }],
      width: 405,
    } as unknown as IIngredient;

    const data = buildRepromptData(
      ingredient,
      IngredientCategory.VIDEO,
      'brand-1',
      models,
    );

    expect(data.blacklist).toEqual(['bad']);
    expect(data.brand).toBe('brand-1');
    expect(data.camera).toBe('85mm');
    expect(data.duration).toBe(6);
    expect(data.format).toBe(IngredientFormat.PORTRAIT);
    expect(data.height).toBe(1440);
    expect(data.isAudioEnabled).toBe(true);
    expect(data.isValid).toBe(true);
    expect(data.models).toEqual(['ingredient-model']);
    expect(data.mood).toBe('moody');
    expect(data.references).toEqual(['ref-1']);
    expect(data.sounds).toEqual(['rain']);
    expect(data.style).toBe('noir');
    expect(data.tags).toEqual(['tag-key', 'only-id']);
    expect(data.text).toBe('Original prompt');
    expect(data.width).toBe(810);
  });

  it('falls back to defaults when metadata is missing', () => {
    const ingredient = {} as IIngredient;

    const data = buildRepromptData(
      ingredient,
      IngredientCategory.MUSIC,
      'brand-1',
      models,
    );

    expect(data.blacklist).toEqual([]);
    expect(data.duration).toBeUndefined();
    expect(data.format).toBe('');
    expect(data.height).toBe(1920);
    expect(data.isAudioEnabled).toBe(false);
    expect(data.models).toEqual(['fallback-model']);
    expect(data.references).toEqual([]);
    expect(data.sounds).toEqual([]);
    expect(data.tags).toEqual([]);
    expect(data.text).toBe('');
    expect(data.width).toBe(1080);
  });

  it('uses an empty model key when no model source exists', () => {
    const data = buildRepromptData(
      {} as IIngredient,
      IngredientCategory.IMAGE,
      'brand-1',
      [],
    );

    expect(data.models).toEqual(['']);
    expect(data.format).toBe(IngredientFormat.PORTRAIT);
  });
});

describe('reviewed Crun request projection', () => {
  const controls: CrunInputControls = {
    endpoint: 'google/nano-banana-pro',
    version: 'reviewed-1',
    mediaKind: 'image',
    maxOutputs: 4,
    isBatchSupported: false,
    referenceRoles: { img_urls: 'image' },
    isAutoAspectReferenceRequired: true,
    fields: {
      prompt: {
        type: 'string',
        isRequired: true,
        minLength: 1,
        maxLength: 20000,
      },
      aspect_ratio: {
        type: 'string',
        isRequired: false,
        enum: ['1:1', '16:9', '21:9', 'auto'],
        default: '1:1',
      },
      resolution: {
        type: 'string',
        isRequired: false,
        enum: ['1K', '2K', '4K'],
        default: '1K',
      },
      output_format: {
        type: 'string',
        isRequired: false,
        enum: ['png', 'jpg'],
        default: 'png',
      },
      img_urls: {
        type: 'array',
        isRequired: false,
        maxItems: 8,
        format: 'uri',
      },
    },
  };
  const model = {
    key: 'crun/google/nano-banana-pro',
    provider: 'crun',
    inputControls: controls,
  } as IModel;
  function build(
    overrides: Partial<Parameters<typeof buildStudioCrunQuoteRequest>[0]> = {},
  ) {
    return buildStudioCrunQuoteRequest({
      model,
      brandId: 'brand-1',
      promptText: ' A product ',
      references: ['image-1'],
      settings: {
        ...getDefaultStudioGenerateSettings('image'),
        modelKey: model.key,
        aspectRatio: '21:9',
        resolution: '2K',
        outputs: 4,
        crunControls: {
          modelKey: model.key,
          contractVersion: controls.version,
          outputFormat: 'jpg',
        },
      },
      ...overrides,
    });
  }
  it('carries reviewed ratio/count/format and canonical IDs without legacy provider defaults', () => {
    const request = build();
    expect(request).toMatchObject({
      model: model.key,
      text: 'A product',
      brandId: 'brand-1',
      outputs: 4,
      references: ['image-1'],
      harness: false,
      crunControls: {
        contractVersion: controls.version,
        aspectRatio: '21:9',
        resolution: '2K',
        outputFormat: 'jpg',
      },
    });
    for (const key of [
      'width',
      'height',
      'format',
      'quality',
      'seed',
      'duration',
      'isAudioEnabled',
      'brand',
      'folder',
    ])
      expect(request).not.toHaveProperty(key);
  });
  it('preserves auto exactly when an authorized reference ID is selected', () => {
    const settings = {
      ...getDefaultStudioGenerateSettings('image'),
      modelKey: model.key,
      aspectRatio: 'auto',
      resolution: '1K',
      crunControls: {
        modelKey: model.key,
        contractVersion: controls.version,
        aspectRatio: 'auto',
      },
    };
    expect(build({ settings })?.crunControls.aspectRatio).toBe('auto');
    expect(build({ settings, references: [] })).toBeNull();
  });
  it('rejects duplicate and excessive references before preview', () => {
    expect(build({ references: ['one', 'one'] })).toBeNull();
    expect(
      build({ references: Array.from({ length: 9 }, (_, i) => `image-${i}`) }),
    ).toBeNull();
  });
  it('rejects stale residual aspect and contract versions', () => {
    const settings = {
      ...getDefaultStudioGenerateSettings('image'),
      modelKey: model.key,
      resolution: '1K',
      aspectRatio: '21:9',
      crunControls: {
        modelKey: model.key,
        contractVersion: controls.version,
        aspectRatio: '1:1',
      },
    };
    expect(build({ settings })).toBeNull();
    expect(
      build({
        settings: {
          ...settings,
          crunControls: { modelKey: model.key, contractVersion: 'old' },
        },
      }),
    ).toBeNull();
  });
});

function controlsFor(endpoint = 'kling/v2-5-turbo-pro'): CrunInputControls {
  const kling = endpoint === 'kling/v2-5-turbo-pro';
  return {
    endpoint,
    version: 'reviewed-video-v1',
    mediaKind: 'video',
    maxOutputs: 4,
    isBatchSupported: false,
    isAutoAspectReferenceRequired: false,
    referenceRoles: kling ? { img_urls: 'image' } : {},
    videoRules: {
      referenceMode: kling ? 'start-end' : 'none',
      omitAspectRatioWithReferences: kling,
      availableDurations: kling ? [5, 10] : [8],
    },
    fields: {
      prompt: {
        type: 'string',
        isRequired: true,
        minLength: 1,
        maxLength: kling ? 2500 : 5000,
      },
      duration: {
        type: 'integer',
        isRequired: false,
        enum: kling ? [5, 10] : [4, 6, 8],
        default: kling ? 5 : 8,
      },
      aspect_ratio: {
        type: 'string',
        isRequired: false,
        enum: kling ? ['1:1', '16:9', '9:16'] : ['16:9', '9:16'],
        default: '16:9',
      },
      ...(kling
        ? {
            negative_prompt: {
              type: 'string' as const,
              isRequired: false,
              maxLength: 2000,
            },
            cfg_scale: {
              type: 'number' as const,
              isRequired: false,
              minimum: 0,
              maximum: 1,
              default: 0.5,
            },
            img_urls: {
              type: 'array' as const,
              isRequired: false,
              format: 'uri' as const,
              minItems: 1,
              maxItems: 2,
            },
          }
        : {
            resolution: {
              type: 'string' as const,
              isRequired: false,
              enum: ['720p', '1080p', '4k'],
              default: '720p',
            },
            translate_prompt: {
              type: 'boolean' as const,
              isRequired: false,
              default: true,
            },
          }),
    },
  };
}

describe('canonical Studio Crun video requests', () => {
  function request(
    endpoint = 'kling/v2-5-turbo-pro',
    overrides: Partial<
      Parameters<typeof buildStudioCrunVideoQuoteRequest>[0]
    > = {},
  ) {
    const controls = controlsFor(endpoint);
    const model = {
      key: `crun/${endpoint}`,
      provider: 'crun',
      inputControls: controls,
    } as IModel;
    return buildStudioCrunVideoQuoteRequest({
      model,
      settings: {
        ...getDefaultStudioGenerateSettings('video'),
        modelKey: model.key,
        duration: endpoint.startsWith('kling/') ? 5 : 8,
        aspectRatio: '16:9',
        resolution: endpoint.startsWith('kling/') ? '' : '720p',
        crunControls: {
          modelKey: model.key,
          contractVersion: controls.version,
        },
      },
      promptText: '  bird in motion  ',
      brandId: 'brand-1',
      references: [],
      ...overrides,
    });
  }
  it('sends canonical text mode and never forwards legacy audio, size or tags', () => {
    const body = request();
    expect(body).toMatchObject({
      model: 'crun/kling/v2-5-turbo-pro',
      text: 'bird in motion',
      outputs: 1,
      crunControls: { duration: 5, aspectRatio: '16:9', guidanceScale: 0.5 },
    });
    for (const field of [
      'height',
      'width',
      'format',
      'tags',
      'speech',
      'sounds',
      'isAudioEnabled',
      'resolution',
    ])
      expect(body).not.toHaveProperty(field);
  });
  it('binds distinct frame IDs in order and omits aspect only when frames are present', () => {
    expect(
      request('kling/v2-5-turbo-pro', {
        references: ['start-owned'],
        endFrameId: 'end-owned',
        parentId: 'start-owned',
      }),
    ).toMatchObject({
      references: ['start-owned'],
      endFrame: 'end-owned',
      parentId: 'start-owned',
      crunControls: { duration: 5 },
    });
    expect(
      request('kling/v2-5-turbo-pro', {
        references: ['start-owned'],
        endFrameId: 'end-owned',
      })?.crunControls,
    ).not.toHaveProperty('aspectRatio');
  });
  it.each([
    { references: ['one', 'two'] },
    { references: [], endFrameId: 'end' },
    { references: ['same'], endFrameId: 'same' },
    { references: ['https://secret.example/image'] },
    { references: ['start'], parentId: 'foreign' },
  ])('rejects invalid frame preparation %j', (overrides) => {
    expect(request('kling/v2-5-turbo-pro', overrides)).toBeNull();
  });
  it('rejects every Veo reference and keeps its reviewed text defaults', () => {
    expect(request('google/veo3-1-fast-t2v')?.crunControls).toEqual({
      contractVersion: 'reviewed-video-v1',
      duration: 8,
      aspectRatio: '16:9',
      resolution: '720p',
      translatePrompt: true,
    });
    expect(
      request('google/veo3-1-fast-t2v', { references: ['start'] }),
    ).toBeNull();
  });
  it.each([4, 6])(
    'rejects unreviewed Veo %s seconds before quote',
    (duration) => {
      const controls = controlsFor('google/veo3-1-fast-t2v');
      const modelKey = `crun/${controls.endpoint}`;
      expect(
        request(controls.endpoint, {
          settings: {
            ...getDefaultStudioGenerateSettings('video'),
            modelKey,
            duration,
            resolution: '720p',
            aspectRatio: '16:9',
            crunControls: { modelKey, contractVersion: controls.version },
          },
        }),
      ).toBeNull();
    },
  );
  it('retains group output count, numeric zero and false without pricing arithmetic', () => {
    const controls = controlsFor('google/veo3-1-fast-t2v');
    const modelKey = `crun/${controls.endpoint}`;
    const body = request(controls.endpoint, {
      settings: {
        ...getDefaultStudioGenerateSettings('video'),
        modelKey,
        duration: 8,
        resolution: '4k',
        aspectRatio: '9:16',
        outputs: 4,
        crunControls: {
          modelKey,
          contractVersion: controls.version,
          translatePrompt: false,
        },
      },
    });
    expect(body).toMatchObject({
      outputs: 4,
      crunControls: { translatePrompt: false, resolution: '4k' },
    });
    const kling = controlsFor();
    const key = `crun/${kling.endpoint}`;
    expect(
      request(kling.endpoint, {
        settings: {
          ...getDefaultStudioGenerateSettings('video'),
          modelKey: key,
          duration: 10,
          resolution: '',
          aspectRatio: '1:1',
          crunControls: {
            modelKey: key,
            contractVersion: kling.version,
            guidanceScale: 0,
            negativePrompt: '  blur  ',
          },
        },
      })?.crunControls,
    ).toMatchObject({ duration: 10, guidanceScale: 0, negativePrompt: 'blur' });
  });
});
