/** Layout styles for the content-card view; colours come from staticSurfaceCss. */
export const CARD_APP_STYLES = `
*{box-sizing:border-box}body{margin:0;padding:16px;background:var(--gf-bg-primary);color:var(--gf-text-primary);font-family:var(--gf-font-sans)}
header{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:12px}h1{font-size:16px;margin:0;text-transform:capitalize}.brand{font-size:12px;color:var(--gf-text-muted);letter-spacing:.08em}
.summary{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 12px}.pill{font-size:11px;padding:3px 8px;border:1px solid var(--gf-border);color:var(--gf-text-muted)}
#cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:12px}#cards.calendar{grid-template-columns:repeat(auto-fill,minmax(min(100%,150px),1fr));gap:8px}#cards.posts{grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr))}
.card{border:1px solid var(--gf-border);background:var(--gf-bg-secondary);overflow:hidden;min-width:0}
.copy{padding:16px}h2{font-size:15px;line-height:1.4;margin:8px 0;overflow-wrap:anywhere}.meta{font-size:11px;color:var(--gf-text-muted);text-transform:uppercase;letter-spacing:.04em}.description{font-size:13px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere;margin:10px 0}.id{font-size:11px;overflow-wrap:anywhere;color:var(--gf-text-muted)}
img,video{display:block;width:100%;max-height:380px;object-fit:contain;background:var(--gf-bg-tertiary)}audio{width:100%;margin-top:12px}.metric{font-size:30px;font-variant-numeric:tabular-nums}.notice{font-size:13px;color:var(--gf-text-muted);white-space:pre-wrap;overflow-wrap:anywhere}
a{color:var(--gf-text-primary);font-size:12px;text-underline-offset:3px}a:focus-visible,button:focus-visible{outline:2px solid var(--gf-text-primary);outline-offset:3px}
footer{margin-top:12px}details summary{cursor:pointer;font-size:12px}details .description{max-height:280px;overflow:auto}
.day{border:1px solid var(--gf-border);background:var(--gf-bg-secondary);padding:10px;min-height:96px;display:flex;flex-direction:column;gap:6px}.day.gap{border-style:dashed;background:transparent}.day.today{border-color:var(--gf-text-primary)}
.day-head{display:flex;justify-content:space-between;align-items:baseline;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--gf-text-muted)}.day-head strong{font-size:15px;color:var(--gf-text-primary);letter-spacing:0}
.slot{border-left:2px solid var(--gf-text-primary);padding:4px 0 4px 8px;font-size:12px;line-height:1.45}.slot .meta{font-size:10px}.slot p{margin:2px 0 0;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere}.gap-label{font-size:12px;color:var(--gf-text-muted);margin:auto 0}
.post-head{display:flex;align-items:center;gap:10px;padding:14px 16px 0}.avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:var(--gf-text-primary);color:var(--gf-bg-primary);font-weight:600;font-size:13px;flex:none}.post-head .who{display:flex;flex-direction:column;min-width:0}.post-head .who span{font-size:11px;color:var(--gf-text-muted)}.status{margin-left:auto;font-size:10px;text-transform:uppercase;letter-spacing:.04em;padding:2px 6px;border:1px solid var(--gf-border);color:var(--gf-text-muted)}
.post-body{padding:0 16px}.post-body .description{margin:12px 0}.post .media-frame{border-top:1px solid var(--gf-border);border-bottom:1px solid var(--gf-border)}
.zoom{all:unset;display:block;width:100%;cursor:zoom-in}.zoom:focus-visible{outline:2px solid var(--gf-text-primary);outline-offset:-2px}
.pending{padding:24px 16px;display:flex;flex-direction:column;gap:10px;background:var(--gf-bg-tertiary)}.bar{height:4px;background:var(--gf-border);overflow:hidden}.bar span{display:block;height:100%;width:var(--progress,30%);background:var(--gf-text-primary);transition:width .4s ease}.bar.indeterminate span{animation:gf-indeterminate 1.4s ease-in-out infinite}
@keyframes gf-indeterminate{0%{transform:translateX(-100%)}100%{transform:translateX(330%)}}
.lightbox{position:fixed;inset:0;z-index:10;background:rgba(0,0,0,.88);display:flex;align-items:center;justify-content:center;padding:24px}.lightbox img{max-width:100%;max-height:100%;width:auto;background:transparent}.lightbox .close{position:absolute;top:12px;right:12px;font:inherit;font-size:13px;padding:6px 10px;background:var(--gf-bg-secondary);color:var(--gf-text-primary);border:1px solid var(--gf-border);cursor:pointer}
@media (prefers-reduced-motion:reduce){.bar.indeterminate span{animation:none;width:100%;opacity:.5}.bar span{transition:none}}
`;
