/**
 * `bun run pricing:rates:pull [--model <owner/name>] [--dry-run]`
 *
 * Adds or refreshes entries of the checked-in rate sheet from the same
 * structured source the daily watcher reads: the Replicate model page's
 * `billingConfig.current_tiers[]`, mapped onto the model's own input schema.
 * Prints a per-variant diff against the sheet and rewrites
 * `packages/pricing/src/reviewed-rates/reviewed-rate-sheet.data.ts`. Adding a
 * model is: run this, review the diff, merge.
 *
 * Needs `REPLICATE_KEY` for the model's input schema. Public list prices only.
 */
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describeProviderRateChanges } from '../../packages/pricing/src/reviewed-rate-hash';
import {
  extractReplicateBillingTiers,
  mapReplicateBillingTiers,
} from '../../packages/pricing/src/reviewed-rates/replicate-billing-tiers';
import { REVIEWED_RATE_SHEET_ENTRIES } from '../../packages/pricing/src/reviewed-rates/reviewed-rate-sheet.data';
import type { ReviewedRateSheetEntry } from '../../packages/pricing/src/reviewed-rates/reviewed-rate-sheet.types';

const SHEET_PATH = resolve(
  import.meta.dir,
  '../../packages/pricing/src/reviewed-rates/reviewed-rate-sheet.data.ts',
);
const HEADER = `import type { ReviewedRateSheetEntry } from './reviewed-rate-sheet.types';

/**
 * Public provider list prices, one entry per \`provider\` + \`endpoint\`.
 * Generated by \`bun run pricing:rates:pull [--model <key>]\`: review the
 * printed diff, run biome and merge. The watcher keeps each entry verified and
 * alerts when the provider's page stops matching it.
 */
export const REVIEWED_RATE_SHEET_ENTRIES: readonly ReviewedRateSheetEntry[] = `;

function parseArgs(argv: string[]): { isDryRun: boolean; model?: string } {
  const modelIndex = argv.indexOf('--model');
  const model = modelIndex >= 0 ? argv[modelIndex + 1] : undefined;
  if (modelIndex >= 0 && (!model || model.startsWith('--')))
    throw new Error('--model needs a value, for example --model owner/name');
  return { isDryRun: argv.includes('--dry-run'), model };
}

async function fetchInputProperties(
  endpoint: string,
  token: string,
): Promise<Record<string, unknown>> {
  const response = await fetch(
    `https://api.replicate.com/v1/models/${endpoint}`,
    {
      headers: { Authorization: `Bearer ${token}` },
    },
  );
  if (!response.ok)
    throw new Error(
      `Replicate API returned ${response.status} for ${endpoint}`,
    );
  const model = (await response.json()) as {
    latest_version?: {
      openapi_schema?: {
        components?: {
          schemas?: { Input?: { properties?: Record<string, unknown> } };
        };
      };
    };
  };
  return (
    model.latest_version?.openapi_schema?.components?.schemas?.Input
      ?.properties ?? {}
  );
}

async function pullEntry(
  endpoint: string,
  token: string,
  existing: ReviewedRateSheetEntry | undefined,
): Promise<ReviewedRateSheetEntry> {
  const sourceUrl = `https://replicate.com/${endpoint}`;
  const page = await fetch(sourceUrl, { headers: { Accept: 'text/html' } });
  if (!page.ok) throw new Error(`${sourceUrl} returned ${page.status}`);
  const tiers = extractReplicateBillingTiers(await page.text());
  if (!tiers) throw new Error(`${sourceUrl} carries no billingConfig`);
  const mapping = mapReplicateBillingTiers(
    tiers,
    await fetchInputProperties(endpoint, token),
    endpoint,
  );
  if (mapping.status === 'failed')
    throw new Error(`cannot map ${endpoint}: ${mapping.reason}`);
  return {
    endpoint,
    provider: 'replicate',
    rates: mapping.rates,
    ...(mapping.variantRules ? { variantRules: mapping.variantRules } : {}),
    sourceUrl,
    verifiedAt: new Date().toISOString(),
    ...(existing?.invariantSelectors
      ? { invariantSelectors: existing.invariantSelectors }
      : {}),
  };
}

async function main(): Promise<void> {
  const { isDryRun, model } = parseArgs(process.argv.slice(2));
  // biome-ignore lint/suspicious/noUndeclaredEnvVars: operator script, token is read from the shell
  const token = process.env.REPLICATE_KEY;
  if (!token)
    throw new Error('REPLICATE_KEY is required to read input schemas');
  const targets = model
    ? [model]
    : REVIEWED_RATE_SHEET_ENTRIES.filter(
        (entry) => entry.provider === 'replicate',
      ).map((entry) => entry.endpoint);
  const entries = new Map(
    REVIEWED_RATE_SHEET_ENTRIES.map((entry) => [
      `${entry.provider}:${entry.endpoint}`,
      entry,
    ]),
  );
  let failures = 0;

  for (const endpoint of targets) {
    const key = `replicate:${endpoint}`;
    const existing = entries.get(key);
    try {
      const pulled = await pullEntry(endpoint, token, existing);
      const changes = describeProviderRateChanges(
        existing?.rates ?? [],
        pulled.rates,
      );
      console.log(
        `${endpoint}: ${existing ? (changes.length ? 'changed' : 'unchanged') : 'new'}`,
      );
      for (const change of changes)
        console.log(
          `  ${change.variant}: ${change.oldPriceUsd ?? 'none'} -> ${change.newPriceUsd ?? 'none'} per ${change.unit}`,
        );
      entries.set(key, pulled);
    } catch (error: unknown) {
      failures += 1;
      console.error(
        `${endpoint}: kept as is (${error instanceof Error ? error.message : 'unknown error'})`,
      );
    }
  }

  if (isDryRun) return;
  const sorted = [...entries.values()].sort((left, right) =>
    `${left.provider}:${left.endpoint}`.localeCompare(
      `${right.provider}:${right.endpoint}`,
    ),
  );
  writeFileSync(SHEET_PATH, `${HEADER}${JSON.stringify(sorted, null, 2)};\n`);
  spawnSync('bunx', ['biome', 'format', '--write', SHEET_PATH], {
    stdio: 'inherit',
  });
  if (failures > 0) process.exitCode = 1;
}

await main();
