import type { ReviewedRateSheetEntry } from './reviewed-rate-sheet.types';

/**
 * Public provider list prices, one entry per `provider` + `endpoint`.
 * Generated by `bun run pricing:rates:pull [--model <key>]`: review the
 * printed diff, run biome and merge. The watcher keeps each entry verified and
 * alerts when the provider's page stops matching it.
 */
export const REVIEWED_RATE_SHEET_ENTRIES: readonly ReviewedRateSheetEntry[] = [
  {
    endpoint: 'black-forest-labs/flux-3-image',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.0205,
        when: {
          resolution: '768sq',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.024,
        when: {
          resolution: '1k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.035,
        when: {
          resolution: '1.5k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.05,
        when: {
          resolution: '2k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.3035,
        when: {
          resolution: '4k',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/black-forest-labs/flux-3-image',
    verifiedAt: '2026-10-01T00:00:00.000Z',
  },
  {
    endpoint: 'black-forest-labs/flux-3-image-edit',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.0205,
        when: {
          resolution: '768sq',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.024,
        when: {
          resolution: '1k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.035,
        when: {
          resolution: '1.5k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.05,
        when: {
          resolution: '2k',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.3035,
        when: {
          resolution: '4k',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/black-forest-labs/flux-3-image',
    verifiedAt: '2026-10-01T00:00:00.000Z',
  },
  {
    endpoint: 'black-forest-labs/flux-kontext-pro',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.04,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/black-forest-labs/flux-kontext-pro',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'bytedance/seedream-4',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.03,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/bytedance/seedream-4',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'bytedance/seedream-4.5',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.04,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/bytedance/seedream-4.5',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'google/nano-banana',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.039,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/google/nano-banana',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'google/nano-banana-pro',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.15,
        when: {
          resolution: '1K',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.15,
        when: {
          resolution: '2K',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.3,
        when: {
          resolution: '4K',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/google/nano-banana-pro',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'google/veo-3.1',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.4,
        when: {
          generate_audio: true,
        },
      },
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.2,
        when: {
          generate_audio: false,
        },
      },
    ],
    sourceUrl: 'https://replicate.com/google/veo-3.1',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'google/veo-3.1-fast',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.15,
        when: {
          generate_audio: true,
        },
      },
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.1,
        when: {
          generate_audio: false,
        },
      },
    ],
    sourceUrl: 'https://replicate.com/google/veo-3.1-fast',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'ideogram-ai/ideogram-4-5',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.06,
        when: {
          quality: 'medium',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/ideogram-ai/ideogram-4-5',
    verifiedAt: '2026-10-01T00:00:00.000Z',
  },
  {
    endpoint: 'ideogram-ai/ideogram-v3-balanced',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.06,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/ideogram-ai/ideogram-v3-balanced',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'ideogram-ai/ideogram-v3-quality',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.09,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/ideogram-ai/ideogram-v3-quality',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'kwaivgi/kling-avatar-v2',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.056,
        when: {
          mode: 'standard',
        },
      },
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.11,
        when: {
          mode: 'pro',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/kwaivgi/kling-avatar-v2',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'kwaivgi/kling-v2.1',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.05,
        when: {
          mode: 'standard',
        },
      },
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.09,
        when: {
          mode: 'pro',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/kwaivgi/kling-v2.1',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'kwaivgi/kling-v2.1-master',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.28,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/kwaivgi/kling-v2.1-master',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'kwaivgi/kling-v2.5-turbo-pro',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.07,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/kwaivgi/kling-v2.5-turbo-pro',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'luma/reframe-image',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.01,
        when: {
          model: 'photon-flash-1',
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.03,
        when: {
          model: 'photon-1',
        },
      },
    ],
    sourceUrl: 'https://replicate.com/luma/reframe-image',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'luma/reframe-video',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        isPerOutput: true,
        unit: 'second',
        unitPriceUsd: 0.06,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/luma/reframe-video',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'minimax/hailuo-2.3-fast',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.19,
        when: {
          resolution: '768P',
          duration: 6,
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.32,
        when: {
          resolution: '768P',
          duration: 10,
        },
      },
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.33,
        when: {
          resolution: '1080P',
          duration: 6,
        },
      },
    ],
    sourceUrl: 'https://replicate.com/minimax/hailuo-2.3-fast',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'qwen/qwen-image',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.025,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/qwen/qwen-image',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
  {
    endpoint: 'runwayml/gen4-image-turbo',
    provider: 'replicate',
    rates: [
      {
        component: 'output',
        unit: 'output',
        unitPriceUsd: 0.03,
        when: {},
      },
    ],
    sourceUrl: 'https://replicate.com/runwayml/gen4-image-turbo',
    verifiedAt: '2026-09-30T00:00:00.000Z',
  },
];
