export type EnvMode = 'local' | 'staging' | 'production';

export interface EnvTarget {
  id: string;
  path: string;
  generatedFileByMode: Record<EnvMode, string>;
  sharedKeys: string[];
  directKeys: string[];
  mappedKeys: Record<string, string>;
  localLegacyFile?: string;
}

export interface EnvSection {
  title: string;
  keys: string[];
}

export const DEPRECATED_ENV_KEYS = [
  'MONGODB_URI',
  'SENTRY_AUTH_TOKEN_API',
  'SENTRY_AUTH_TOKEN_FILES',
  'SENTRY_AUTH_TOKEN_MCP',
  'SENTRY_AUTH_TOKEN_NOTIFICATIONS',
  'SENTRY_DSN_WORKERS',
  'SENTRY_DSN_DISCORD',
  'SENTRY_DSN_SLACK',
  'SENTRY_DSN_TELEGRAM',
  'SENTRY_DSN_CLIPS',
  'MONGODB_URL',
  // Subscription credit grants come from the Stripe price
  // (`included_monthly_credits` metadata), never from a deployment-wide
  // constant that is unrelated to what the customer paid.
  'STRIPE_MONTHLY_CREDITS',
  'STRIPE_YEARLY_CREDITS',
  // The Creator tier was renamed to Pro; the price it pointed at is now
  // STRIPE_PRICE_SUBSCRIPTION_PRO_MONTHLY.
  'STRIPE_PRICE_SUBSCRIPTION_CREATOR_MONTHLY',
  // Never read by any service.
  'STRIPE_COUPON_CREDITS_PACKS_V2_PRO',
  'STRIPE_COUPON_CREDITS_PACKS_V2_ENTERPRISE',
] as const;

const frontendSharedKeys = [
  'API_URL',
  'NEXT_PUBLIC_API_ENDPOINT',
  'NEXT_PUBLIC_API_URL',
  'NEXT_PUBLIC_CDN_URL',
  'NEXT_PUBLIC_BETTER_AUTH_ENABLED',
  'NEXT_PUBLIC_GENFEED_CLOUD',
  'NEXT_PUBLIC_GENFEED_EDITION',
  'NEXT_PUBLIC_GENFEED_LICENSE_KEY',
  'NEXT_PUBLIC_MCP_ENDPOINT',
  'NEXT_PUBLIC_PLAYWRIGHT_TEST',
  'NEXT_PUBLIC_POSTHOG_HOST',
  'NEXT_PUBLIC_POSTHOG_KEY',
  'NEXT_PUBLIC_SENTRY_ENVIRONMENT',
  'NEXT_PUBLIC_WS_ENDPOINT',
  'SENTRY_AUTH_TOKEN',
  'SENTRY_ORG',
  'SENTRY_ENVIRONMENT',
] as const;

const backendSharedKeys = [
  'BETTER_AUTH_ENABLED',
  'BETTER_AUTH_SECRET',
  'BETTER_AUTH_TRUSTED_ORIGINS',
  'BETTER_AUTH_URL',
  'DATABASE_URL',
  'GENFEEDAI_API_KEY',
  'GENFEEDAI_API_PUBLIC_URL',
  'GENFEEDAI_API_URL',
  'GENFEEDAI_APP_URL',
  'GENFEEDAI_CDN_URL',
  'GENFEEDAI_MCP_PUBLIC_URL',
  'GENFEED_CLOUD',
  'GENFEEDAI_MICROSERVICES_FILES_URL',
  'GENFEEDAI_MICROSERVICES_MCP_URL',
  'GENFEEDAI_MICROSERVICES_NOTIFICATIONS_URL',
  'GENFEEDAI_PUBLIC_URL',
  'GENFEEDAI_WEBHOOKS_URL',
  'NEXT_PUBLIC_GENFEED_CLOUD',
  'REDIS_URL',
  'SENTRY_AUTH_TOKEN',
  'SENTRY_ENVIRONMENT',
  'TOKEN_ENCRYPTION_KEY',
  'WEBSOCKET_URL',
] as const;

export const ENV_TARGETS: EnvTarget[] = [
  {
    id: 'app',
    path: 'apps/app',
    generatedFileByMode: {
      local: 'apps/app/.env.local',
      staging: 'apps/app/.env.staging',
      production: 'apps/app/.env.production',
    },
    localLegacyFile: 'apps/app/.env',
    sharedKeys: [...frontendSharedKeys],
    // Checkout runs in the browser: `@genfeedai/pricing` reads these at module
    // load to fill `plan.stripePriceId`, and the app posts that ID to the API.
    // Without them every paid plan renders as unavailable. Only `apps/app`
    // needs them — the website consumes `@genfeedai/pricing` for display only.
    directKeys: [
      'NEXT_PUBLIC_STRIPE_PRICE_PAYG',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_ENTERPRISE_MONTHLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_PRO_MONTHLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_PRO_YEARLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_SCALE_MONTHLY',
      'NEXT_PUBLIC_TTS_ENABLED',
    ],
    mappedKeys: {
      APP_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL:
        'BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
      APP_MEDIUM_REDIRECT_URI: 'MEDIUM_REDIRECT_URI',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FALLBACK_REDIRECT_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FALLBACK_REDIRECT_URL',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FORCE_REDIRECT_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FORCE_REDIRECT_URL',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_URL',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FALLBACK_REDIRECT_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FALLBACK_REDIRECT_URL',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
      APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_URL:
        'NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_URL',
      APP_NEXT_PUBLIC_SENTRY_DSN: 'NEXT_PUBLIC_SENTRY_DSN',
      APP_PORT: 'PORT',
      APP_SENTRY_PROJECT: 'SENTRY_PROJECT',
    },
  },
  {
    id: 'website',
    path: 'apps/website',
    generatedFileByMode: {
      local: 'apps/website/.env.local',
      staging: 'apps/website/.env.staging',
      production: 'apps/website/.env.production',
    },
    localLegacyFile: 'apps/website/.env',
    sharedKeys: [...frontendSharedKeys],
    directKeys: [
      'NEXT_PUBLIC_APPS_ADMIN_ENDPOINT',
      'NEXT_PUBLIC_APPS_APP_ENDPOINT',
      'NEXT_PUBLIC_APPS_MARKETPLACE_ENDPOINT',
      'NEXT_PUBLIC_APPS_WEBSITE_ENDPOINT',
      'NEXT_PUBLIC_ASSETS_ENDPOINT',
      'NEXT_PUBLIC_CALENDLY_URL',
    ],
    mappedKeys: {
      WEBSITE_NEXT_PUBLIC_SENTRY_DSN: 'NEXT_PUBLIC_SENTRY_DSN',
      WEBSITE_PORT: 'PORT',
      WEBSITE_SENTRY_PROJECT: 'SENTRY_PROJECT',
    },
  },
  {
    id: 'api',
    path: 'apps/server/api',
    generatedFileByMode: {
      local: 'apps/server/api/.env.local',
      staging: 'apps/server/api/.env.staging',
      production: 'apps/server/api/.env.production',
    },
    localLegacyFile: 'apps/server/api/.env',
    sharedKeys: [...backendSharedKeys],
    directKeys: [
      'ARGIL_KEY',
      'ARGIL_WEBHOOK_SECRET',
      'ANTHROPIC_API_KEY',
      'AWS_ACCESS_KEY_ID',
      'AWS_REGION',
      'AWS_S3_BUCKET',
      'AWS_SECRET_ACCESS_KEY',
      'BULL_BOARD_AUTH_TOKEN',
      'CHROME_EXTENSION_ID',
      'ELEVENLABS_API_KEY',
      'ELEVENLABS_MODEL',
      'FACEBOOK_API_VERSION',
      'FACEBOOK_APP_ID',
      'FACEBOOK_APP_SECRET',
      'FACEBOOK_GRAPH_URL',
      'FACEBOOK_REDIRECT_URI',
      'FANVUE_CLIENT_ID',
      'FANVUE_CLIENT_SECRET',
      'FANVUE_REDIRECT_URI',
      'GENFEED_LICENSE_KEY',
      'GIPHY_API_KEY',
      'GOOGLE_ADS_CLIENT_ID',
      'GOOGLE_ADS_CLIENT_SECRET',
      'GOOGLE_ADS_DEVELOPER_TOKEN',
      'GOOGLE_ADS_REDIRECT_URI',
      'HEDRA_KEY',
      'HEYGEN_KEY',
      'INSTAGRAM_API_VERSION',
      'INSTAGRAM_APP_ID',
      'INSTAGRAM_APP_SECRET',
      'INSTAGRAM_CLIENT_ID',
      'INSTAGRAM_CLIENT_SECRET',
      'INSTAGRAM_GRAPH_URL',
      'INSTAGRAM_REDIRECT_URI',
      'KLINGAI_KEY',
      'KLINGAI_MODEL',
      'KLINGAI_SECRET',
      'LEONARDO_KEY',
      'LOGO_DEV_PUBLISHABLE_KEY',
      'LINKEDIN_CLIENT_ID',
      'LINKEDIN_CLIENT_SECRET',
      'LINKEDIN_REDIRECT_URI',
      'MARKETPLACE_API_URL',
      'MEDIUM_CLIENT_ID',
      'MEDIUM_CLIENT_SECRET',
      'NEWS_API_KEY',
      'NEWS_API_URL',
      'OPENAI_API_KEY',
      'OPENAI_CODEX_REDIRECT_URI',
      'OPENROUTER_API_KEY',
      'PINTEREST_CLIENT_ID',
      'PINTEREST_CLIENT_SECRET',
      'PINTEREST_REDIRECT_URI',
      'POSTHOG_HOST',
      'POSTHOG_PROJECT_API_KEY',
      'REDDIT_CLIENT_ID',
      'REDDIT_CLIENT_SECRET',
      'REDDIT_REDIRECT_URI',
      'REDDIT_USER_AGENT',
      'REPLICATE_KEY',
      'REPLICATE_MODELS_TRAINER',
      'REPLICATE_MODEL_HARDWARE',
      'REPLICATE_MODEL_VISIBILITY',
      'REPLICATE_OWNER',
      'REPLICATE_TARGET_FPS',
      'REPLICATE_TARGET_RESOLUTION',
      'REPLICATE_WEBHOOK_SIGNING_SECRET',
      'VERCEL_WEBHOOK_SECRET',
      'SLACK_CLIENT_ID',
      'SLACK_CLIENT_SECRET',
      'SLACK_REDIRECT_URI',
      'SLACK_SIGNING_SECRET',
      'SOLANA_KEY',
      'SOLANA_URL',
      'STRIPE_API_VERSION',
      'STRIPE_PAYG_CREDITS',
      'STRIPE_PRICE_PAYG',
      'STRIPE_PRICE_SKILLS_PRO',
      'STRIPE_PRICE_SUBSCRIPTION_ENTERPRISE_MONTHLY',
      'STRIPE_PRICE_SUBSCRIPTION_PRO_MONTHLY',
      'STRIPE_PRICE_SUBSCRIPTION_PRO_YEARLY',
      'STRIPE_PRICE_SUBSCRIPTION_SCALE_MONTHLY',
      'STRIPE_PROMOTION_CODE_LAUNCH',
      'STRIPE_PROMOTION_CODE_SKILLS_PRO',
      'STRIPE_PUBLISHABLE_KEY',
      'STRIPE_SECRET_KEY',
      'STRIPE_WEBHOOK_SIGNING_SECRET',
      'TIKTOK_CLIENT_KEY',
      'TIKTOK_CLIENT_SECRET',
      'THREADS_API_VERSION',
      'THREADS_CLIENT_ID',
      'THREADS_CLIENT_SECRET',
      'THREADS_GRAPH_URL',
      'THREADS_REDIRECT_URI',
      'TRAINING_CUSTOM_MODEL_CREDITS_COST',
      'TRAINING_TRAINING_CREDITS_COST',
      'TWITCH_CLIENT_ID',
      'TWITTER_BEARER_TOKEN',
      'TWITTER_CLIENT_ID',
      'TWITTER_CLIENT_SECRET',
      'TWITTER_CONSUMER_KEY',
      'TWITTER_CONSUMER_SECRET',
      'TWITTER_REDIRECT_URI',
      'X_ADS_API_KEY',
      'X_ADS_API_SECRET',
      'X_ADS_REDIRECT_URI',
      'X_ADS_REPOSITORY_COMMERCIAL_USE_APPROVED',
      'X_ADS_REPOSITORY_ENTITLEMENT_CONFIRMED',
      'YOUTUBE_API_KEY',
      'YOUTUBE_CLIENT_ID',
      'YOUTUBE_CLIENT_SECRET',
      'YOUTUBE_REDIRECT_URI',
      'RESTREAM_CLIENT_ID',
      'RESTREAM_CLIENT_SECRET',
      'RESTREAM_REDIRECT_URI',
    ],
    mappedKeys: {
      API_PORT: 'PORT',
      API_SENTRY_DSN: 'SENTRY_DSN',
      API_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'files',
    path: 'apps/server/files',
    generatedFileByMode: {
      local: 'apps/server/files/.env.local',
      staging: 'apps/server/files/.env.staging',
      production: 'apps/server/files/.env.production',
    },
    localLegacyFile: 'apps/server/files/.env',
    sharedKeys: [...backendSharedKeys],
    directKeys: [
      'AWS_ACCESS_KEY_ID',
      'AWS_IMAGE_COMPRESSION',
      'AWS_PROFILE',
      'AWS_REGION',
      'AWS_S3_BUCKET',
      'AWS_SECRET_ACCESS_KEY',
      'TEMP_DIR',
    ],
    mappedKeys: {
      FILES_PORT: 'PORT',
      FILES_SENTRY_DSN: 'SENTRY_DSN',
      FILES_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'mcp',
    path: 'apps/server/mcp',
    generatedFileByMode: {
      local: 'apps/server/mcp/.env.local',
      staging: 'apps/server/mcp/.env.staging',
      production: 'apps/server/mcp/.env.production',
    },
    localLegacyFile: 'apps/server/mcp/.env',
    sharedKeys: [...backendSharedKeys],
    directKeys: ['POSTHOG_HOST', 'POSTHOG_PROJECT_API_KEY', 'VERSION'],
    mappedKeys: {
      MCP_PORT: 'PORT',
      MCP_SENTRY_DSN: 'SENTRY_DSN',
      MCP_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'notifications',
    path: 'apps/server/notifications',
    generatedFileByMode: {
      local: 'apps/server/notifications/.env.local',
      staging: 'apps/server/notifications/.env.staging',
      production: 'apps/server/notifications/.env.production',
    },
    localLegacyFile: 'apps/server/notifications/.env',
    sharedKeys: [...backendSharedKeys],
    directKeys: [
      'API_BASE_URL',
      'API_SECRET_KEY',
      'DISCORD_BOT_TOKEN',
      'DISCORD_CHANNEL_ID_DEPLOYMENTS',
      'DISCORD_CHANNEL_ID_POSTS',
      'DISCORD_CHANNEL_ID_STUDIO',
      'DISCORD_CHANNEL_ID_USERS',
      'DISCORD_CLIENT_ID',
      'DISCORD_GUILD_ID',
      'RESEND_API_KEY',
      'RESEND_FROM_EMAIL',
      'RESEND_REPLY_TO_EMAIL',
      'TELEGRAM_ADMIN_IDS',
      'TELEGRAM_BOT_TOKEN',
      'TELEGRAM_BOT_USERNAME',
      'TWITCH_CLIENT_ID',
      'VERSION',
    ],
    mappedKeys: {
      NOTIFICATIONS_PORT: 'PORT',
      NOTIFICATIONS_SENTRY_DSN: 'SENTRY_DSN',
      NOTIFICATIONS_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'workers',
    path: 'apps/server/workers',
    generatedFileByMode: {
      local: 'apps/server/workers/.env.local',
      staging: 'apps/server/workers/.env.staging',
      production: 'apps/server/workers/.env.production',
    },
    sharedKeys: [
      'DATABASE_URL',
      'REDIS_URL',
      'SENTRY_AUTH_TOKEN',
      'SENTRY_ENVIRONMENT',
    ],
    directKeys: [
      'AWS_ACCESS_KEY_ID',
      'AWS_REGION',
      'AWS_SECRET_ACCESS_KEY',
      'FAL_API_KEY',
      'GF_DEV_ENABLE_SCHEDULERS',
      'GPU_LLM_INSTANCE_ID',
      'OPENROUTER_API_KEY',
      'REPLICATE_KEY',
    ],
    mappedKeys: {
      WORKERS_PORT: 'PORT',
      WORKERS_SENTRY_DSN: 'SENTRY_DSN',
      WORKERS_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'discord',
    path: 'apps/server/discord',
    generatedFileByMode: {
      local: 'apps/server/discord/.env.local',
      staging: 'apps/server/discord/.env.staging',
      production: 'apps/server/discord/.env.production',
    },
    localLegacyFile: 'apps/server/discord/.env',
    sharedKeys: [
      'GENFEEDAI_API_KEY',
      'GENFEEDAI_API_URL',
      'SENTRY_AUTH_TOKEN',
      'SENTRY_ENVIRONMENT',
    ],
    directKeys: ['DISCORD_BOT_TOKEN'],
    mappedKeys: {
      DISCORD_PORT: 'PORT',
      DISCORD_SENTRY_DSN: 'SENTRY_DSN',
      DISCORD_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'slack',
    path: 'apps/server/slack',
    generatedFileByMode: {
      local: 'apps/server/slack/.env.local',
      staging: 'apps/server/slack/.env.staging',
      production: 'apps/server/slack/.env.production',
    },
    sharedKeys: [
      'GENFEEDAI_API_KEY',
      'GENFEEDAI_API_URL',
      'SENTRY_AUTH_TOKEN',
      'SENTRY_ENVIRONMENT',
    ],
    directKeys: [],
    mappedKeys: {
      SLACK_PORT: 'PORT',
      SLACK_SENTRY_DSN: 'SENTRY_DSN',
      SLACK_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'telegram',
    path: 'apps/server/telegram',
    generatedFileByMode: {
      local: 'apps/server/telegram/.env.local',
      staging: 'apps/server/telegram/.env.staging',
      production: 'apps/server/telegram/.env.production',
    },
    localLegacyFile: 'apps/server/telegram/.env',
    sharedKeys: [
      'GENFEEDAI_API_KEY',
      'GENFEEDAI_API_URL',
      'SENTRY_AUTH_TOKEN',
      'SENTRY_ENVIRONMENT',
    ],
    directKeys: [],
    mappedKeys: {
      TELEGRAM_PORT: 'PORT',
      TELEGRAM_SENTRY_DSN: 'SENTRY_DSN',
      TELEGRAM_SERVICE_NAME: 'SERVICE_NAME',
    },
  },
  {
    id: 'docs',
    path: 'apps/docs',
    generatedFileByMode: {
      local: 'apps/docs/.env.local',
      staging: 'apps/docs/.env.staging',
      production: 'apps/docs/.env.production',
    },
    localLegacyFile: 'apps/docs/.env',
    sharedKeys: ['NEXT_PUBLIC_POSTHOG_HOST', 'NEXT_PUBLIC_POSTHOG_KEY'],
    directKeys: [],
    mappedKeys: {
      DOCS_PORT: 'PORT',
    },
  },
  {
    id: 'extension-browser',
    path: 'apps/extensions/browser/app',
    generatedFileByMode: {
      local: 'apps/extensions/browser/app/.env.local',
      staging: 'apps/extensions/browser/app/.env.staging',
      production: 'apps/extensions/browser/app/.env.production',
    },
    localLegacyFile: 'apps/extensions/browser/app/.env',
    sharedKeys: ['SENTRY_AUTH_TOKEN'],
    directKeys: [
      'NPM_TOKEN',
      'PLASMO_PUBLIC_API_ENDPOINT',
      'PLASMO_PUBLIC_APP_ENDPOINT',
      'PLASMO_PUBLIC_APP_VERSION',
      'PLASMO_PUBLIC_ASSETS_ENDPOINT',
      'PLASMO_PUBLIC_ENV',
      'PLASMO_PUBLIC_WEBSITE_ENDPOINT',
      'PLASMO_PUBLIC_WS_ENDPOINT',
    ],
    mappedKeys: {
      EXTENSION_BROWSER_PLASMO_PUBLIC_SENTRY_DSN: 'PLASMO_PUBLIC_SENTRY_DSN',
    },
  },
];

export const GENERATED_ENV_HEADER = [
  '# Generated by `bun run env:sync <local|staging|production>`.',
  '# Source of truth lives in the repo root env files.',
  '# Do not edit this file manually.',
  '',
];

export const LEGACY_ENV_HEADER = [
  '# Canonical env values now live in the repo root env files.',
  '# This file is intentionally kept comment-only to avoid stale overrides.',
  '# Run `bun run env:sync local` after updating the root env file.',
  '',
];

export const ROOT_ENV_SECTIONS: EnvSection[] = [
  {
    title: 'Shared Runtime',
    keys: ['NODE_ENV', 'DATABASE_URL', 'REDIS_URL'],
  },
  {
    title: 'Shared URLs',
    keys: [
      'API_URL',
      'GENFEEDAI_API_PUBLIC_URL',
      'GENFEEDAI_API_URL',
      'GENFEEDAI_APP_URL',
      'GENFEEDAI_PUBLIC_URL',
      'GENFEEDAI_CDN_URL',
      'GENFEEDAI_MCP_PUBLIC_URL',
      'GENFEEDAI_MICROSERVICES_FILES_URL',
      'GENFEEDAI_MICROSERVICES_MCP_URL',
      'GENFEEDAI_MICROSERVICES_NOTIFICATIONS_URL',
      'GENFEEDAI_WEBHOOKS_URL',
      'GENFEEDAI_API_KEY',
    ],
  },
  {
    title: 'Shared Auth And Edition',
    keys: [
      'BETTER_AUTH_ENABLED',
      'BETTER_AUTH_SECRET',
      'BETTER_AUTH_TRUSTED_ORIGINS',
      'BETTER_AUTH_URL',
      'GENFEED_CLOUD',
      'GENFEED_LICENSE_KEY',
      'NEXT_PUBLIC_BETTER_AUTH_ENABLED',
      'NEXT_PUBLIC_GENFEED_CLOUD',
      'NEXT_PUBLIC_GENFEED_EDITION',
      'NEXT_PUBLIC_GENFEED_LICENSE_KEY',
      'NEXT_PUBLIC_PLAYWRIGHT_TEST',
    ],
  },
  {
    title: 'Shared Frontend',
    keys: [
      'NEXT_PUBLIC_API_ENDPOINT',
      'NEXT_PUBLIC_API_URL',
      'NEXT_PUBLIC_WS_ENDPOINT',
      'NEXT_PUBLIC_CDN_URL',
      'NEXT_PUBLIC_MCP_ENDPOINT',
      'NEXT_PUBLIC_POSTHOG_HOST',
      'NEXT_PUBLIC_POSTHOG_KEY',
      'NEXT_PUBLIC_SENTRY_ENVIRONMENT',
      'SENTRY_ENVIRONMENT',
      'SENTRY_AUTH_TOKEN',
      'SENTRY_ORG',
    ],
  },
  {
    title: 'Frontend App',
    keys: [
      'APP_PORT',
      'APP_NEXT_PUBLIC_SENTRY_DSN',
      'APP_SENTRY_PROJECT',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_URL',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_URL',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FORCE_REDIRECT_URL',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FALLBACK_REDIRECT_URL',
      'APP_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FALLBACK_REDIRECT_URL',
      'APP_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
      'APP_MEDIUM_REDIRECT_URI',
      'NEXT_PUBLIC_TTS_ENABLED',
      // Browser-side checkout price IDs. They mirror the server-side
      // STRIPE_PRICE_SUBSCRIPTION_* values in the API section: the server pair
      // classifies an incoming price, this pair is what the customer is
      // actually charged, so the two must never drift apart.
      'NEXT_PUBLIC_STRIPE_PRICE_PAYG',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_PRO_MONTHLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_PRO_YEARLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_SCALE_MONTHLY',
      'NEXT_PUBLIC_STRIPE_PRICE_SUBSCRIPTION_ENTERPRISE_MONTHLY',
    ],
  },
  {
    title: 'Frontend Admin',
    keys: [
      'ADMIN_PORT',
      'ADMIN_NEXT_PUBLIC_SENTRY_DSN',
      'ADMIN_SENTRY_PROJECT',
      'ADMIN_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_URL',
      'ADMIN_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FORCE_REDIRECT_URL',
      'ADMIN_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
      'ADMIN_NEXT_PUBLIC_BETTER_AUTH_SIGN_IN_FALLBACK_REDIRECT_URL',
      'ADMIN_NEXT_PUBLIC_BETTER_AUTH_SIGN_UP_FALLBACK_REDIRECT_URL',
      'ADMIN_BETTER_AUTH_SIGN_UP_FORCE_REDIRECT_URL',
    ],
  },
  {
    title: 'Frontend Website',
    keys: [
      'WEBSITE_PORT',
      'WEBSITE_NEXT_PUBLIC_SENTRY_DSN',
      'WEBSITE_SENTRY_PROJECT',
      'NEXT_PUBLIC_ASSETS_ENDPOINT',
      'NEXT_PUBLIC_APPS_APP_ENDPOINT',
      'NEXT_PUBLIC_APPS_ADMIN_ENDPOINT',
      'NEXT_PUBLIC_APPS_MARKETPLACE_ENDPOINT',
      'NEXT_PUBLIC_APPS_WEBSITE_ENDPOINT',
      'NEXT_PUBLIC_CALENDLY_URL',
    ],
  },
  {
    title: 'API',
    keys: [
      'API_PORT',
      'API_SERVICE_NAME',
      'API_SENTRY_DSN',
      'MARKETPLACE_API_URL',
      'AWS_PROFILE',
      'AWS_REGION',
      'AWS_ACCESS_KEY_ID',
      'AWS_SECRET_ACCESS_KEY',
      'AWS_S3_BUCKET',
      'ARGIL_KEY',
      'ARGIL_WEBHOOK_SECRET',
      'ANTHROPIC_API_KEY',
      'OPENAI_API_KEY',
      'OPENAI_CODEX_REDIRECT_URI',
      'ELEVENLABS_API_KEY',
      'ELEVENLABS_MODEL',
      'NEWS_API_KEY',
      'NEWS_API_URL',
      'KLINGAI_KEY',
      'KLINGAI_SECRET',
      'KLINGAI_MODEL',
      'LEONARDO_KEY',
      'HEYGEN_KEY',
      'HEDRA_KEY',
      'GIPHY_API_KEY',
      'LOGO_DEV_PUBLISHABLE_KEY',
      'SOLANA_KEY',
      'SOLANA_URL',
      'REPLICATE_KEY',
      'REPLICATE_MODELS_TRAINER',
      'REPLICATE_MODEL_HARDWARE',
      'REPLICATE_MODEL_VISIBILITY',
      'REPLICATE_OWNER',
      'REPLICATE_TARGET_FPS',
      'REPLICATE_TARGET_RESOLUTION',
      'REPLICATE_WEBHOOK_SIGNING_SECRET',
      'TOKEN_ENCRYPTION_KEY',
      'BULL_BOARD_AUTH_TOKEN',
      'CHROME_EXTENSION_ID',
      'VERCEL_WEBHOOK_SECRET',
      'FACEBOOK_GRAPH_URL',
      'FACEBOOK_API_VERSION',
      'FACEBOOK_APP_ID',
      'FACEBOOK_APP_SECRET',
      'FACEBOOK_REDIRECT_URI',
      'FANVUE_CLIENT_ID',
      'FANVUE_CLIENT_SECRET',
      'FANVUE_REDIRECT_URI',
      'GOOGLE_ADS_CLIENT_ID',
      'GOOGLE_ADS_CLIENT_SECRET',
      'GOOGLE_ADS_DEVELOPER_TOKEN',
      'GOOGLE_ADS_REDIRECT_URI',
      'INSTAGRAM_GRAPH_URL',
      'INSTAGRAM_API_VERSION',
      'INSTAGRAM_CLIENT_ID',
      'INSTAGRAM_CLIENT_SECRET',
      'INSTAGRAM_APP_ID',
      'INSTAGRAM_APP_SECRET',
      'INSTAGRAM_REDIRECT_URI',
      'LINKEDIN_CLIENT_ID',
      'LINKEDIN_CLIENT_SECRET',
      'LINKEDIN_REDIRECT_URI',
      'MEDIUM_CLIENT_ID',
      'MEDIUM_CLIENT_SECRET',
      'PINTEREST_CLIENT_ID',
      'PINTEREST_CLIENT_SECRET',
      'PINTEREST_REDIRECT_URI',
      'REDDIT_CLIENT_ID',
      'REDDIT_CLIENT_SECRET',
      'REDDIT_REDIRECT_URI',
      'REDDIT_USER_AGENT',
      'SLACK_CLIENT_ID',
      'SLACK_CLIENT_SECRET',
      'SLACK_REDIRECT_URI',
      'SLACK_SIGNING_SECRET',
      'TIKTOK_CLIENT_KEY',
      'TIKTOK_CLIENT_SECRET',
      'THREADS_API_VERSION',
      'THREADS_CLIENT_ID',
      'THREADS_CLIENT_SECRET',
      'THREADS_GRAPH_URL',
      'THREADS_REDIRECT_URI',
      'TWITCH_CLIENT_ID',
      'TWITTER_BEARER_TOKEN',
      'TWITTER_CLIENT_ID',
      'TWITTER_CLIENT_SECRET',
      'TWITTER_CONSUMER_KEY',
      'TWITTER_CONSUMER_SECRET',
      'TWITTER_REDIRECT_URI',
      'X_ADS_API_KEY',
      'X_ADS_API_SECRET',
      'X_ADS_REDIRECT_URI',
      'X_ADS_REPOSITORY_COMMERCIAL_USE_APPROVED',
      'X_ADS_REPOSITORY_ENTITLEMENT_CONFIRMED',
      'YOUTUBE_API_KEY',
      'YOUTUBE_CLIENT_ID',
      'YOUTUBE_CLIENT_SECRET',
      'YOUTUBE_REDIRECT_URI',
      'RESTREAM_CLIENT_ID',
      'RESTREAM_CLIENT_SECRET',
      'RESTREAM_REDIRECT_URI',
      'STRIPE_API_VERSION',
      'STRIPE_SECRET_KEY',
      'STRIPE_PUBLISHABLE_KEY',
      'STRIPE_WEBHOOK_SIGNING_SECRET',
      'STRIPE_PAYG_CREDITS',
      'STRIPE_PRICE_PAYG',
      'STRIPE_PRICE_SKILLS_PRO',
      'STRIPE_PRICE_SUBSCRIPTION_PRO_MONTHLY',
      'STRIPE_PRICE_SUBSCRIPTION_PRO_YEARLY',
      'STRIPE_PRICE_SUBSCRIPTION_SCALE_MONTHLY',
      'STRIPE_PRICE_SUBSCRIPTION_ENTERPRISE_MONTHLY',
      'STRIPE_PROMOTION_CODE_LAUNCH',
      'STRIPE_PROMOTION_CODE_SKILLS_PRO',
      'TRAINING_TRAINING_CREDITS_COST',
      'TRAINING_CUSTOM_MODEL_CREDITS_COST',
    ],
  },
  {
    title: 'Files MCP Notifications',
    keys: [
      'FILES_PORT',
      'FILES_SERVICE_NAME',
      'FILES_SENTRY_DSN',
      'TEMP_DIR',
      'AWS_IMAGE_COMPRESSION',
      'WEBSOCKET_URL',
      'MCP_PORT',
      'MCP_SERVICE_NAME',
      'MCP_SENTRY_DSN',
      'POSTHOG_HOST',
      'POSTHOG_PROJECT_API_KEY',
      'VERSION',
      'NOTIFICATIONS_PORT',
      'NOTIFICATIONS_SERVICE_NAME',
      'NOTIFICATIONS_SENTRY_DSN',
      'API_BASE_URL',
      'API_SECRET_KEY',
      'DISCORD_BOT_TOKEN',
      'DISCORD_CLIENT_ID',
      'DISCORD_GUILD_ID',
      'DISCORD_CHANNEL_ID_DEPLOYMENTS',
      'DISCORD_CHANNEL_ID_POSTS',
      'DISCORD_CHANNEL_ID_STUDIO',
      'DISCORD_CHANNEL_ID_USERS',
      'TELEGRAM_BOT_TOKEN',
      'TELEGRAM_BOT_USERNAME',
      'TELEGRAM_ADMIN_IDS',
      'RESEND_API_KEY',
      'RESEND_FROM_EMAIL',
      'RESEND_REPLY_TO_EMAIL',
    ],
  },
  {
    title: 'Lightweight Services',
    keys: [
      'WORKERS_PORT',
      'WORKERS_SERVICE_NAME',
      'WORKERS_SENTRY_DSN',
      'GF_DEV_ENABLE_SCHEDULERS',
      'DISCORD_PORT',
      'DISCORD_SERVICE_NAME',
      'DISCORD_SENTRY_DSN',
      'SLACK_PORT',
      'SLACK_SERVICE_NAME',
      'SLACK_SENTRY_DSN',
      'TELEGRAM_PORT',
      'TELEGRAM_SERVICE_NAME',
      'TELEGRAM_SENTRY_DSN',
      'OPENROUTER_API_KEY',
    ],
  },
  {
    title: 'Docs And Browser Extension',
    keys: [
      'DOCS_PORT',
      'NPM_TOKEN',
      'PLASMO_PUBLIC_API_ENDPOINT',
      'PLASMO_PUBLIC_APP_ENDPOINT',
      'PLASMO_PUBLIC_APP_VERSION',
      'PLASMO_PUBLIC_ASSETS_ENDPOINT',
      'PLASMO_PUBLIC_ENV',
      'PLASMO_PUBLIC_WEBSITE_ENDPOINT',
      'PLASMO_PUBLIC_WS_ENDPOINT',
      'EXTENSION_BROWSER_PLASMO_PUBLIC_SENTRY_DSN',
    ],
  },
];

const KEY_TO_SECTION = new Map(
  ROOT_ENV_SECTIONS.flatMap((section, index) =>
    section.keys.map((key) => [key, { index, title: section.title }] as const),
  ),
);

export function getCanonicalEnvPath(mode: EnvMode): string {
  switch (mode) {
    case 'local':
      return '.env.local';
    case 'staging':
      return '.env.staging';
    case 'production':
      return '.env.production';
  }
}

export function getSectionForKey(key: string): {
  index: number;
  title: string;
} | null {
  return KEY_TO_SECTION.get(key) ?? null;
}
