import { createEntityAttributes } from '@genfeedai/helpers';

export const settingAttributes = createEntityAttributes([
  'agentMode',
  'theme',
  'locale',
  'isVerified',
  'isFirstLogin',
  'isMenuCollapsed',
  'isSidebarProgressVisible',
  'isSidebarProgressCollapsed',
  'contentPreferences',
  'favoriteModelKeys',
  'favoriteWorkflowIds',
  'pinnedAppIds',
  'isAgentAssetsPanelOpen',
  'dashboardPreferences',
  'generationPriority',
  'isTrendNotificationsInApp',
  'isTrendNotificationsTelegram',
  'isTrendNotificationsEmail',
  'isVideoNotificationsEmail',
  'trendNotificationsTelegramChatId',
  'trendNotificationsEmailAddress',
  'trendNotificationsFrequency',
  'trendNotificationsMinViralScore',
]);
