/** Persisted failure categories; values match Prisma AgentFailureReason. */
export enum AgentFailureReason {
  PROVIDER_CONFIGURATION = 'PROVIDER_CONFIGURATION',
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
  RATE_LIMITED = 'RATE_LIMITED',
  TIMEOUT = 'TIMEOUT',
  DATA_SAVE_FAILED = 'DATA_SAVE_FAILED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  CONNECTION_INTERRUPTED = 'CONNECTION_INTERRUPTED',
  CANCELLED = 'CANCELLED',
  PROVIDER_AUTHENTICATION = 'PROVIDER_AUTHENTICATION',
  WORKSPACE_MISSING = 'WORKSPACE_MISSING',
  ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED',
  MODEL_UNAVAILABLE = 'MODEL_UNAVAILABLE',
  PROVIDER_ACCESS_DENIED = 'PROVIDER_ACCESS_DENIED',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  UNKNOWN = 'UNKNOWN',
}
