export enum ByokProvider {
  ANTHROPIC = 'anthropic',
  OPENAI = 'openai',
  OPENROUTER = 'openrouter',
  ELEVENLABS = 'elevenlabs',
  REPLICATE = 'replicate',
  FAL = 'fal',
  CRUN = 'crun',
  ARGIL = 'argil',
  HEYGEN = 'heygen',
  HEDRA = 'hedra',
  KLINGAI = 'klingai',
  LEONARDOAI = 'leonardoai',
  HIGGSFIELD = 'higgsfield',
  APIFY = 'apify',
  GOOGLE = 'google',
  XAI = 'xai',
  BFL = 'bfl',
  RUNWAY = 'runway',
}
