export enum ByokProvider {
  ANTHROPIC = 'anthropic',
  OPENAI = 'openai',
  OPENROUTER = 'openrouter',
  ELEVENLABS = 'elevenlabs',
  REPLICATE = 'replicate',
  FAL = 'fal',
  ARGIL = 'argil',
  HEYGEN = 'heygen',
  HEDRA = 'hedra',
  KLINGAI = 'klingai',
  LEONARDOAI = 'leonardoai',
  HIGGSFIELD = 'higgsfield',
  APIFY = 'apify',
}
