import { createEntityAttributes } from '@genfeedai/helpers';

export const analyticsAttributes = createEntityAttributes([
  'totalCredentialsConnected',
  'totalPosts',
  'totalViews',
  'totalLikes',
  'totalComments',
  'totalShares',
  'totalSaves',
  'avgEngagementRate',
  'totalEngagement',
  'viewsGrowth',
  'engagementGrowth',
  'monthlyGrowth',
  'activePlatforms',
  'bestPerformingPlatform',
  'totalSubscriptions',
  'totalUsers',
  'totalBrands',
  'totalVideos',
  'totalImages',
  // Admin dashboard stats
  'totalOrganizations',
  'totalCredits',
  'activeWorkflows',
  'activeBots',
  'totalModels',
  'pendingPosts',
  'recentActivities',
]);
