/**
 * Seed Script: AI Models
 *
 * Seeds all AI models for image, video, text generation.
 * Uses upsert logic with field diffing - safe to run multiple times.
 *
 * Usage:
 *   bun run apps/server/api/scripts/seeds/models.seed.ts
 *   bun run apps/server/api/scripts/seeds/models.seed.ts --dry-run
 */

import { runScript } from '@api-scripts/db/connection';
import { parseArgs, seedDocuments } from '@api-scripts/db/seed-utils';
import { Logger } from '@nestjs/common';

const logger = new Logger('ModelsSeed');

const COLLECTION_NAME = 'models';

const FIELDS_TO_CHECK = [
  'label',
  'description',
  'category',
  'provider',
  'cost',
  'isActive',
  'isHighlighted',
  'isDefault',
  'isDeleted',
  'capabilities',
  'costTier',
  'speedTier',
  'qualityTier',
  'recommendedFor',
  'minDimensions',
  'maxDimensions',
  'supportsFeatures',
  'pricingType',
  'costPerUnit',
  'minCost',
  'aspectRatios',
  'defaultAspectRatio',
  'maxOutputs',
  'maxReferences',
  'isBatchSupported',
  'durations',
  'defaultDuration',
  'hasEndFrame',
  'hasInterpolation',
  'hasSpeech',
  'hasAudioToggle',
  'hasResolutionOptions',
  'isImagenModel',
  'isReferencesMandatory',
  'usesOrientation',
  'hasDurationEditing',
  'succeededBy',
  'predecessorOf',
  'inputCostPerMillionTokens',
  'outputCostPerMillionTokens',
  'providerCostUsd',
];

interface ModelDocument {
  key: string;
  label: string;
  description: string;
  category: string;
  provider: string;
  cost: number;
  isActive: boolean;
  isHighlighted: boolean;
  isDefault: boolean;
  isDeleted?: boolean;
  capabilities: string[];
  costTier: string;
  speedTier: string;
  qualityTier: string;
  recommendedFor: string[];
  minDimensions?: { width: number; height: number };
  maxDimensions?: { width: number; height: number };
  supportsFeatures: string[];
  pricingType?: string;
  costPerUnit?: number;
  minCost?: number;
  aspectRatios?: string[];
  defaultAspectRatio?: string;
  maxOutputs?: number;
  maxReferences?: number;
  isBatchSupported?: boolean;
  durations?: number[];
  defaultDuration?: number;
  hasEndFrame?: boolean;
  hasInterpolation?: boolean;
  hasSpeech?: boolean;
  hasAudioToggle?: boolean;
  hasResolutionOptions?: boolean;
  isImagenModel?: boolean;
  isReferencesMandatory?: boolean;
  usesOrientation?: boolean;
  hasDurationEditing?: boolean;
  succeededBy?: string;
  predecessorOf?: string;
  inputCostPerMillionTokens?: number;
  outputCostPerMillionTokens?: number;
  providerCostUsd?: number;
}

const models: ModelDocument[] = [
  // ============================================================================
  // GOOGLE MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    capabilities: ['quick', 'efficient', 'versatile', 'photorealistic'],
    category: 'image',
    cost: 10,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      "Fast version of Google's Imagen 3, optimized for speed with good quality",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    isImagenModel: true,
    key: 'google/imagen-3-fast',
    label: 'Imagen 3 Fast',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.02,
    qualityTier: 'standard',
    recommendedFor: ['quick', 'fast', 'draft', 'realistic'],
    speedTier: 'fast',
    succeededBy: 'google/imagen-4-fast',
    supportsFeatures: ['negative-prompt'],
  },
  {
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    capabilities: ['high-quality', 'photorealistic', 'versatile'],
    category: 'image',
    cost: 15,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "Google's base Imagen 3 model for high-quality image generation",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    isImagenModel: true,
    key: 'google/imagen-3',
    label: 'Imagen 3',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.04,
    qualityTier: 'high',
    recommendedFor: ['professional', 'photorealistic', 'creative'],
    speedTier: 'medium',
    succeededBy: 'google/imagen-4',
    supportsFeatures: ['negative-prompt', 'seed-control'],
  },
  {
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    capabilities: ['high-quality', 'photorealistic', 'versatile'],
    category: 'image',
    cost: 12,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description: "Google's standard Imagen 4 model with improved quality",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    isImagenModel: true,
    key: 'google/imagen-4',
    label: 'Imagen 4',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    predecessorOf: 'google/imagen-3',
    provider: 'replicate',
    providerCostUsd: 0.04,
    qualityTier: 'high',
    recommendedFor: ['professional', 'photorealistic', 'creative'],
    speedTier: 'medium',
    supportsFeatures: ['negative-prompt', 'seed-control'],
  },
  {
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    capabilities: ['fast', 'efficient', 'versatile'],
    category: 'image',
    cost: 10,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description: "Fast version of Google's Imagen 4, optimized for speed",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    isImagenModel: true,
    key: 'google/imagen-4-fast',
    label: 'Imagen 4 Fast',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    predecessorOf: 'google/imagen-3-fast',
    provider: 'replicate',
    providerCostUsd: 0.02,
    qualityTier: 'standard',
    recommendedFor: ['quick', 'draft', 'fast'],
    speedTier: 'fast',
    supportsFeatures: ['negative-prompt', 'seed-control'],
  },
  {
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    capabilities: ['ultra-quality', 'photorealistic', 'detailed'],
    category: 'image',
    cost: 15,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "Premium version of Google's Imagen 4 with highest quality output",
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isImagenModel: true,
    key: 'google/imagen-4-ultra',
    label: 'Imagen 4 Ultra',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.08,
    qualityTier: 'ultra',
    recommendedFor: ['professional', 'high-quality', 'detailed'],
    speedTier: 'slow',
    supportsFeatures: ['negative-prompt', 'seed-control'],
  },
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '9:16',
      '16:9',
      '21:9',
    ],
    capabilities: ['reference-guided', 'transformation', 'versatile'],
    category: 'image',
    cost: 15,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description: 'Image transformation with reference support (base version)',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'google/nano-banana',
    label: 'Nano Banana',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 15,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: ['transformation', 'reference', 'creative'],
    speedTier: 'fast',
    supportsFeatures: ['reference-images', 'seed-control'],
  },
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '9:16',
      '16:9',
      '21:9',
    ],
    capabilities: [
      'multi-reference',
      'resolution-control',
      'reference-guided',
      'transformation',
    ],
    category: 'image',
    cost: 50,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Enhanced image transformation with multi-image reference support (up to 14 images)',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'google/nano-banana-pro',
    label: 'Nano Banana Pro',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 4,
    maxReferences: 14,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'multi-reference',
      'transformation',
      'creative',
      'versatile',
      'high-resolution',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'multi-reference-images',
      'resolution-control',
      'match-input-aspect',
      'safety-filter',
    ],
  },
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '1:4',
      '1:8',
      '2:3',
      '3:2',
      '3:4',
      '4:1',
      '4:3',
      '4:5',
      '5:4',
      '8:1',
      '9:16',
      '16:9',
      '21:9',
    ],
    capabilities: [
      'multi-reference',
      'resolution-control',
      'reference-guided',
      'transformation',
      'google-search',
      'image-search',
    ],
    category: 'image',
    cost: 10,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "Google's fast image generation model with conversational editing, multi-image fusion, and character consistency",
    isActive: true,
    isDefault: true,
    isHighlighted: true,
    key: 'google/nano-banana-2',
    label: 'Nano Banana 2',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 4,
    maxReferences: 14,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'multi-reference',
      'transformation',
      'creative',
      'versatile',
      'high-resolution',
      'grounded-search',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'multi-reference-images',
      'resolution-control',
      'match-input-aspect',
      'google-search-grounding',
      'image-search-grounding',
      'safety-filter',
    ],
  },

  // ============================================================================
  // BLACK FOREST LABS MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'high-quality',
      'photorealistic',
      'flux-redux',
      'reference-guided',
    ],
    category: 'image',
    cost: 14,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'High-quality image generation with FLUX Redux support for reference-guided generation',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'black-forest-labs/flux-1.1-pro',
    label: 'FLUX 1.1 Pro',
    maxDimensions: { height: 1440, width: 1440 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.04,
    qualityTier: 'high',
    recommendedFor: [
      'professional',
      'high-quality',
      'detailed',
      'photorealistic',
      'creative',
    ],
    speedTier: 'medium',
    succeededBy: 'black-forest-labs/flux-2-pro',
    supportsFeatures: [
      'reference-images',
      'custom-dimensions',
      'prompt-upsampling',
      'seed-control',
    ],
  },
  {
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    capabilities: ['fast', 'efficient', 'quick-generation'],
    category: 'image',
    cost: 10,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description: 'Fast FLUX model optimized for speed with good quality output',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'black-forest-labs/flux-schnell',
    label: 'FLUX Schnell',
    maxDimensions: { height: 1440, width: 1440 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.003,
    qualityTier: 'standard',
    recommendedFor: [
      'quick',
      'draft',
      'fast',
      'efficient',
      'rapid-prototyping',
    ],
    speedTier: 'fast',
    supportsFeatures: ['seed-control', 'custom-dimensions'],
  },
  {
    aspectRatios: [
      'match_input_image',
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'high-quality',
      'multi-reference',
      'resolution-control',
      'photorealistic',
    ],
    category: 'image',
    cost: 20,
    costPerUnit: 20,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Professional-grade image generation with multi-image input support (up to 8 images)',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'black-forest-labs/flux-2-pro',
    label: 'FLUX 2 Pro',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 8,
    minCost: 20,
    minDimensions: { height: 256, width: 256 },
    predecessorOf: 'black-forest-labs/flux-1.1-pro',
    pricingType: 'per-megapixel',
    provider: 'replicate',
    providerCostUsd: 0.05,
    qualityTier: 'high',
    recommendedFor: [
      'professional',
      'high-quality',
      'multi-reference',
      'photorealistic',
      'creative',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'multi-reference-images',
      'resolution-control',
      'custom-dimensions',
      'seed-control',
      'match-input-aspect',
    ],
  },
  {
    aspectRatios: [
      'match_input_image',
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: ['fast', 'multi-reference', 'efficient', 'versatile'],
    category: 'image',
    cost: 16,
    costPerUnit: 16,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Next-generation image generation with multi-image input support (up to 4 images)',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'black-forest-labs/flux-2-dev',
    label: 'FLUX 2 Dev',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 4,
    minCost: 16,
    minDimensions: { height: 256, width: 256 },
    pricingType: 'per-megapixel',
    provider: 'replicate',
    providerCostUsd: 0.025,
    qualityTier: 'standard',
    recommendedFor: [
      'quick',
      'draft',
      'multi-reference',
      'versatile',
      'development',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'multi-reference-images',
      'custom-dimensions',
      'seed-control',
      'match-input-aspect',
    ],
  },
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '21:9',
      '9:21',
      '2:1',
      '1:2',
    ],
    capabilities: [
      'high-quality',
      'photorealistic',
      'reference-guided',
      'context-aware',
    ],
    category: 'image',
    cost: 14,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Advanced FLUX model with reference image support and intelligent prompt upsampling',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'black-forest-labs/flux-kontext-pro',
    label: 'FLUX Kontext Pro',
    maxDimensions: { height: 1440, width: 1440 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'professional',
      'high-quality',
      'detailed',
      'context-aware',
      'reference-based',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'reference-images',
      'prompt-upsampling',
      'seed-control',
      'match-input-aspect',
    ],
  },

  // ============================================================================
  // IDEOGRAM MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: [
      '1:3',
      '3:1',
      '1:2',
      '2:1',
      '9:16',
      '16:9',
      '10:16',
      '16:10',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '1:1',
    ],
    capabilities: ['fast', 'style-presets', 'reference-guided', 'versatile'],
    category: 'image',
    cost: 10,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Fast image generation with style presets and reference image support',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'ideogram-ai/ideogram-v3-turbo',
    label: 'Ideogram V3 Turbo',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 4,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.04,
    qualityTier: 'high',
    recommendedFor: ['quick', 'styled', 'artistic', 'creative', 'versatile'],
    speedTier: 'fast',
    supportsFeatures: [
      'style-presets',
      'reference-images',
      'seed-control',
      'magic-prompt',
      'multi-style-references',
    ],
  },
  {
    aspectRatios: [
      '1:3',
      '3:1',
      '1:2',
      '2:1',
      '9:16',
      '16:9',
      '10:16',
      '16:10',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '1:1',
    ],
    capabilities: [
      'balanced',
      'style-presets',
      'reference-guided',
      'versatile',
    ],
    category: 'image',
    cost: 20,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Balanced quality and speed with style presets and multi-reference support',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'ideogram-ai/ideogram-v3-balanced',
    label: 'Ideogram V3 Balanced',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 4,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.06,
    qualityTier: 'high',
    recommendedFor: ['balanced', 'styled', 'artistic', 'creative', 'versatile'],
    speedTier: 'medium',
    supportsFeatures: [
      'style-presets',
      'reference-images',
      'seed-control',
      'magic-prompt',
      'multi-style-references',
    ],
  },
  {
    aspectRatios: [
      '1:3',
      '3:1',
      '1:2',
      '2:1',
      '9:16',
      '16:9',
      '10:16',
      '16:10',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '1:1',
    ],
    capabilities: [
      'high-quality',
      'style-presets',
      'reference-guided',
      'detailed',
    ],
    category: 'image',
    cost: 30,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Highest quality Ideogram model with style presets and multi-reference support',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'ideogram-ai/ideogram-v3-quality',
    label: 'Ideogram V3 Quality',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 4,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    providerCostUsd: 0.08,
    qualityTier: 'ultra',
    recommendedFor: [
      'professional',
      'high-quality',
      'styled',
      'artistic',
      'detailed',
    ],
    speedTier: 'slow',
    supportsFeatures: [
      'style-presets',
      'reference-images',
      'seed-control',
      'magic-prompt',
      'multi-style-references',
    ],
  },
  {
    aspectRatios: [
      '1:3',
      '3:1',
      '1:2',
      '2:1',
      '9:16',
      '16:9',
      '10:16',
      '16:10',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '1:1',
    ],
    capabilities: ['character-consistency', 'reference-guided', 'high-quality'],
    category: 'image',
    cost: 40,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Specialized model for consistent character generation across multiple images',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isReferencesMandatory: true,
    key: 'ideogram-ai/ideogram-character',
    label: 'Ideogram Character',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'character',
      'consistent',
      'reference-based',
      'storytelling',
      'branding',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'character-reference',
      'style-reference',
      'seed-control',
      'negative-prompt',
    ],
  },

  // ============================================================================
  // BYTEDANCE MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '3:2',
      '2:3',
      '21:9',
    ],
    capabilities: [
      'multi-reference',
      'high-quality',
      'sequential-generation',
      'versatile',
    ],
    category: 'image',
    cost: 10,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "Bytedance's SeeDream 4 model for advanced image generation with multi-image reference support",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'bytedance/seedream-4',
    label: 'SeeDream 4',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 10,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'multi-reference',
      'high-quality',
      'detailed',
      'versatile',
      'creative',
    ],
    speedTier: 'medium',
    succeededBy: 'bytedance/seedream-4.5',
    supportsFeatures: [
      'multi-reference-images',
      'enhance-prompt',
      'match-input-aspect',
      'seed-control',
    ],
  },
  {
    aspectRatios: [
      'match_input_image',
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '3:2',
      '2:3',
      '21:9',
    ],
    capabilities: [
      'multi-reference',
      'batch-generation',
      'high-quality',
      'high-resolution',
    ],
    category: 'image',
    cost: 14,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "Bytedance's SeeDream 4.5 model with batch generation and high-resolution support",
    isActive: true,
    isBatchSupported: true,
    isDefault: false,
    isHighlighted: true,
    key: 'bytedance/seedream-4.5',
    label: 'SeeDream 4.5',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 4,
    maxReferences: 14,
    minDimensions: { height: 256, width: 256 },
    predecessorOf: 'bytedance/seedream-4',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'multi-reference',
      'batch',
      'high-quality',
      'high-resolution',
      'creative',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'multi-reference-images',
      'batch-generation',
      'match-input-aspect',
      'seed-control',
      '2k-4k-resolution',
    ],
  },

  // ============================================================================
  // RUNWAYML MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: ['16:9', '9:16', '4:3', '3:4', '1:1', '21:9'],
    capabilities: ['fast', 'reference-tags', 'multi-reference', 'high-quality'],
    category: 'image',
    cost: 20,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      'Fast image generation with reference tag system for naming and mentioning reference images',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'runwayml/gen4-image-turbo',
    label: 'Gen4 Image Turbo',
    maxDimensions: { height: 1920, width: 1920 },
    maxOutputs: 4,
    maxReferences: 3,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'fast',
      'reference-based',
      'creative',
      'character-consistency',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'reference-images',
      'reference-tags',
      'seed-control',
      '720p-1080p-resolution',
    ],
  },

  // ============================================================================
  // OPENAI MODELS - Image Generation
  // ============================================================================
  {
    aspectRatios: ['1:1', '3:2', '2:3'],
    capabilities: [
      'precise-control',
      'instruction-following',
      'image-editing',
      'photorealistic',
      'text-rendering',
    ],
    category: 'image',
    cost: 17,
    costTier: 'medium',
    defaultAspectRatio: '1:1',
    description:
      "OpenAI's latest image generation model with better instruction following and image editing",
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'openai/gpt-image-1.5',
    label: 'GPT Image 1.5',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 10,
    maxReferences: 10,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'medium',
    recommendedFor: [
      'professional',
      'photorealistic',
      'instruction-following',
      'image-editing',
      'text-in-images',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'multi-image-input',
      'aspect-ratio-control',
      'output-format',
      'quality-control',
      'background-control',
    ],
  },

  // ============================================================================
  // QWEN MODEL - Image Generation
  // ============================================================================
  {
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    capabilities: ['versatile', 'img2img', 'lora-support', 'customizable'],
    category: 'image',
    cost: 10,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Versatile image generation with img2img pipeline and LoRA support',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'qwen/qwen-image',
    label: 'Qwen Image',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 4,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: [
      'versatile',
      'customizable',
      'img2img',
      'training',
      'lora',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'img2img',
      'lora-weights',
      'negative-prompt',
      'seed-control',
      'enhance-prompt',
    ],
  },

  // ============================================================================
  // GOOGLE VEO MODELS - Video Generation
  // ============================================================================
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: ['cinematic', 'physics-simulation', 'versatile', 'long-form'],
    category: 'video',
    cost: 680,
    costPerUnit: 85,
    costTier: 'high',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Veo 2 faithfully follows instructions and simulates real-world physics with wide visual styles',
    durations: [5, 6, 7, 8],
    hasDurationEditing: true,
    hasSpeech: true,
    isActive: false,
    isDefault: false,
    isHighlighted: false,
    key: 'google/veo-2',
    label: 'Veo 2',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 425,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['cinematic', 'realistic', 'physics', 'long'],
    speedTier: 'slow',
    succeededBy: 'google/veo-3',
    supportsFeatures: ['image-to-video', 'physics'],
  },
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: [
      'cinematic',
      'speech-support',
      'high-quality',
      'audio-generation',
    ],
    category: 'video',
    cost: 1000,
    costPerUnit: 125,
    costTier: 'high',
    defaultAspectRatio: '16:9',
    defaultDuration: 8,
    description: "Google's flagship Veo 3 text to video model, with audio",
    durations: [4, 6, 8],
    hasDurationEditing: true,
    hasResolutionOptions: true,
    hasSpeech: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'google/veo-3',
    label: 'Veo 3',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 500,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'google/veo-2',
    pricingType: 'per-second',
    provider: 'replicate',
    providerCostUsd: 0.5,
    qualityTier: 'ultra',
    recommendedFor: ['cinematic', 'professional', 'speech', 'audio'],
    speedTier: 'slow',
    succeededBy: 'google/veo-3.1',
    supportsFeatures: ['speech', 'audio', 'image-to-video', 'negative-prompt'],
  },
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: ['quick', 'efficient', 'audio-generation'],
    category: 'video',
    cost: 640,
    costPerUnit: 80,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 8,
    description:
      "A faster and cheaper version of Google's Veo 3 video model, with audio",
    durations: [4, 6, 8],
    hasDurationEditing: true,
    hasResolutionOptions: true,
    hasSpeech: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'google/veo-3-fast',
    label: 'Veo 3 (Fast)',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 320,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    providerCostUsd: 0.25,
    qualityTier: 'high',
    recommendedFor: ['quick', 'fast', 'clip', 'short'],
    speedTier: 'fast',
    succeededBy: 'google/veo-3.1-fast',
    supportsFeatures: ['audio', 'image-to-video', 'negative-prompt'],
  },
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: [
      'cinematic',
      'r2v',
      'interpolation',
      'high-quality',
      'audio-generation',
    ],
    category: 'video',
    cost: 1000,
    costPerUnit: 125,
    costTier: 'high',
    defaultAspectRatio: '16:9',
    defaultDuration: 8,
    description:
      'Latest Veo model with reference-to-video, audio generation, and improved quality',
    durations: [4, 6, 8],
    hasAudioToggle: true,
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    hasResolutionOptions: true,
    hasSpeech: true,
    isActive: true,
    isDefault: true,
    isHighlighted: true,
    key: 'google/veo-3.1',
    label: 'Veo 3.1',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 3,
    minCost: 500,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'google/veo-3',
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'cinematic',
      'professional',
      'reference',
      'interpolation',
      'high-quality',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'reference-to-video',
      'interpolation',
      'audio',
      'negative-prompt',
    ],
  },
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: [
      'quick',
      'i2v',
      'interpolation',
      'efficient',
      'audio-generation',
    ],
    category: 'video',
    cost: 480,
    costPerUnit: 60,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 8,
    description:
      'Fast version of Veo 3.1 with image-to-video and interpolation support',
    durations: [4, 6, 8],
    hasAudioToggle: true,
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    hasResolutionOptions: true,
    hasSpeech: true,
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'google/veo-3.1-fast',
    label: 'Veo 3.1 (Fast)',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 240,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'google/veo-3-fast',
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['quick', 'fast', 'image-to-video', 'interpolation'],
    speedTier: 'fast',
    supportsFeatures: [
      'image-to-video',
      'interpolation',
      'audio',
      'negative-prompt',
    ],
  },

  // ============================================================================
  // KLING MODELS - Video Generation
  // ============================================================================
  {
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: [
      't2v',
      'i2v',
      'interpolation',
      'reference-images',
      'cfg-scale',
      'negative-prompt',
    ],
    category: 'video',
    cost: 400,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Video generation with I2V, interpolation, reference images, and CFG scale control',
    durations: [5, 10],
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'kwaivgi/kling-v1.6-pro',
    label: 'Kling V1.6 Pro',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 4,
    minCost: 250,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'video',
      'interpolation',
      'reference-guided',
      'scene-elements',
      'short-clips',
    ],
    speedTier: 'medium',
    succeededBy: 'kwaivgi/kling-v2.1',
    supportsFeatures: [
      't2v',
      'i2v',
      'interpolation',
      'reference-images',
      'cfg-scale',
      'negative-prompt',
      '5s-10s-duration',
      'aspect-ratio-control',
    ],
  },
  {
    aspectRatios: [],
    capabilities: ['i2v', 'negative-prompt', 'end-frame'],
    category: 'video',
    cost: 400,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Image-to-video generation, 5s and 10s videos in 720p and 1080p resolution',
    durations: [5, 10],
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'kwaivgi/kling-v2.1',
    label: 'Kling V2.1',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 250,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'kwaivgi/kling-v1.6-pro',
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['i2v', 'video', 'short-clips'],
    speedTier: 'medium',
    supportsFeatures: [
      'i2v',
      'negative-prompt',
      '5s-10s-duration',
      '720p-1080p-resolution',
      'end-frame',
      'pro-mode',
    ],
  },
  {
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: ['fast', 't2v', 'i2v', 'negative-prompt'],
    category: 'video',
    cost: 400,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Fast video generation with T2V and I2V modes, 5 or 10 second duration support',
    durations: [5, 10],
    hasDurationEditing: true,
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'kwaivgi/kling-v2.5-turbo-pro',
    label: 'Kling V2.5 Turbo Pro',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 250,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['fast-video', 't2v', 'i2v', 'short-clips'],
    speedTier: 'fast',
    supportsFeatures: ['t2v', 'i2v', 'negative-prompt', '5s-10s-duration'],
  },
  {
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: [
      't2v',
      'i2v',
      'audio-generation',
      'multi-shot',
      'cinematic',
      'negative-prompt',
    ],
    category: 'video',
    cost: 500,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Cinematic video up to 15s with native audio generation, lip-synced dialogue, and multi-shot narratives',
    durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    hasAudioToggle: true,
    hasDurationEditing: true,
    hasSpeech: true,
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'kwaivgi/kling-v3-video',
    label: 'Kling V3',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 250,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'kwaivgi/kling-v2.5-turbo-pro',
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: ['cinematic', 'audio', 'multi-shot', 'professional'],
    speedTier: 'medium',
    supportsFeatures: [
      't2v',
      'i2v',
      'audio-generation',
      'multi-shot',
      'negative-prompt',
      '3s-15s-duration',
    ],
  },
  {
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: [
      't2v',
      'i2v',
      'r2v',
      'video-editing',
      'reference-images',
      'audio-generation',
    ],
    category: 'video',
    cost: 600,
    costPerUnit: 60,
    costTier: 'high',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Unified model: text-to-video, image-to-video, reference-based generation, and video editing with character consistency',
    durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    hasAudioToggle: true,
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    hasSpeech: true,
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'kwaivgi/kling-v3-omni-video',
    label: 'Kling V3 Omni',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 4,
    maxReferences: 7,
    minCost: 300,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'cinematic',
      'reference',
      'video-editing',
      'character-consistency',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      't2v',
      'i2v',
      'r2v',
      'video-editing',
      'reference-images',
      'audio-generation',
      'negative-prompt',
    ],
  },
  {
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: ['avatar', 'lip-sync', 'talking-head', 'portrait-animation'],
    category: 'video',
    cost: 500,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 10,
    description:
      'Talking avatar from portrait image + audio with lip-synced expressions, 48fps output up to 1080p',
    durations: [5, 10, 15, 30, 60],
    hasDurationEditing: false,
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'kwaivgi/kling-avatar-v2',
    label: 'Kling Avatar V2',
    maxDimensions: { height: 1080, width: 1080 },
    maxOutputs: 1,
    maxReferences: 1,
    minCost: 250,
    minDimensions: { height: 256, width: 256 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'avatar',
      'talking-head',
      'lip-sync',
      'portrait-animation',
      'social-media',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'avatar',
      'lip-sync',
      'portrait-animation',
      'audio-driven',
    ],
  },

  // ============================================================================
  // WAN VIDEO MODEL - Video Generation
  // ============================================================================
  {
    aspectRatios: ['16:9', '9:16'],
    capabilities: ['i2v', 'fast', 'high-framerate', 'efficient'],
    category: 'video',
    cost: 560,
    costPerUnit: 70,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description: 'Fast image-to-video generation with high frame rate support',
    durations: [5],
    hasDurationEditing: true,
    hasEndFrame: true,
    hasInterpolation: true,
    hasResolutionOptions: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'wan-video/wan-2.2-i2v-fast',
    label: 'WAN Video 2.2 I2V Fast',
    maxDimensions: { height: 1280, width: 1280 },
    maxOutputs: 4,
    maxReferences: 2,
    minCost: 350,
    minDimensions: { height: 512, width: 512 },
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: ['i2v', 'fast', 'animation', 'motion', 'quick-turnaround'],
    speedTier: 'fast',
    supportsFeatures: [
      'i2v',
      'high-framerate',
      'custom-resolution',
      'seed-control',
    ],
  },

  // PrunaAI P-Video
  {
    aspectRatios: ['16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '1:1'],
    capabilities: ['t2v', 'i2v', 'a2v', 'lip-sync', 'draft-mode', 'versatile'],
    category: 'video',
    cost: 500,
    costPerUnit: 50,
    costTier: 'medium',
    defaultAspectRatio: '16:9',
    defaultDuration: 5,
    description:
      'Unified video generation: text-to-video, image-to-video, and audio-to-video with lip-sync support',
    durations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    hasDurationEditing: true,
    hasResolutionOptions: true,
    hasSpeech: true,
    isActive: false,
    isDefault: false,
    isHighlighted: false,
    key: 'prunaai/p-video',
    label: 'P-Video',
    maxOutputs: 4,
    maxReferences: 1,
    minCost: 250,
    pricingType: 'per-second',
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: ['lip-sync', 'avatar', 'talking-head', 'fast', 'versatile'],
    speedTier: 'fast',
    supportsFeatures: [
      't2v',
      'i2v',
      'a2v',
      'lip-sync',
      'draft-mode',
      'resolution-options',
      'seed-control',
    ],
  },

  // ============================================================================
  // TEXT / LLM MODELS - Text Generation
  // ============================================================================
  {
    capabilities: [
      'reasoning',
      'code-generation',
      'logical-analysis',
      'multilingual',
    ],
    category: 'text',
    cost: 5,
    costTier: 'low',
    description:
      'Advanced reasoning model optimized for complex tasks, code generation, and logical analysis',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'deepseek-ai/deepseek-r1',
    label: 'DeepSeek R1',
    maxOutputs: 1,
    maxReferences: 0,
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: ['articles', 'reasoning', 'code', 'analysis', 'long-form'],
    speedTier: 'medium',
    supportsFeatures: [
      'temperature-control',
      'max-tokens',
      'presence-penalty',
      'frequency-penalty',
    ],
  },
  {
    capabilities: [
      'high-quality',
      'creative-writing',
      'instruction-following',
      'long-form',
    ],
    category: 'text',
    cost: 1,
    costTier: 'medium',
    description:
      'Anthropic Claude 4.5 Sonnet on Replicate for high-quality writing, editing, and structured content generation',
    inputCostPerMillionTokens: 1000,
    isActive: true,
    isDefault: true,
    isHighlighted: true,
    key: 'anthropic/claude-4.5-sonnet',
    label: 'Claude 4.5 Sonnet',
    maxOutputs: 1,
    maxReferences: 0,
    minCost: 1,
    outputCostPerMillionTokens: 5000,
    pricingType: 'per-token',
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'tweets',
      'newsletters',
      'articles',
      'copywriting',
      'editing',
      'long-form',
    ],
    speedTier: 'medium',
    supportsFeatures: ['system-prompt', 'temperature-control', 'max-tokens'],
  },
  {
    capabilities: [
      'advanced-reasoning',
      'multimodal',
      'reasoning-effort',
      'verbosity-control',
      'high-quality',
    ],
    category: 'text',
    cost: 3,
    costTier: 'medium',
    description:
      'Advanced text generation model with reasoning capabilities and multimodal understanding',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'openai/gpt-5.2',
    label: 'GPT-5.2',
    maxOutputs: 1,
    maxReferences: 10,
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'posts',
      'articles',
      'titles',
      'content-generation',
      'multimodal',
      'reasoning',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'system-prompt',
      'image-input',
      'reasoning-effort',
      'verbosity',
      'max-completion-tokens',
    ],
  },
  {
    capabilities: ['fast', 'multimodal', 'reasoning', 'efficient'],
    category: 'text',
    cost: 2,
    costTier: 'low',
    description:
      'Fast multimodal reasoning model optimized for speed and cost-efficiency',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'google/gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    maxOutputs: 1,
    maxReferences: 10,
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['tweets', 'captions', 'quick-generation', 'multimodal'],
    speedTier: 'fast',
    supportsFeatures: [
      'system-instruction',
      'image-input',
      'temperature-control',
      'max-tokens',
    ],
  },
  {
    capabilities: [
      'advanced-reasoning',
      'multimodal',
      'thinking-mode',
      'high-quality',
    ],
    category: 'text',
    cost: 10,
    costTier: 'medium',
    description:
      'Most advanced reasoning Gemini model with extended thinking capabilities',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'google/gemini-3-pro',
    label: 'Gemini 3 Pro',
    maxOutputs: 1,
    maxReferences: 10,
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'articles',
      'complex-reasoning',
      'analysis',
      'professional',
      'long-form',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'system-instruction',
      'image-input',
      'video-input',
      'audio-input',
      'thinking-level',
      'temperature-control',
      'max-tokens',
    ],
  },
  {
    capabilities: [
      'versatile',
      'instruction-following',
      'multilingual',
      'creative',
    ],
    category: 'text',
    cost: 8,
    costTier: 'medium',
    description:
      'Large language model from Meta, excellent for general-purpose text generation',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'meta/meta-llama-3.1-405b-instruct',
    label: 'Meta Llama 3.1',
    maxOutputs: 1,
    maxReferences: 0,
    provider: 'replicate',
    providerCostUsd: 0.0005,
    qualityTier: 'high',
    recommendedFor: [
      'prompts',
      'enhancement',
      'creative',
      'versatile',
      'general-purpose',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'system-prompt',
      'temperature-control',
      'top-p',
      'top-k',
      'presence-penalty',
      'frequency-penalty',
      'max-tokens',
    ],
  },

  // ============================================================================
  // XAI GROK MODELS - Text Generation (via OpenRouter)
  // ============================================================================
  {
    capabilities: ['fast', 'multimodal', 'reasoning', 'real-time-knowledge'],
    category: 'text',
    cost: 3,
    costTier: 'low',
    description:
      'Fast multimodal model from xAI with real-time knowledge and SOTA cost-efficiency',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'x-ai/grok-4-fast',
    label: 'Grok 4 Fast',
    maxOutputs: 1,
    maxReferences: 0,
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'posts',
      'tweets',
      'captions',
      'quick-generation',
      'trends',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'system-prompt',
      'temperature-control',
      'max-tokens',
      'image-input',
    ],
  },
  {
    capabilities: [
      'advanced-reasoning',
      'multimodal',
      'real-time-knowledge',
      'high-quality',
    ],
    category: 'text',
    cost: 10,
    costTier: 'medium',
    description:
      'Most advanced reasoning model from xAI with deep thinking and multimodal understanding',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'x-ai/grok-4',
    label: 'Grok 4',
    maxOutputs: 1,
    maxReferences: 0,
    provider: 'replicate',
    qualityTier: 'ultra',
    recommendedFor: [
      'articles',
      'complex-reasoning',
      'analysis',
      'professional',
      'long-form',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'system-prompt',
      'temperature-control',
      'max-tokens',
      'image-input',
    ],
  },
  {
    capabilities: [
      'fast',
      'multimodal',
      'reasoning',
      'agent-tools',
      'real-time-knowledge',
    ],
    category: 'text',
    cost: 3,
    costTier: 'low',
    description:
      'Latest iteration of xAI fast model with improved agent tool use and reasoning',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'x-ai/grok-4.1-fast',
    label: 'Grok 4.1 Fast',
    maxOutputs: 1,
    maxReferences: 0,
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: [
      'posts',
      'tweets',
      'captions',
      'quick-generation',
      'agents',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'system-prompt',
      'temperature-control',
      'max-tokens',
      'image-input',
    ],
  },

  // ============================================================================
  // EMBEDDING MODELS - Vector Generation
  // ============================================================================
  {
    capabilities: [
      'text-embedding',
      'image-embedding',
      'semantic-search',
      'similarity',
    ],
    category: 'embedding',
    cost: 1,
    costTier: 'low',
    description:
      "OpenAI's CLIP model for generating text and image embeddings for semantic search",
    isActive: true,
    isDefault: true,
    isHighlighted: false,
    key: 'openai/clip',
    label: 'CLIP',
    maxOutputs: 1,
    maxReferences: 1,
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['embedding', 'semantic-search', 'rag', 'similarity'],
    speedTier: 'fast',
    supportsFeatures: ['text-input', 'image-input'],
  },

  // ============================================================================
  // GENFEED AI SELF-HOSTED MODELS (ComfyUI on gpu.genfeed.ai)
  // ============================================================================
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: ['fast', 'self-hosted', 'no-queue', 'zero-cost'],
    category: 'image',
    cost: 0,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'FLUX.1 Dev running on Genfeed AI GPU — fast, no queue, zero external API cost',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'genfeed-ai/flux-dev',
    label: 'Flux Dev (Self-Hosted)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 0,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: ['quick', 'draft', 'iteration', 'free-generation'],
    speedTier: 'fast',
    succeededBy: 'genfeed-ai/flux2-dev',
    supportsFeatures: ['seed-control', 'custom-dimensions', 'negative-prompt'],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'face-consistent',
      'self-hosted',
      'reference-guided',
      'zero-cost',
    ],
    category: 'image',
    cost: 0,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Face-consistent image generation using FLUX Dev + PuLID on Genfeed AI GPU',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isReferencesMandatory: true,
    key: 'genfeed-ai/flux-dev-pulid',
    label: 'Flux Dev + PuLID (Self-Hosted)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: [
      'character',
      'face-consistency',
      'portrait',
      'reference-based',
    ],
    speedTier: 'medium',
    succeededBy: 'genfeed-ai/flux2-dev-pulid',
    supportsFeatures: [
      'reference-images',
      'seed-control',
      'custom-dimensions',
      'face-id',
    ],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: ['ultra-fast', 'self-hosted', 'few-steps', 'zero-cost'],
    category: 'image',
    cost: 0,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Ultra-fast image generation in 4 steps on Genfeed AI GPU — ideal for rapid iteration',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'genfeed-ai/z-image-turbo',
    label: 'Z-Image Turbo (Self-Hosted)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 0,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'standard',
    recommendedFor: ['rapid', 'iteration', 'draft', 'speed'],
    speedTier: 'fast',
    supportsFeatures: ['seed-control', 'custom-dimensions'],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: ['high-quality', 'self-hosted', 'flux2', 'low-cost'],
    category: 'image',
    cost: 1,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Flux 2 Dev fp8 on Genfeed AI GPU — next-gen quality with split UNET + Mistral 3 encoder',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'genfeed-ai/flux2-dev',
    label: 'Flux 2 Dev (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 0,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'genfeed-ai/flux-dev',
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: ['professional', 'high-quality', 'creative', 'iteration'],
    speedTier: 'medium',
    supportsFeatures: ['seed-control', 'custom-dimensions'],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'face-consistent',
      'self-hosted',
      'flux2',
      'reference-guided',
      'low-cost',
    ],
    category: 'image',
    cost: 2,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Face-consistent Flux 2 generation with PuLID identity preservation on Genfeed AI GPU',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isReferencesMandatory: true,
    key: 'genfeed-ai/flux2-dev-pulid',
    label: 'Flux 2 Dev + PuLID (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 512, width: 512 },
    predecessorOf: 'genfeed-ai/flux-dev-pulid',
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: [
      'character',
      'face-consistency',
      'portrait',
      'reference-based',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'reference-images',
      'seed-control',
      'custom-dimensions',
      'face-id',
    ],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'face-consistent',
      'self-hosted',
      'flux2',
      'lora-support',
      'reference-guided',
      'low-cost',
    ],
    category: 'image',
    cost: 2,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Face-consistent Flux 2 with LoRA customization — character styles and realism on Genfeed AI GPU',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isReferencesMandatory: true,
    key: 'genfeed-ai/flux2-dev-pulid-lora',
    label: 'Flux 2 Dev + PuLID + LoRA (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: [
      'character',
      'face-consistency',
      'styled',
      'lora',
      'custom-style',
    ],
    speedTier: 'medium',
    supportsFeatures: [
      'reference-images',
      'seed-control',
      'custom-dimensions',
      'face-id',
      'lora-weights',
    ],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'face-consistent',
      'self-hosted',
      'flux2',
      '4k-upscale',
      'reference-guided',
      'low-cost',
    ],
    category: 'image',
    cost: 3,
    costTier: 'low',
    defaultAspectRatio: '4:5',
    description:
      'Face-consistent Flux 2 with 4x UltraSharp upscale — generates 4K+ images on Genfeed AI GPU',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    isReferencesMandatory: true,
    key: 'genfeed-ai/flux2-dev-pulid-upscale',
    label: 'Flux 2 Dev + PuLID + 4K Upscale (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'ultra',
    recommendedFor: [
      'instagram',
      'portrait',
      'face-consistency',
      '4k',
      'high-resolution',
    ],
    speedTier: 'slow',
    supportsFeatures: [
      'reference-images',
      'seed-control',
      'custom-dimensions',
      'face-id',
      '4k-upscale',
    ],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: ['fast', 'self-hosted', 'flux2', 'few-steps', 'low-cost'],
    category: 'image',
    cost: 1,
    costTier: 'low',
    defaultAspectRatio: '1:1',
    description:
      'Fast Flux 2 Klein 9B on Genfeed AI GPU — quick generation in 4-8 steps',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'genfeed-ai/flux2-klein',
    label: 'Flux 2 Klein (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 0,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'standard',
    recommendedFor: ['quick', 'draft', 'fast', 'iteration'],
    speedTier: 'fast',
    supportsFeatures: ['seed-control', 'custom-dimensions'],
  },
  {
    aspectRatios: [
      'custom',
      '1:1',
      '16:9',
      '3:2',
      '2:3',
      '4:5',
      '5:4',
      '9:16',
      '3:4',
      '4:3',
    ],
    capabilities: [
      'face-consistent',
      'self-hosted',
      'lora-support',
      '4k-upscale',
      'low-cost',
    ],
    category: 'image',
    cost: 2,
    costTier: 'low',
    defaultAspectRatio: '4:5',
    description:
      'Face-consistent Z-Image Turbo with trained LoRA + 4x upscale on Genfeed AI GPU — character identity without PuLID',
    isActive: true,
    isDefault: false,
    isHighlighted: true,
    key: 'genfeed-ai/z-image-turbo-lora',
    label: 'Z-Image Turbo + LoRA (GPU)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 0,
    minDimensions: { height: 512, width: 512 },
    provider: 'genfeed-ai',
    qualityTier: 'high',
    recommendedFor: [
      'character',
      'face-consistency',
      'instagram',
      'portrait',
      'lora',
    ],
    speedTier: 'fast',
    supportsFeatures: [
      'seed-control',
      'custom-dimensions',
      'lora-weights',
      '4k-upscale',
    ],
  },

  // ============================================================================
  // UPSCALING MODELS
  // ============================================================================
  {
    capabilities: ['upscaling', 'enhancement', 'detail-preservation'],
    category: 'image-upscale',
    cost: 10,
    costTier: 'low',
    description: 'AI-powered image upscaling with detail enhancement',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'topazlabs/image-upscale',
    label: 'Topaz (Image)',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 64, width: 64 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['upscale', 'enhance', 'high-resolution'],
    speedTier: 'fast',
    supportsFeatures: ['upscale-factor'],
  },
  {
    capabilities: ['upscaling', 'enhancement', 'frame-interpolation'],
    category: 'video-upscale',
    cost: 30,
    costTier: 'medium',
    description: 'AI-powered video upscaling with frame enhancement',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'topazlabs/video-upscale',
    label: 'Topaz (Video)',
    maxDimensions: { height: 4096, width: 4096 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 64, width: 64 },
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['upscale', 'enhance', 'video-quality'],
    speedTier: 'slow',
    supportsFeatures: ['upscale-factor'],
  },

  // ============================================================================
  // REFRAME MODELS
  // ============================================================================
  {
    aspectRatios: ['1:1', '3:4', '4:3', '9:16', '16:9', '21:9', '9:21'],
    capabilities: ['reframing', 'aspect-ratio', 'outpainting'],
    category: 'image-edit',
    cost: 10,
    costTier: 'low',
    defaultAspectRatio: '9:16',
    description: 'AI-powered image reframing and aspect ratio adjustment',
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'luma/reframe-image',
    label: 'Luma (Reframe Image)',
    maxDimensions: { height: 2048, width: 2048 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: ['reframe', 'resize', 'outpaint'],
    speedTier: 'fast',
    supportsFeatures: ['aspect-ratio', 'outpainting'],
  },
  {
    aspectRatios: ['1:1', '3:4', '4:3', '9:16', '16:9', '21:9', '9:21'],
    capabilities: ['reframing', 'aspect-ratio', 'video-editing'],
    category: 'video-edit',
    cost: 20,
    costTier: 'medium',
    defaultAspectRatio: '9:16',
    description: 'AI-powered video reframing and aspect ratio adjustment',
    hasDurationEditing: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'luma/reframe-video',
    label: 'Luma (Reframe Video)',
    maxDimensions: { height: 1080, width: 1920 },
    maxOutputs: 1,
    maxReferences: 1,
    minDimensions: { height: 256, width: 256 },
    provider: 'replicate',
    qualityTier: 'standard',
    recommendedFor: ['reframe', 'resize', 'video-editing'],
    speedTier: 'medium',
    supportsFeatures: ['aspect-ratio'],
  },

  // ============================================================================
  // AUDIO MODELS
  // ============================================================================
  {
    capabilities: ['music-generation', 'audio', 'creative'],
    category: 'music',
    cost: 25,
    costTier: 'low',
    defaultDuration: 10,
    description: "Meta's AI music generation model",
    durations: [5, 10, 15, 30],
    hasDurationEditing: true,
    isActive: true,
    isDefault: false,
    isHighlighted: false,
    key: 'meta/musicgen',
    label: 'MusicGen',
    maxOutputs: 4,
    maxReferences: 1,
    provider: 'replicate',
    qualityTier: 'high',
    recommendedFor: ['music', 'audio', 'background-music'],
    speedTier: 'medium',
    supportsFeatures: ['duration-control', 'melody-conditioning'],
  },
];

// Run the seed
const args = parseArgs();

runScript(
  'Models Seed',
  (db) => {
    return seedDocuments(db, COLLECTION_NAME, models, {
      dryRun: args.dryRun,
      fieldsToCheck: FIELDS_TO_CHECK,
      keyField: 'key',
    });
  },
  { database: args.database, uri: args.uri },
).catch((error) => {
  logger.error('Seed failed:', error);
  process.exit(1);
});
